/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_prio(clk, rst_b, valid, clr, sel);
  input clk;
  wire clk;
  input rst_b;
  wire rst_b;
  input [1:0] valid;
  wire [1:0] valid;
  input clr;
  wire clr;
  output [1:0] sel;
  wire [1:0] sel;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [1:0] \prio[0] ;
  wire [1:0] \prio[1] ;
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(\prio[0] [0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(\prio[1] [1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _12_ (
    .A(valid[1]),
    .B(\prio[0] [1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__and3_1 _13_ (
    .A(valid[0]),
    .B(_04_),
    .C(_06_),
    .X(sel[0])
  );
  sky130_fd_sc_hd__nand2_1 _14_ (
    .A(valid[0]),
    .B(\prio[1] [0]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and3_1 _15_ (
    .A(valid[1]),
    .B(_05_),
    .C(_07_),
    .X(sel[1])
  );
  sky130_fd_sc_hd__a31oi_1 _16_ (
    .A1(valid[0]),
    .A2(_04_),
    .A3(clr),
    .B1(\prio[0] [1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_1 _17_ (
    .A1(clr),
    .A2(sel[1]),
    .B1(_08_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a31oi_1 _18_ (
    .A1(valid[1]),
    .A2(clr),
    .A3(_05_),
    .B1(\prio[1] [0]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__a21oi_1 _19_ (
    .A1(clr),
    .A2(sel[0]),
    .B1(_09_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__buf_1 _20_ (
    .A(\prio[0] [0]),
    .X(_00_)
  );
  sky130_fd_sc_hd__buf_1 _21_ (
    .A(\prio[1] [1]),
    .X(_02_)
  );
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(clk),
    .D(_00_),
    .Q(\prio[0] [0]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _23_ (
    .CLK(clk),
    .D(_01_),
    .Q(\prio[0] [1]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfstp_2 _24_ (
    .CLK(clk),
    .D(_03_),
    .Q(\prio[1] [0]),
    .SET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(clk),
    .D(_02_),
    .Q(\prio[1] [1]),
    .RESET_B(rst_b)
  );
endmodule
