/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_prio_gate(clk, rst_b, valid, clr, sel);
  input clk;
  wire clk;
  input rst_b;
  wire rst_b;
  input [1:0] valid;
  wire [1:0] valid;
  input clr;
  wire clr;
  output [1:0] sel;
  wire [1:0] sel;
  wire _0_;
  wire _1_;
  wire _2_;
  wire prio_1_over_0;
  wire _ppa_bad_0;
  wire _ppa_bad_1;
  wire _ppa_bad_2;
  wire _ppa_bad_3;
  wire _ppa_bad_4;
  wire _ppa_bad_5;
  wire _ppa_bad_6;
  wire _ppa_bad_7;
  wire _ppa_bad_8;
  wire _ppa_bad_9;
  wire _ppa_bad_10;
  wire _ppa_bad_11;
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(prio_1_over_0),
    .Y(_2_)
  );
  sky130_fd_sc_hd__a21boi_0 _4_ (
    .A1(prio_1_over_0),
    .A2(valid[1]),
    .B1_N(valid[0]),
    .Y(sel[0])
  );
  sky130_fd_sc_hd__a21boi_0 _5_ (
    .A1(_2_),
    .A2(valid[0]),
    .B1_N(valid[1]),
    .Y(sel[1])
  );
  sky130_fd_sc_hd__a21boi_0 _6_ (
    .A1(valid[1]),
    .A2(clr),
    .B1_N(prio_1_over_0),
    .Y(_1_)
  );
  sky130_fd_sc_hd__a31o_1 _7_ (
    .A1(_2_),
    .A2(valid[0]),
    .A3(clr),
    .B1(_1_),
    .X(_0_)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_0 (
    .A(_0_),
    .X(_ppa_bad_0)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_1 (
    .A(_ppa_bad_0),
    .X(_ppa_bad_1)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_2 (
    .A(_ppa_bad_1),
    .X(_ppa_bad_2)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_3 (
    .A(_ppa_bad_2),
    .X(_ppa_bad_3)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_4 (
    .A(_ppa_bad_3),
    .X(_ppa_bad_4)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_5 (
    .A(_ppa_bad_4),
    .X(_ppa_bad_5)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_6 (
    .A(_ppa_bad_5),
    .X(_ppa_bad_6)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_7 (
    .A(_ppa_bad_6),
    .X(_ppa_bad_7)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_8 (
    .A(_ppa_bad_7),
    .X(_ppa_bad_8)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_9 (
    .A(_ppa_bad_8),
    .X(_ppa_bad_9)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_10 (
    .A(_ppa_bad_9),
    .X(_ppa_bad_10)
  );
  sky130_fd_sc_hd__buf_16 _ppa_bad_buf_11 (
    .A(_ppa_bad_10),
    .X(_ppa_bad_11)
  );
  sky130_fd_sc_hd__dfrtp_1 _8_ (
    .CLK(clk),
    .D(_ppa_bad_11),
    .Q(prio_1_over_0),
    .RESET_B(rst_b)
  );
endmodule
