/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_vfmau_ff1_10bit(ff1_data, ff1_result);
  input [9:0] ff1_data;
  wire [9:0] ff1_data;
  output [3:0] ff1_result;
  wire [3:0] ff1_result;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [9:0] onehot;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _14_ (
    .A(ff1_data[3]),
    .SLEEP(ff1_data[4]),
    .X(_00_)
  );
  sky130_fd_sc_hd__nor2_1 _15_ (
    .A(ff1_data[7]),
    .B(ff1_data[8]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor3_1 _16_ (
    .A(ff1_data[7]),
    .B(ff1_data[8]),
    .C(ff1_data[9]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__o21ai_0 _17_ (
    .A1(ff1_data[5]),
    .A2(_00_),
    .B1(_02_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _18_ (
    .A(ff1_data[3]),
    .B(ff1_data[4]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor4_1 _19_ (
    .A(ff1_data[3]),
    .B(ff1_data[4]),
    .C(ff1_data[5]),
    .D(ff1_data[6]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _20_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _21_ (
    .A(ff1_data[1]),
    .SLEEP(ff1_data[2]),
    .X(_07_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _22_ (
    .A(ff1_data[7]),
    .SLEEP(ff1_data[8]),
    .X(_08_)
  );
  sky130_fd_sc_hd__a311oi_1 _23_ (
    .A1(_02_),
    .A2(_05_),
    .A3(_07_),
    .B1(_08_),
    .C1(ff1_data[9]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _24_ (
    .A1(ff1_data[6]),
    .A2(_03_),
    .B1(_09_),
    .Y(ff1_result[0])
  );
  sky130_fd_sc_hd__o31a_1 _25_ (
    .A1(ff1_data[5]),
    .A2(ff1_data[6]),
    .A3(_04_),
    .B1(_01_),
    .X(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _26_ (
    .A(ff1_data[2]),
    .B(ff1_data[1]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _27_ (
    .A(ff1_data[0]),
    .B(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o22ai_1 _28_ (
    .A1(ff1_data[9]),
    .A2(_10_),
    .B1(_12_),
    .B2(_06_),
    .Y(ff1_result[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _29_ (
    .A(_02_),
    .SLEEP(_05_),
    .X(ff1_result[2])
  );
  sky130_fd_sc_hd__nor3_1 _30_ (
    .A(ff1_data[2]),
    .B(ff1_data[1]),
    .C(ff1_data[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _31_ (
    .A(_06_),
    .B(_13_),
    .Y(ff1_result[3])
  );
  assign onehot[9] = ff1_data[9];
endmodule
