/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_vfmau_ff1_10bit(ff1_data, ff1_result);
  input [9:0] ff1_data;
  wire [9:0] ff1_data;
  output [3:0] ff1_result;
  wire [3:0] ff1_result;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  sky130_fd_sc_hd__nor2_1 _14_ (
    .A(ff1_data[6]),
    .B(ff1_data[5]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor4_1 _15_ (
    .A(ff1_data[6]),
    .B(ff1_data[5]),
    .C(ff1_data[4]),
    .D(ff1_data[3]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(ff1_data[8]),
    .B(ff1_data[9]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor3_1 _17_ (
    .A(ff1_data[7]),
    .B(ff1_data[8]),
    .C(ff1_data[9]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__or3_1 _18_ (
    .A(ff1_data[7]),
    .B(ff1_data[8]),
    .C(ff1_data[9]),
    .X(_04_)
  );
  sky130_fd_sc_hd__nor4_1 _19_ (
    .A(ff1_data[7]),
    .B(ff1_data[8]),
    .C(ff1_data[9]),
    .D(ff1_data[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand4b_1 _20_ (
    .A_N(ff1_data[1]),
    .B(_01_),
    .C(_05_),
    .D(ff1_data[0]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor4b_1 _21_ (
    .A(ff1_data[6]),
    .B(ff1_data[5]),
    .C(ff1_data[4]),
    .D_N(ff1_data[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o21ai_0 _22_ (
    .A1(ff1_data[7]),
    .A2(_07_),
    .B1(_02_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand2b_1 _23_ (
    .A_N(ff1_data[9]),
    .B(ff1_data[8]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand3_1 _24_ (
    .A(ff1_data[4]),
    .B(_00_),
    .C(_03_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nand4_1 _25_ (
    .A(_06_),
    .B(_08_),
    .C(_09_),
    .D(_10_),
    .Y(ff1_result[1])
  );
  sky130_fd_sc_hd__nor2_1 _26_ (
    .A(_01_),
    .B(_04_),
    .Y(ff1_result[2])
  );
  sky130_fd_sc_hd__nand3_1 _27_ (
    .A(ff1_data[1]),
    .B(_01_),
    .C(_05_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o311a_1 _28_ (
    .A1(ff1_data[2]),
    .A2(ff1_data[0]),
    .A3(ff1_data[1]),
    .B1(_01_),
    .C1(_03_),
    .X(ff1_result[3])
  );
  sky130_fd_sc_hd__o21ai_0 _29_ (
    .A1(_01_),
    .A2(_04_),
    .B1(_09_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand3b_1 _30_ (
    .A_N(ff1_data[6]),
    .B(ff1_data[5]),
    .C(_03_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o2111ai_1 _31_ (
    .A1(ff1_result[3]),
    .A2(_12_),
    .B1(_13_),
    .C1(_11_),
    .D1(_08_),
    .Y(ff1_result[0])
  );
endmodule
