/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_lsu_spec_fail_predict(cp0_lsu_icg_en, cpurst_b, forever_cpuclk, ld_da_sf_addr_tto4, ld_da_sf_bytes_vld, ld_da_sf_spec_chk_req, pad_yy_icg_scan_en, rtu_lsu_spec_fail_flush, rtu_lsu_spec_fail_iid, rtu_yy_xx_flush, sf_spec_hit, sf_spec_mark, st_da_sf_addr_tto4, st_da_sf_bytes_vld, st_da_sf_iid, st_da_sf_no_spec_miss, st_da_sf_no_spec_miss_gate, st_da_sf_spec_chk, st_da_sf_spec_chk_gate);
  input cp0_lsu_icg_en;
  wire cp0_lsu_icg_en;
  input cpurst_b;
  wire cpurst_b;
  input forever_cpuclk;
  wire forever_cpuclk;
  input [35:0] ld_da_sf_addr_tto4;
  wire [35:0] ld_da_sf_addr_tto4;
  input [15:0] ld_da_sf_bytes_vld;
  wire [15:0] ld_da_sf_bytes_vld;
  input ld_da_sf_spec_chk_req;
  wire ld_da_sf_spec_chk_req;
  input pad_yy_icg_scan_en;
  wire pad_yy_icg_scan_en;
  input rtu_lsu_spec_fail_flush;
  wire rtu_lsu_spec_fail_flush;
  input [6:0] rtu_lsu_spec_fail_iid;
  wire [6:0] rtu_lsu_spec_fail_iid;
  input rtu_yy_xx_flush;
  wire rtu_yy_xx_flush;
  output sf_spec_hit;
  wire sf_spec_hit;
  output sf_spec_mark;
  wire sf_spec_mark;
  input [35:0] st_da_sf_addr_tto4;
  wire [35:0] st_da_sf_addr_tto4;
  input [15:0] st_da_sf_bytes_vld;
  wire [15:0] st_da_sf_bytes_vld;
  input [6:0] st_da_sf_iid;
  wire [6:0] st_da_sf_iid;
  input st_da_sf_no_spec_miss;
  wire st_da_sf_no_spec_miss;
  input st_da_sf_no_spec_miss_gate;
  wire st_da_sf_no_spec_miss_gate;
  input st_da_sf_spec_chk;
  wire st_da_sf_spec_chk;
  input st_da_sf_spec_chk_gate;
  wire st_da_sf_spec_chk_gate;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire ld_hit_sf_mispred_chk;
  wire ld_hit_sf_start;
  wire sf_clk;
  wire sf_clk_en;
  wire [15:0] sf_mispred_chk_bytes_vld;
  wire [3:0] sf_mispred_chk_clr_counter;
  wire sf_mispred_chk_iid_newer_than_st_da;
  wire [35:0] sf_mispred_chk_st_addr_tto4;
  wire [6:0] sf_mispred_chk_st_iid;
  wire sf_mispred_chk_vld;
  wire sf_pred_chk_dp_clk;
  wire sf_pred_chk_dp_clk_en;
  wire [3:0] sf_start_clr_counter;
  wire sf_start_dp_clk;
  wire sf_start_dp_clk_en;
  wire sf_start_iid_newer_than_st_da;
  wire sf_start_pre;
  wire [35:0] sf_start_st_addr_tto4;
  wire [15:0] sf_start_st_bytes_vld;
  wire [6:0] sf_start_st_iid;
  wire sf_start_vld;
  sky130_fd_sc_hd__clkinv_1 _0509_ (
    .A(rtu_lsu_spec_fail_iid[6]),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__clkinv_1 _0510_ (
    .A(sf_start_st_iid[3]),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__clkinv_1 _0511_ (
    .A(sf_mispred_chk_vld),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__clkinv_1 _0512_ (
    .A(sf_mispred_chk_st_addr_tto4[26]),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__clkinv_1 _0513_ (
    .A(ld_da_sf_addr_tto4[6]),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__clkinv_1 _0514_ (
    .A(sf_mispred_chk_st_addr_tto4[1]),
    .Y(_0134_)
  );
  sky130_fd_sc_hd__clkinv_1 _0515_ (
    .A(ld_da_sf_addr_tto4[1]),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__clkinv_1 _0516_ (
    .A(ld_da_sf_addr_tto4[4]),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__clkinv_1 _0517_ (
    .A(ld_da_sf_addr_tto4[24]),
    .Y(_0137_)
  );
  sky130_fd_sc_hd__clkinv_1 _0518_ (
    .A(sf_mispred_chk_st_addr_tto4[24]),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__clkinv_1 _0519_ (
    .A(ld_da_sf_addr_tto4[23]),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__clkinv_1 _0520_ (
    .A(ld_da_sf_addr_tto4[30]),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__clkinv_1 _0521_ (
    .A(ld_da_sf_addr_tto4[15]),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__clkinv_1 _0522_ (
    .A(ld_da_sf_addr_tto4[8]),
    .Y(_0142_)
  );
  sky130_fd_sc_hd__clkinv_1 _0523_ (
    .A(sf_mispred_chk_st_addr_tto4[32]),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__clkinv_1 _0524_ (
    .A(ld_da_sf_addr_tto4[29]),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__clkinv_1 _0525_ (
    .A(sf_mispred_chk_st_addr_tto4[29]),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__clkinv_1 _0526_ (
    .A(ld_da_sf_addr_tto4[22]),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__clkinv_1 _0527_ (
    .A(ld_da_sf_addr_tto4[3]),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__clkinv_1 _0528_ (
    .A(ld_da_sf_addr_tto4[21]),
    .Y(_0148_)
  );
  sky130_fd_sc_hd__clkinv_1 _0529_ (
    .A(ld_da_sf_addr_tto4[34]),
    .Y(_0149_)
  );
  sky130_fd_sc_hd__clkinv_1 _0530_ (
    .A(ld_da_sf_addr_tto4[5]),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__clkinv_1 _0531_ (
    .A(ld_da_sf_addr_tto4[33]),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__clkinv_1 _0532_ (
    .A(sf_mispred_chk_st_addr_tto4[12]),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__clkinv_1 _0533_ (
    .A(ld_da_sf_addr_tto4[12]),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__clkinv_1 _0534_ (
    .A(ld_da_sf_addr_tto4[18]),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__clkinv_1 _0535_ (
    .A(sf_mispred_chk_st_addr_tto4[11]),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__clkinv_1 _0536_ (
    .A(ld_da_sf_addr_tto4[19]),
    .Y(_0156_)
  );
  sky130_fd_sc_hd__clkinv_1 _0537_ (
    .A(sf_start_vld),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__clkinv_1 _0538_ (
    .A(sf_start_st_addr_tto4[2]),
    .Y(_0158_)
  );
  sky130_fd_sc_hd__clkinv_1 _0539_ (
    .A(sf_start_st_addr_tto4[28]),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__clkinv_1 _0540_ (
    .A(sf_start_st_addr_tto4[10]),
    .Y(_0160_)
  );
  sky130_fd_sc_hd__clkinv_1 _0541_ (
    .A(sf_start_st_addr_tto4[16]),
    .Y(_0161_)
  );
  sky130_fd_sc_hd__clkinv_1 _0542_ (
    .A(sf_start_st_addr_tto4[7]),
    .Y(_0162_)
  );
  sky130_fd_sc_hd__clkinv_1 _0543_ (
    .A(sf_start_st_addr_tto4[25]),
    .Y(_0163_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0544_ (
    .A(sf_mispred_chk_st_addr_tto4[18]),
    .SLEEP(ld_da_sf_addr_tto4[18]),
    .X(_0164_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0545_ (
    .A(sf_mispred_chk_st_addr_tto4[0]),
    .SLEEP(ld_da_sf_addr_tto4[0]),
    .X(_0165_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0546_ (
    .A(ld_da_sf_addr_tto4[31]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[31]),
    .X(_0166_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0547_ (
    .A(ld_da_sf_addr_tto4[0]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[0]),
    .X(_0167_)
  );
  sky130_fd_sc_hd__nor4_1 _0548_ (
    .A(_0164_),
    .B(_0165_),
    .C(_0166_),
    .D(_0167_),
    .Y(_0168_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0549_ (
    .A(sf_mispred_chk_st_addr_tto4[17]),
    .SLEEP(ld_da_sf_addr_tto4[17]),
    .X(_0169_)
  );
  sky130_fd_sc_hd__a21oi_1 _0550_ (
    .A1(sf_mispred_chk_st_addr_tto4[3]),
    .A2(_0147_),
    .B1(_0169_),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__nor2_1 _0551_ (
    .A(sf_mispred_chk_st_addr_tto4[3]),
    .B(_0147_),
    .Y(_0171_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0552_ (
    .A(sf_mispred_chk_st_addr_tto4[4]),
    .SLEEP(ld_da_sf_addr_tto4[4]),
    .X(_0172_)
  );
  sky130_fd_sc_hd__nor3b_1 _0553_ (
    .A(_0171_),
    .B(_0172_),
    .C_N(_0170_),
    .Y(_0173_)
  );
  sky130_fd_sc_hd__nand2b_1 _0554_ (
    .A_N(sf_mispred_chk_st_addr_tto4[32]),
    .B(ld_da_sf_addr_tto4[32]),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__nand2b_1 _0555_ (
    .A_N(ld_da_sf_addr_tto4[28]),
    .B(sf_mispred_chk_st_addr_tto4[28]),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nand2b_1 _0556_ (
    .A_N(ld_da_sf_addr_tto4[8]),
    .B(sf_mispred_chk_st_addr_tto4[8]),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__nand2b_1 _0557_ (
    .A_N(ld_da_sf_addr_tto4[9]),
    .B(sf_mispred_chk_st_addr_tto4[9]),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nand4_1 _0558_ (
    .A(_0174_),
    .B(_0175_),
    .C(_0176_),
    .D(_0177_),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0559_ (
    .A(sf_mispred_chk_st_addr_tto4[21]),
    .SLEEP(ld_da_sf_addr_tto4[21]),
    .X(_0179_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0560_ (
    .A(ld_da_sf_addr_tto4[27]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[27]),
    .X(_0180_)
  );
  sky130_fd_sc_hd__o22ai_1 _0561_ (
    .A1(sf_mispred_chk_st_addr_tto4[22]),
    .A2(_0146_),
    .B1(sf_mispred_chk_st_addr_tto4[33]),
    .B2(_0151_),
    .Y(_0181_)
  );
  sky130_fd_sc_hd__nor4_1 _0562_ (
    .A(_0178_),
    .B(_0179_),
    .C(_0180_),
    .D(_0181_),
    .Y(_0182_)
  );
  sky130_fd_sc_hd__xnor2_1 _0563_ (
    .A(ld_da_sf_addr_tto4[7]),
    .B(sf_mispred_chk_st_addr_tto4[7]),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__xnor2_1 _0564_ (
    .A(ld_da_sf_addr_tto4[10]),
    .B(sf_mispred_chk_st_addr_tto4[10]),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__xor2_1 _0565_ (
    .A(sf_mispred_chk_st_addr_tto4[13]),
    .B(ld_da_sf_addr_tto4[13]),
    .X(_0185_)
  );
  sky130_fd_sc_hd__xnor2_1 _0566_ (
    .A(sf_mispred_chk_st_addr_tto4[13]),
    .B(ld_da_sf_addr_tto4[13]),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__nand3_1 _0567_ (
    .A(_0183_),
    .B(_0184_),
    .C(_0186_),
    .Y(_0187_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0568_ (
    .A(ld_da_sf_addr_tto4[17]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[17]),
    .X(_0188_)
  );
  sky130_fd_sc_hd__a21oi_1 _0569_ (
    .A1(_0155_),
    .A2(ld_da_sf_addr_tto4[11]),
    .B1(_0188_),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__o221ai_1 _0570_ (
    .A1(ld_da_sf_addr_tto4[24]),
    .A2(_0138_),
    .B1(_0155_),
    .B2(ld_da_sf_addr_tto4[11]),
    .C1(_0189_),
    .Y(_0190_)
  );
  sky130_fd_sc_hd__xor2_1 _0571_ (
    .A(sf_mispred_chk_st_addr_tto4[20]),
    .B(ld_da_sf_addr_tto4[20]),
    .X(_0191_)
  );
  sky130_fd_sc_hd__o21ai_0 _0572_ (
    .A1(_0137_),
    .A2(sf_mispred_chk_st_addr_tto4[24]),
    .B1(sf_mispred_chk_vld),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__nor4_1 _0573_ (
    .A(_0187_),
    .B(_0190_),
    .C(_0191_),
    .D(_0192_),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__nand4_1 _0574_ (
    .A(_0168_),
    .B(_0173_),
    .C(_0182_),
    .D(_0193_),
    .Y(_0194_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0575_ (
    .A(sf_mispred_chk_st_addr_tto4[35]),
    .SLEEP(ld_da_sf_addr_tto4[35]),
    .X(_0195_)
  );
  sky130_fd_sc_hd__a21oi_1 _0576_ (
    .A1(sf_mispred_chk_st_addr_tto4[5]),
    .A2(_0150_),
    .B1(_0195_),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__xnor2_1 _0577_ (
    .A(ld_da_sf_addr_tto4[29]),
    .B(sf_mispred_chk_st_addr_tto4[29]),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _0578_ (
    .A1_N(_0141_),
    .A2_N(sf_mispred_chk_st_addr_tto4[15]),
    .B1(sf_mispred_chk_st_addr_tto4[12]),
    .B2(_0153_),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__xnor2_1 _0579_ (
    .A(ld_da_sf_addr_tto4[30]),
    .B(sf_mispred_chk_st_addr_tto4[30]),
    .Y(_0199_)
  );
  sky130_fd_sc_hd__nand4_1 _0580_ (
    .A(_0196_),
    .B(_0197_),
    .C(_0198_),
    .D(_0199_),
    .Y(_0200_)
  );
  sky130_fd_sc_hd__nand2b_1 _0581_ (
    .A_N(sf_mispred_chk_st_addr_tto4[26]),
    .B(ld_da_sf_addr_tto4[26]),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__nand2b_1 _0582_ (
    .A_N(sf_mispred_chk_st_addr_tto4[4]),
    .B(ld_da_sf_addr_tto4[4]),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__nand2_1 _0583_ (
    .A(_0201_),
    .B(_0202_),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _0584_ (
    .A1_N(sf_mispred_chk_st_addr_tto4[22]),
    .A2_N(_0146_),
    .B1(sf_mispred_chk_st_addr_tto4[8]),
    .B2(_0142_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__nand2b_1 _0585_ (
    .A_N(sf_mispred_chk_st_addr_tto4[5]),
    .B(ld_da_sf_addr_tto4[5]),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__nand2b_1 _0586_ (
    .A_N(ld_da_sf_addr_tto4[2]),
    .B(sf_mispred_chk_st_addr_tto4[2]),
    .Y(_0206_)
  );
  sky130_fd_sc_hd__nand2b_1 _0587_ (
    .A_N(ld_da_sf_addr_tto4[33]),
    .B(sf_mispred_chk_st_addr_tto4[33]),
    .Y(_0207_)
  );
  sky130_fd_sc_hd__nand2b_1 _0588_ (
    .A_N(ld_da_sf_addr_tto4[27]),
    .B(sf_mispred_chk_st_addr_tto4[27]),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__nand4_1 _0589_ (
    .A(_0205_),
    .B(_0206_),
    .C(_0207_),
    .D(_0208_),
    .Y(_0209_)
  );
  sky130_fd_sc_hd__nor4_1 _0590_ (
    .A(_0200_),
    .B(_0203_),
    .C(_0204_),
    .D(_0209_),
    .Y(_0210_)
  );
  sky130_fd_sc_hd__nor2_1 _0591_ (
    .A(sf_mispred_chk_st_addr_tto4[12]),
    .B(_0153_),
    .Y(_0211_)
  );
  sky130_fd_sc_hd__nor2_1 _0592_ (
    .A(ld_da_sf_addr_tto4[32]),
    .B(_0143_),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__xor2_1 _0593_ (
    .A(ld_da_sf_addr_tto4[34]),
    .B(sf_mispred_chk_st_addr_tto4[34]),
    .X(_0213_)
  );
  sky130_fd_sc_hd__nor3_1 _0594_ (
    .A(_0211_),
    .B(_0212_),
    .C(_0213_),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__a22o_1 _0595_ (
    .A1(_0139_),
    .A2(sf_mispred_chk_st_addr_tto4[23]),
    .B1(_0141_),
    .B2(sf_mispred_chk_st_addr_tto4[15]),
    .X(_0215_)
  );
  sky130_fd_sc_hd__a22oi_1 _0596_ (
    .A1(sf_mispred_chk_st_addr_tto4[1]),
    .A2(_0135_),
    .B1(sf_mispred_chk_st_addr_tto4[19]),
    .B2(_0156_),
    .Y(_0216_)
  );
  sky130_fd_sc_hd__nor2b_1 _0597_ (
    .A(_0215_),
    .B_N(_0216_),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0598_ (
    .A(ld_da_sf_addr_tto4[25]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[25]),
    .X(_0218_)
  );
  sky130_fd_sc_hd__o22ai_1 _0599_ (
    .A1(_0132_),
    .A2(ld_da_sf_addr_tto4[26]),
    .B1(_0133_),
    .B2(sf_mispred_chk_st_addr_tto4[6]),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__nand2b_1 _0600_ (
    .A_N(sf_mispred_chk_st_addr_tto4[21]),
    .B(ld_da_sf_addr_tto4[21]),
    .Y(_0220_)
  );
  sky130_fd_sc_hd__nand2b_1 _0601_ (
    .A_N(ld_da_sf_addr_tto4[16]),
    .B(sf_mispred_chk_st_addr_tto4[16]),
    .Y(_0221_)
  );
  sky130_fd_sc_hd__nand2b_1 _0602_ (
    .A_N(sf_mispred_chk_st_addr_tto4[16]),
    .B(ld_da_sf_addr_tto4[16]),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__nand2b_1 _0603_ (
    .A_N(ld_da_sf_addr_tto4[25]),
    .B(sf_mispred_chk_st_addr_tto4[25]),
    .Y(_0223_)
  );
  sky130_fd_sc_hd__nand4_1 _0604_ (
    .A(_0220_),
    .B(_0221_),
    .C(_0222_),
    .D(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0605_ (
    .A1(_0134_),
    .A2(ld_da_sf_addr_tto4[1]),
    .B1(_0218_),
    .C1(_0219_),
    .D1(_0224_),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__nand4_1 _0606_ (
    .A(_0210_),
    .B(_0214_),
    .C(_0217_),
    .D(_0225_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__a22oi_1 _0607_ (
    .A1(ld_da_sf_bytes_vld[11]),
    .A2(sf_mispred_chk_bytes_vld[11]),
    .B1(ld_da_sf_bytes_vld[15]),
    .B2(sf_mispred_chk_bytes_vld[15]),
    .Y(_0227_)
  );
  sky130_fd_sc_hd__a22oi_1 _0608_ (
    .A1(ld_da_sf_bytes_vld[0]),
    .A2(sf_mispred_chk_bytes_vld[0]),
    .B1(ld_da_sf_bytes_vld[1]),
    .B2(sf_mispred_chk_bytes_vld[1]),
    .Y(_0228_)
  );
  sky130_fd_sc_hd__a22oi_1 _0609_ (
    .A1(ld_da_sf_bytes_vld[3]),
    .A2(sf_mispred_chk_bytes_vld[3]),
    .B1(ld_da_sf_bytes_vld[10]),
    .B2(sf_mispred_chk_bytes_vld[10]),
    .Y(_0229_)
  );
  sky130_fd_sc_hd__a222oi_1 _0610_ (
    .A1(ld_da_sf_bytes_vld[7]),
    .A2(sf_mispred_chk_bytes_vld[7]),
    .B1(ld_da_sf_bytes_vld[8]),
    .B2(sf_mispred_chk_bytes_vld[8]),
    .C1(ld_da_sf_bytes_vld[2]),
    .C2(sf_mispred_chk_bytes_vld[2]),
    .Y(_0230_)
  );
  sky130_fd_sc_hd__a222oi_1 _0611_ (
    .A1(ld_da_sf_bytes_vld[5]),
    .A2(sf_mispred_chk_bytes_vld[5]),
    .B1(ld_da_sf_bytes_vld[6]),
    .B2(sf_mispred_chk_bytes_vld[6]),
    .C1(ld_da_sf_bytes_vld[12]),
    .C2(sf_mispred_chk_bytes_vld[12]),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__nand3_1 _0612_ (
    .A(_0227_),
    .B(_0230_),
    .C(_0231_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__a222oi_1 _0613_ (
    .A1(ld_da_sf_bytes_vld[14]),
    .A2(sf_mispred_chk_bytes_vld[14]),
    .B1(ld_da_sf_bytes_vld[4]),
    .B2(sf_mispred_chk_bytes_vld[4]),
    .C1(ld_da_sf_bytes_vld[9]),
    .C2(sf_mispred_chk_bytes_vld[9]),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__nand3_1 _0614_ (
    .A(_0228_),
    .B(_0229_),
    .C(_0233_),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__a211oi_1 _0615_ (
    .A1(ld_da_sf_bytes_vld[13]),
    .A2(sf_mispred_chk_bytes_vld[13]),
    .B1(_0232_),
    .C1(_0234_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0616_ (
    .A(ld_da_sf_addr_tto4[14]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[14]),
    .X(_0236_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0617_ (
    .A(ld_da_sf_addr_tto4[19]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[19]),
    .X(_0237_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0618_ (
    .A(sf_mispred_chk_st_addr_tto4[14]),
    .SLEEP(ld_da_sf_addr_tto4[14]),
    .X(_0238_)
  );
  sky130_fd_sc_hd__nor3_1 _0619_ (
    .A(_0236_),
    .B(_0237_),
    .C(_0238_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0620_ (
    .A(sf_mispred_chk_st_addr_tto4[6]),
    .SLEEP(ld_da_sf_addr_tto4[6]),
    .X(_0240_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0621_ (
    .A(ld_da_sf_addr_tto4[2]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[2]),
    .X(_0241_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0622_ (
    .A(ld_da_sf_addr_tto4[23]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[23]),
    .X(_0242_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0623_ (
    .A(ld_da_sf_addr_tto4[18]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[18]),
    .X(_0243_)
  );
  sky130_fd_sc_hd__nor4_1 _0624_ (
    .A(_0240_),
    .B(_0241_),
    .C(_0242_),
    .D(_0243_),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0625_ (
    .A(ld_da_sf_addr_tto4[9]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[9]),
    .X(_0245_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0626_ (
    .A(ld_da_sf_addr_tto4[35]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[35]),
    .X(_0246_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0627_ (
    .A(sf_mispred_chk_st_addr_tto4[31]),
    .SLEEP(ld_da_sf_addr_tto4[31]),
    .X(_0247_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0628_ (
    .A(ld_da_sf_addr_tto4[28]),
    .SLEEP(sf_mispred_chk_st_addr_tto4[28]),
    .X(_0248_)
  );
  sky130_fd_sc_hd__nor4_1 _0629_ (
    .A(_0245_),
    .B(_0246_),
    .C(_0247_),
    .D(_0248_),
    .Y(_0249_)
  );
  sky130_fd_sc_hd__nand3_1 _0630_ (
    .A(_0239_),
    .B(_0244_),
    .C(_0249_),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__nor4_1 _0631_ (
    .A(_0194_),
    .B(_0226_),
    .C(_0235_),
    .D(_0250_),
    .Y(sf_spec_hit)
  );
  sky130_fd_sc_hd__a22o_1 _0632_ (
    .A1(_0140_),
    .A2(sf_start_st_addr_tto4[30]),
    .B1(sf_start_st_addr_tto4[21]),
    .B2(_0148_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__a221o_1 _0633_ (
    .A1(ld_da_sf_addr_tto4[2]),
    .A2(_0158_),
    .B1(sf_start_st_addr_tto4[3]),
    .B2(_0147_),
    .C1(_0251_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__o22ai_1 _0634_ (
    .A1(_0142_),
    .A2(sf_start_st_addr_tto4[8]),
    .B1(sf_start_st_addr_tto4[3]),
    .B2(_0147_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__a221o_1 _0635_ (
    .A1(_0156_),
    .A2(sf_start_st_addr_tto4[19]),
    .B1(sf_start_st_addr_tto4[15]),
    .B2(_0141_),
    .C1(_0253_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _0636_ (
    .A1_N(_0150_),
    .A2_N(sf_start_st_addr_tto4[5]),
    .B1(sf_start_st_addr_tto4[8]),
    .B2(_0142_),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__o221ai_1 _0637_ (
    .A1(_0154_),
    .A2(sf_start_st_addr_tto4[18]),
    .B1(sf_start_st_addr_tto4[33]),
    .B2(_0151_),
    .C1(_0255_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__o22ai_1 _0638_ (
    .A1(ld_da_sf_addr_tto4[7]),
    .A2(_0162_),
    .B1(sf_start_st_addr_tto4[34]),
    .B2(_0149_),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__o22ai_1 _0639_ (
    .A1(ld_da_sf_addr_tto4[16]),
    .A2(_0161_),
    .B1(sf_start_st_addr_tto4[4]),
    .B2(_0136_),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0640_ (
    .A(_0257_),
    .SLEEP(_0258_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__nor4_1 _0641_ (
    .A(_0252_),
    .B(_0254_),
    .C(_0256_),
    .D(_0259_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__xor2_1 _0642_ (
    .A(ld_da_sf_addr_tto4[11]),
    .B(sf_start_st_addr_tto4[11]),
    .X(_0261_)
  );
  sky130_fd_sc_hd__nand2b_1 _0643_ (
    .A_N(sf_start_st_addr_tto4[0]),
    .B(ld_da_sf_addr_tto4[0]),
    .Y(_0262_)
  );
  sky130_fd_sc_hd__nand2b_1 _0644_ (
    .A_N(sf_start_st_addr_tto4[14]),
    .B(ld_da_sf_addr_tto4[14]),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0645_ (
    .A1(_0146_),
    .A2(sf_start_st_addr_tto4[22]),
    .B1(_0262_),
    .C1(_0263_),
    .D1(sf_start_vld),
    .Y(_0264_)
  );
  sky130_fd_sc_hd__o22ai_1 _0646_ (
    .A1(ld_da_sf_addr_tto4[28]),
    .A2(_0159_),
    .B1(sf_start_st_addr_tto4[15]),
    .B2(_0141_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__a221o_1 _0647_ (
    .A1(_0150_),
    .A2(sf_start_st_addr_tto4[5]),
    .B1(_0162_),
    .B2(ld_da_sf_addr_tto4[7]),
    .C1(_0265_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__xnor2_1 _0648_ (
    .A(ld_da_sf_addr_tto4[27]),
    .B(sf_start_st_addr_tto4[27]),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__o221ai_1 _0649_ (
    .A1(_0144_),
    .A2(sf_start_st_addr_tto4[29]),
    .B1(sf_start_st_addr_tto4[1]),
    .B2(_0135_),
    .C1(_0267_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nor4_1 _0650_ (
    .A(_0261_),
    .B(_0264_),
    .C(_0266_),
    .D(_0268_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0651_ (
    .A(sf_start_st_addr_tto4[14]),
    .SLEEP(ld_da_sf_addr_tto4[14]),
    .X(_0270_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0652_ (
    .A(sf_start_st_addr_tto4[20]),
    .SLEEP(ld_da_sf_addr_tto4[20]),
    .X(_0271_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0653_ (
    .A(ld_da_sf_addr_tto4[31]),
    .SLEEP(sf_start_st_addr_tto4[31]),
    .X(_0272_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0654_ (
    .A1(_0136_),
    .A2(sf_start_st_addr_tto4[4]),
    .B1(_0270_),
    .C1(_0271_),
    .D1(_0272_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__nand2b_1 _0655_ (
    .A_N(sf_start_st_addr_tto4[16]),
    .B(ld_da_sf_addr_tto4[16]),
    .Y(_0274_)
  );
  sky130_fd_sc_hd__nand2b_1 _0656_ (
    .A_N(ld_da_sf_addr_tto4[0]),
    .B(sf_start_st_addr_tto4[0]),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__nand2b_1 _0657_ (
    .A_N(sf_start_st_addr_tto4[17]),
    .B(ld_da_sf_addr_tto4[17]),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__o2111a_1 _0658_ (
    .A1(_0137_),
    .A2(sf_start_st_addr_tto4[24]),
    .B1(_0274_),
    .C1(_0275_),
    .D1(_0276_),
    .X(_0277_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0659_ (
    .A(sf_start_st_addr_tto4[9]),
    .SLEEP(ld_da_sf_addr_tto4[9]),
    .X(_0278_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0660_ (
    .A(sf_start_st_addr_tto4[17]),
    .SLEEP(ld_da_sf_addr_tto4[17]),
    .X(_0279_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0661_ (
    .A(ld_da_sf_addr_tto4[32]),
    .SLEEP(sf_start_st_addr_tto4[32]),
    .X(_0280_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0662_ (
    .A1(_0133_),
    .A2(sf_start_st_addr_tto4[6]),
    .B1(_0278_),
    .C1(_0279_),
    .D1(_0280_),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0663_ (
    .A(ld_da_sf_addr_tto4[35]),
    .SLEEP(sf_start_st_addr_tto4[35]),
    .X(_0282_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0664_ (
    .A(ld_da_sf_addr_tto4[23]),
    .SLEEP(sf_start_st_addr_tto4[23]),
    .X(_0283_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0665_ (
    .A(sf_start_st_addr_tto4[24]),
    .SLEEP(ld_da_sf_addr_tto4[24]),
    .X(_0284_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0666_ (
    .A1(_0151_),
    .A2(sf_start_st_addr_tto4[33]),
    .B1(_0282_),
    .C1(_0283_),
    .D1(_0284_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__nand4_1 _0667_ (
    .A(_0273_),
    .B(_0277_),
    .C(_0281_),
    .D(_0285_),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__nand2b_1 _0668_ (
    .A_N(ld_da_sf_addr_tto4[18]),
    .B(sf_start_st_addr_tto4[18]),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__nand2b_1 _0669_ (
    .A_N(sf_start_st_addr_tto4[28]),
    .B(ld_da_sf_addr_tto4[28]),
    .Y(_0288_)
  );
  sky130_fd_sc_hd__nand2b_1 _0670_ (
    .A_N(sf_start_st_addr_tto4[13]),
    .B(ld_da_sf_addr_tto4[13]),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__o2111a_1 _0671_ (
    .A1(_0153_),
    .A2(sf_start_st_addr_tto4[12]),
    .B1(_0287_),
    .C1(_0288_),
    .D1(_0289_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__nand2b_1 _0672_ (
    .A_N(ld_da_sf_addr_tto4[26]),
    .B(sf_start_st_addr_tto4[26]),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__nand2b_1 _0673_ (
    .A_N(ld_da_sf_addr_tto4[35]),
    .B(sf_start_st_addr_tto4[35]),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__nand2b_1 _0674_ (
    .A_N(ld_da_sf_addr_tto4[34]),
    .B(sf_start_st_addr_tto4[34]),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__o2111a_1 _0675_ (
    .A1(_0140_),
    .A2(sf_start_st_addr_tto4[30]),
    .B1(_0291_),
    .C1(_0292_),
    .D1(_0293_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0676_ (
    .A(sf_start_st_addr_tto4[10]),
    .SLEEP(ld_da_sf_addr_tto4[10]),
    .X(_0295_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0677_ (
    .A(sf_start_st_addr_tto4[29]),
    .SLEEP(ld_da_sf_addr_tto4[29]),
    .X(_0296_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0678_ (
    .A(sf_start_st_addr_tto4[25]),
    .SLEEP(ld_da_sf_addr_tto4[25]),
    .X(_0297_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0679_ (
    .A1(_0146_),
    .A2(sf_start_st_addr_tto4[22]),
    .B1(_0295_),
    .C1(_0296_),
    .D1(_0297_),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__nand2b_1 _0680_ (
    .A_N(sf_start_st_addr_tto4[21]),
    .B(ld_da_sf_addr_tto4[21]),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__nand2b_1 _0681_ (
    .A_N(ld_da_sf_addr_tto4[31]),
    .B(sf_start_st_addr_tto4[31]),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__nand2b_1 _0682_ (
    .A_N(sf_start_st_addr_tto4[26]),
    .B(ld_da_sf_addr_tto4[26]),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__o2111a_1 _0683_ (
    .A1(_0133_),
    .A2(sf_start_st_addr_tto4[6]),
    .B1(_0299_),
    .C1(_0300_),
    .D1(_0301_),
    .X(_0302_)
  );
  sky130_fd_sc_hd__nand4_1 _0684_ (
    .A(_0290_),
    .B(_0294_),
    .C(_0298_),
    .D(_0302_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__a22oi_1 _0685_ (
    .A1(ld_da_sf_bytes_vld[14]),
    .A2(sf_start_st_bytes_vld[14]),
    .B1(sf_start_st_bytes_vld[6]),
    .B2(ld_da_sf_bytes_vld[6]),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__a22oi_1 _0686_ (
    .A1(ld_da_sf_bytes_vld[5]),
    .A2(sf_start_st_bytes_vld[5]),
    .B1(sf_start_st_bytes_vld[1]),
    .B2(ld_da_sf_bytes_vld[1]),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__a22oi_1 _0687_ (
    .A1(ld_da_sf_bytes_vld[10]),
    .A2(sf_start_st_bytes_vld[10]),
    .B1(sf_start_st_bytes_vld[2]),
    .B2(ld_da_sf_bytes_vld[2]),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__a222oi_1 _0688_ (
    .A1(ld_da_sf_bytes_vld[8]),
    .A2(sf_start_st_bytes_vld[8]),
    .B1(sf_start_st_bytes_vld[9]),
    .B2(ld_da_sf_bytes_vld[9]),
    .C1(sf_start_st_bytes_vld[12]),
    .C2(ld_da_sf_bytes_vld[12]),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__a222oi_1 _0689_ (
    .A1(ld_da_sf_bytes_vld[11]),
    .A2(sf_start_st_bytes_vld[11]),
    .B1(sf_start_st_bytes_vld[13]),
    .B2(ld_da_sf_bytes_vld[13]),
    .C1(sf_start_st_bytes_vld[15]),
    .C2(ld_da_sf_bytes_vld[15]),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__nand3_1 _0690_ (
    .A(_0304_),
    .B(_0307_),
    .C(_0308_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__a222oi_1 _0691_ (
    .A1(ld_da_sf_bytes_vld[4]),
    .A2(sf_start_st_bytes_vld[4]),
    .B1(sf_start_st_bytes_vld[0]),
    .B2(ld_da_sf_bytes_vld[0]),
    .C1(ld_da_sf_bytes_vld[7]),
    .C2(sf_start_st_bytes_vld[7]),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__nand3_1 _0692_ (
    .A(_0305_),
    .B(_0306_),
    .C(_0310_),
    .Y(_0311_)
  );
  sky130_fd_sc_hd__a211oi_1 _0693_ (
    .A1(ld_da_sf_bytes_vld[3]),
    .A2(sf_start_st_bytes_vld[3]),
    .B1(_0309_),
    .C1(_0311_),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__a222oi_1 _0694_ (
    .A1(ld_da_sf_addr_tto4[25]),
    .A2(_0163_),
    .B1(sf_start_st_addr_tto4[12]),
    .B2(_0153_),
    .C1(ld_da_sf_addr_tto4[10]),
    .C2(_0160_),
    .Y(_0313_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0695_ (
    .A(ld_da_sf_addr_tto4[19]),
    .SLEEP(sf_start_st_addr_tto4[19]),
    .X(_0314_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0696_ (
    .A(ld_da_sf_addr_tto4[9]),
    .SLEEP(sf_start_st_addr_tto4[9]),
    .X(_0315_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0697_ (
    .A(sf_start_st_addr_tto4[13]),
    .SLEEP(ld_da_sf_addr_tto4[13]),
    .X(_0316_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0698_ (
    .A1(_0139_),
    .A2(sf_start_st_addr_tto4[23]),
    .B1(_0314_),
    .C1(_0315_),
    .D1(_0316_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0699_ (
    .A(sf_start_st_addr_tto4[32]),
    .SLEEP(ld_da_sf_addr_tto4[32]),
    .X(_0318_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0700_ (
    .A(ld_da_sf_addr_tto4[20]),
    .SLEEP(sf_start_st_addr_tto4[20]),
    .X(_0319_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0701_ (
    .A(sf_start_st_addr_tto4[2]),
    .SLEEP(ld_da_sf_addr_tto4[2]),
    .X(_0320_)
  );
  sky130_fd_sc_hd__a2111oi_0 _0702_ (
    .A1(_0135_),
    .A2(sf_start_st_addr_tto4[1]),
    .B1(_0318_),
    .C1(_0319_),
    .D1(_0320_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__nand3_1 _0703_ (
    .A(_0313_),
    .B(_0317_),
    .C(_0321_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__nor4_1 _0704_ (
    .A(_0286_),
    .B(_0303_),
    .C(_0312_),
    .D(_0322_),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__and3_1 _0705_ (
    .A(_0260_),
    .B(_0269_),
    .C(_0323_),
    .X(sf_spec_mark)
  );
  sky130_fd_sc_hd__nor3_1 _0706_ (
    .A(rtu_yy_xx_flush),
    .B(sf_start_vld),
    .C(st_da_sf_spec_chk_gate),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__nor3_1 _0707_ (
    .A(sf_start_pre),
    .B(sf_mispred_chk_vld),
    .C(st_da_sf_no_spec_miss_gate),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__nand2_1 _0708_ (
    .A(_0324_),
    .B(_0325_),
    .Y(sf_clk_en)
  );
  sky130_fd_sc_hd__o21a_1 _0709_ (
    .A1(sf_mispred_chk_iid_newer_than_st_da),
    .A2(_0131_),
    .B1(st_da_sf_spec_chk),
    .X(_0326_)
  );
  sky130_fd_sc_hd__o21ai_0 _0710_ (
    .A1(sf_mispred_chk_iid_newer_than_st_da),
    .A2(_0131_),
    .B1(st_da_sf_spec_chk),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__nand2_1 _0711_ (
    .A(st_da_sf_addr_tto4[19]),
    .B(_0326_),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__nand2_1 _0712_ (
    .A(sf_mispred_chk_st_addr_tto4[19]),
    .B(_0327_),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__nand2_1 _0713_ (
    .A(_0328_),
    .B(_0329_),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__nand2_1 _0714_ (
    .A(st_da_sf_addr_tto4[18]),
    .B(_0326_),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__nand2_1 _0715_ (
    .A(sf_mispred_chk_st_addr_tto4[18]),
    .B(_0327_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__nand2_1 _0716_ (
    .A(_0330_),
    .B(_0331_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__nand2_1 _0717_ (
    .A(st_da_sf_addr_tto4[17]),
    .B(_0326_),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__nand2_1 _0718_ (
    .A(sf_mispred_chk_st_addr_tto4[17]),
    .B(_0327_),
    .Y(_0333_)
  );
  sky130_fd_sc_hd__nand2_1 _0719_ (
    .A(_0332_),
    .B(_0333_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__nand2_1 _0720_ (
    .A(st_da_sf_addr_tto4[16]),
    .B(_0326_),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__nand2_1 _0721_ (
    .A(sf_mispred_chk_st_addr_tto4[16]),
    .B(_0327_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__nand2_1 _0722_ (
    .A(_0334_),
    .B(_0335_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__nand2_1 _0723_ (
    .A(st_da_sf_addr_tto4[15]),
    .B(_0326_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__nand2_1 _0724_ (
    .A(sf_mispred_chk_st_addr_tto4[15]),
    .B(_0327_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__nand2_1 _0725_ (
    .A(_0336_),
    .B(_0337_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__nand2_1 _0726_ (
    .A(st_da_sf_addr_tto4[14]),
    .B(_0326_),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__nand2_1 _0727_ (
    .A(sf_mispred_chk_st_addr_tto4[14]),
    .B(_0327_),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__nand2_1 _0728_ (
    .A(_0338_),
    .B(_0339_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__nand2_1 _0729_ (
    .A(st_da_sf_addr_tto4[13]),
    .B(_0326_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__nand2_1 _0730_ (
    .A(sf_mispred_chk_st_addr_tto4[13]),
    .B(_0327_),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__nand2_1 _0731_ (
    .A(_0340_),
    .B(_0341_),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__nand2_1 _0732_ (
    .A(st_da_sf_addr_tto4[12]),
    .B(_0326_),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__o21ai_0 _0733_ (
    .A1(_0152_),
    .A2(_0326_),
    .B1(_0342_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__nand2_1 _0734_ (
    .A(st_da_sf_addr_tto4[11]),
    .B(_0326_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__o21ai_0 _0735_ (
    .A1(_0155_),
    .A2(_0326_),
    .B1(_0343_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__nand2_1 _0736_ (
    .A(st_da_sf_addr_tto4[10]),
    .B(_0326_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__nand2_1 _0737_ (
    .A(sf_mispred_chk_st_addr_tto4[10]),
    .B(_0327_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__nand2_1 _0738_ (
    .A(_0344_),
    .B(_0345_),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__nand2_1 _0739_ (
    .A(st_da_sf_addr_tto4[9]),
    .B(_0326_),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__nand2_1 _0740_ (
    .A(sf_mispred_chk_st_addr_tto4[9]),
    .B(_0327_),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__nand2_1 _0741_ (
    .A(_0346_),
    .B(_0347_),
    .Y(_0010_)
  );
  sky130_fd_sc_hd__nand2_1 _0742_ (
    .A(st_da_sf_addr_tto4[8]),
    .B(_0326_),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__nand2_1 _0743_ (
    .A(sf_mispred_chk_st_addr_tto4[8]),
    .B(_0327_),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__nand2_1 _0744_ (
    .A(_0348_),
    .B(_0349_),
    .Y(_0011_)
  );
  sky130_fd_sc_hd__nand2_1 _0745_ (
    .A(st_da_sf_addr_tto4[7]),
    .B(_0326_),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__nand2_1 _0746_ (
    .A(sf_mispred_chk_st_addr_tto4[7]),
    .B(_0327_),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__nand2_1 _0747_ (
    .A(_0350_),
    .B(_0351_),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__nand2_1 _0748_ (
    .A(st_da_sf_addr_tto4[6]),
    .B(_0326_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__nand2_1 _0749_ (
    .A(sf_mispred_chk_st_addr_tto4[6]),
    .B(_0327_),
    .Y(_0353_)
  );
  sky130_fd_sc_hd__nand2_1 _0750_ (
    .A(_0352_),
    .B(_0353_),
    .Y(_0013_)
  );
  sky130_fd_sc_hd__nand2_1 _0751_ (
    .A(st_da_sf_addr_tto4[5]),
    .B(_0326_),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__nand2_1 _0752_ (
    .A(sf_mispred_chk_st_addr_tto4[5]),
    .B(_0327_),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__nand2_1 _0753_ (
    .A(_0354_),
    .B(_0355_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__nand2_1 _0754_ (
    .A(st_da_sf_addr_tto4[4]),
    .B(_0326_),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__nand2_1 _0755_ (
    .A(sf_mispred_chk_st_addr_tto4[4]),
    .B(_0327_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__nand2_1 _0756_ (
    .A(_0356_),
    .B(_0357_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__nand2_1 _0757_ (
    .A(st_da_sf_addr_tto4[3]),
    .B(_0326_),
    .Y(_0358_)
  );
  sky130_fd_sc_hd__nand2_1 _0758_ (
    .A(sf_mispred_chk_st_addr_tto4[3]),
    .B(_0327_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__nand2_1 _0759_ (
    .A(_0358_),
    .B(_0359_),
    .Y(_0016_)
  );
  sky130_fd_sc_hd__nand2_1 _0760_ (
    .A(st_da_sf_addr_tto4[2]),
    .B(_0326_),
    .Y(_0360_)
  );
  sky130_fd_sc_hd__nand2_1 _0761_ (
    .A(sf_mispred_chk_st_addr_tto4[2]),
    .B(_0327_),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__nand2_1 _0762_ (
    .A(_0360_),
    .B(_0361_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__nand2_1 _0763_ (
    .A(st_da_sf_addr_tto4[1]),
    .B(_0326_),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__o21ai_0 _0764_ (
    .A1(_0134_),
    .A2(_0326_),
    .B1(_0362_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__nand2_1 _0765_ (
    .A(st_da_sf_addr_tto4[0]),
    .B(_0326_),
    .Y(_0363_)
  );
  sky130_fd_sc_hd__nand2_1 _0766_ (
    .A(sf_mispred_chk_st_addr_tto4[0]),
    .B(_0327_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__nand2_1 _0767_ (
    .A(_0363_),
    .B(_0364_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__nand2b_1 _0768_ (
    .A_N(sf_start_iid_newer_than_st_da),
    .B(sf_start_pre),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__and3_1 _0769_ (
    .A(st_da_sf_no_spec_miss),
    .B(_0157_),
    .C(_0365_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__mux2_1 _0770_ (
    .A0(sf_start_st_iid[5]),
    .A1(st_da_sf_iid[5]),
    .S(_0366_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__mux2_1 _0771_ (
    .A0(sf_start_st_iid[4]),
    .A1(st_da_sf_iid[4]),
    .S(_0366_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__nand2_1 _0772_ (
    .A(st_da_sf_iid[3]),
    .B(_0366_),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__o21ai_0 _0773_ (
    .A1(_0130_),
    .A2(_0366_),
    .B1(_0367_),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__mux2_1 _0774_ (
    .A0(sf_start_st_iid[2]),
    .A1(st_da_sf_iid[2]),
    .S(_0366_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__mux2_1 _0775_ (
    .A0(sf_start_st_iid[1]),
    .A1(st_da_sf_iid[1]),
    .S(_0366_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__mux2_1 _0776_ (
    .A0(sf_start_st_iid[0]),
    .A1(st_da_sf_iid[0]),
    .S(_0366_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__and3_1 _0777_ (
    .A(sf_mispred_chk_vld),
    .B(sf_mispred_chk_clr_counter[0]),
    .C(ld_da_sf_spec_chk_req),
    .X(_0368_)
  );
  sky130_fd_sc_hd__and2_0 _0778_ (
    .A(sf_mispred_chk_clr_counter[1]),
    .B(_0368_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__and3_1 _0779_ (
    .A(sf_mispred_chk_clr_counter[1]),
    .B(sf_mispred_chk_clr_counter[2]),
    .C(_0368_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__o21ai_0 _0780_ (
    .A1(sf_mispred_chk_clr_counter[2]),
    .A2(_0369_),
    .B1(_0327_),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__nor2_1 _0781_ (
    .A(_0370_),
    .B(_0371_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__nor2_1 _0782_ (
    .A(sf_mispred_chk_clr_counter[1]),
    .B(_0368_),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__nor3_1 _0783_ (
    .A(_0326_),
    .B(_0369_),
    .C(_0372_),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__a21oi_1 _0784_ (
    .A1(sf_mispred_chk_vld),
    .A2(ld_da_sf_spec_chk_req),
    .B1(sf_mispred_chk_clr_counter[0]),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__nor3_1 _0785_ (
    .A(_0326_),
    .B(_0368_),
    .C(_0373_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__nand2_1 _0786_ (
    .A(st_da_sf_bytes_vld[14]),
    .B(_0326_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__nand2_1 _0787_ (
    .A(sf_mispred_chk_bytes_vld[14]),
    .B(_0327_),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__nand2_1 _0788_ (
    .A(_0374_),
    .B(_0375_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__nand2_1 _0789_ (
    .A(st_da_sf_bytes_vld[13]),
    .B(_0326_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__nand2_1 _0790_ (
    .A(sf_mispred_chk_bytes_vld[13]),
    .B(_0327_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__nand2_1 _0791_ (
    .A(_0376_),
    .B(_0377_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__nand2_1 _0792_ (
    .A(st_da_sf_bytes_vld[12]),
    .B(_0326_),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__nand2_1 _0793_ (
    .A(sf_mispred_chk_bytes_vld[12]),
    .B(_0327_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__nand2_1 _0794_ (
    .A(_0378_),
    .B(_0379_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__nand2_1 _0795_ (
    .A(st_da_sf_bytes_vld[11]),
    .B(_0326_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__nand2_1 _0796_ (
    .A(sf_mispred_chk_bytes_vld[11]),
    .B(_0327_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__nand2_1 _0797_ (
    .A(_0380_),
    .B(_0381_),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__nand2_1 _0798_ (
    .A(st_da_sf_bytes_vld[10]),
    .B(_0326_),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__nand2_1 _0799_ (
    .A(sf_mispred_chk_bytes_vld[10]),
    .B(_0327_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__nand2_1 _0800_ (
    .A(_0382_),
    .B(_0383_),
    .Y(_0033_)
  );
  sky130_fd_sc_hd__nand2_1 _0801_ (
    .A(st_da_sf_bytes_vld[9]),
    .B(_0326_),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__nand2_1 _0802_ (
    .A(sf_mispred_chk_bytes_vld[9]),
    .B(_0327_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__nand2_1 _0803_ (
    .A(_0384_),
    .B(_0385_),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__nand2_1 _0804_ (
    .A(st_da_sf_bytes_vld[8]),
    .B(_0326_),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__nand2_1 _0805_ (
    .A(sf_mispred_chk_bytes_vld[8]),
    .B(_0327_),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__nand2_1 _0806_ (
    .A(_0386_),
    .B(_0387_),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__nand2_1 _0807_ (
    .A(st_da_sf_bytes_vld[7]),
    .B(_0326_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__nand2_1 _0808_ (
    .A(sf_mispred_chk_bytes_vld[7]),
    .B(_0327_),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__nand2_1 _0809_ (
    .A(_0388_),
    .B(_0389_),
    .Y(_0036_)
  );
  sky130_fd_sc_hd__nand2_1 _0810_ (
    .A(st_da_sf_bytes_vld[6]),
    .B(_0326_),
    .Y(_0390_)
  );
  sky130_fd_sc_hd__nand2_1 _0811_ (
    .A(sf_mispred_chk_bytes_vld[6]),
    .B(_0327_),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__nand2_1 _0812_ (
    .A(_0390_),
    .B(_0391_),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__nand2_1 _0813_ (
    .A(st_da_sf_bytes_vld[5]),
    .B(_0326_),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__nand2_1 _0814_ (
    .A(sf_mispred_chk_bytes_vld[5]),
    .B(_0327_),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__nand2_1 _0815_ (
    .A(_0392_),
    .B(_0393_),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__nand2_1 _0816_ (
    .A(st_da_sf_bytes_vld[4]),
    .B(_0326_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__nand2_1 _0817_ (
    .A(sf_mispred_chk_bytes_vld[4]),
    .B(_0327_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__nand2_1 _0818_ (
    .A(_0394_),
    .B(_0395_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__nand2_1 _0819_ (
    .A(st_da_sf_bytes_vld[3]),
    .B(_0326_),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__nand2_1 _0820_ (
    .A(sf_mispred_chk_bytes_vld[3]),
    .B(_0327_),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__nand2_1 _0821_ (
    .A(_0396_),
    .B(_0397_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__nand2_1 _0822_ (
    .A(st_da_sf_bytes_vld[2]),
    .B(_0326_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__nand2_1 _0823_ (
    .A(sf_mispred_chk_bytes_vld[2]),
    .B(_0327_),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__nand2_1 _0824_ (
    .A(_0398_),
    .B(_0399_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__nand2_1 _0825_ (
    .A(st_da_sf_bytes_vld[1]),
    .B(_0326_),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__nand2_1 _0826_ (
    .A(sf_mispred_chk_bytes_vld[1]),
    .B(_0327_),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__nand2_1 _0827_ (
    .A(_0400_),
    .B(_0401_),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__nand2_1 _0828_ (
    .A(st_da_sf_bytes_vld[0]),
    .B(_0326_),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__nand2_1 _0829_ (
    .A(sf_mispred_chk_bytes_vld[0]),
    .B(_0327_),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__nand2_1 _0830_ (
    .A(_0402_),
    .B(_0403_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__mux2_1 _0831_ (
    .A0(sf_start_st_bytes_vld[14]),
    .A1(st_da_sf_bytes_vld[14]),
    .S(_0366_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__mux2_1 _0832_ (
    .A0(sf_start_st_bytes_vld[13]),
    .A1(st_da_sf_bytes_vld[13]),
    .S(_0366_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__mux2_1 _0833_ (
    .A0(sf_start_st_bytes_vld[12]),
    .A1(st_da_sf_bytes_vld[12]),
    .S(_0366_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__mux2_1 _0834_ (
    .A0(sf_start_st_bytes_vld[11]),
    .A1(st_da_sf_bytes_vld[11]),
    .S(_0366_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__mux2_1 _0835_ (
    .A0(sf_start_st_bytes_vld[10]),
    .A1(st_da_sf_bytes_vld[10]),
    .S(_0366_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__mux2_1 _0836_ (
    .A0(sf_start_st_bytes_vld[9]),
    .A1(st_da_sf_bytes_vld[9]),
    .S(_0366_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__mux2_1 _0837_ (
    .A0(sf_start_st_bytes_vld[8]),
    .A1(st_da_sf_bytes_vld[8]),
    .S(_0366_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__mux2_1 _0838_ (
    .A0(sf_start_st_bytes_vld[7]),
    .A1(st_da_sf_bytes_vld[7]),
    .S(_0366_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__mux2_1 _0839_ (
    .A0(sf_start_st_bytes_vld[6]),
    .A1(st_da_sf_bytes_vld[6]),
    .S(_0366_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__mux2_1 _0840_ (
    .A0(sf_start_st_bytes_vld[5]),
    .A1(st_da_sf_bytes_vld[5]),
    .S(_0366_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__mux2_1 _0841_ (
    .A0(sf_start_st_bytes_vld[4]),
    .A1(st_da_sf_bytes_vld[4]),
    .S(_0366_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__mux2_1 _0842_ (
    .A0(sf_start_st_bytes_vld[3]),
    .A1(st_da_sf_bytes_vld[3]),
    .S(_0366_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__mux2_1 _0843_ (
    .A0(sf_start_st_bytes_vld[2]),
    .A1(st_da_sf_bytes_vld[2]),
    .S(_0366_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__mux2_1 _0844_ (
    .A0(sf_start_st_bytes_vld[1]),
    .A1(st_da_sf_bytes_vld[1]),
    .S(_0366_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__mux2_1 _0845_ (
    .A0(sf_start_st_bytes_vld[0]),
    .A1(st_da_sf_bytes_vld[0]),
    .S(_0366_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__mux2_1 _0846_ (
    .A0(sf_start_st_addr_tto4[34]),
    .A1(st_da_sf_addr_tto4[34]),
    .S(_0366_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__mux2_1 _0847_ (
    .A0(sf_start_st_addr_tto4[33]),
    .A1(st_da_sf_addr_tto4[33]),
    .S(_0366_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__mux2_1 _0848_ (
    .A0(sf_start_st_addr_tto4[32]),
    .A1(st_da_sf_addr_tto4[32]),
    .S(_0366_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__mux2_1 _0849_ (
    .A0(sf_start_st_addr_tto4[31]),
    .A1(st_da_sf_addr_tto4[31]),
    .S(_0366_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__mux2_1 _0850_ (
    .A0(sf_start_st_addr_tto4[30]),
    .A1(st_da_sf_addr_tto4[30]),
    .S(_0366_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__mux2_1 _0851_ (
    .A0(sf_start_st_addr_tto4[29]),
    .A1(st_da_sf_addr_tto4[29]),
    .S(_0366_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__mux2_1 _0852_ (
    .A0(sf_start_st_addr_tto4[28]),
    .A1(st_da_sf_addr_tto4[28]),
    .S(_0366_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__mux2_1 _0853_ (
    .A0(sf_start_st_addr_tto4[27]),
    .A1(st_da_sf_addr_tto4[27]),
    .S(_0366_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__mux2_1 _0854_ (
    .A0(sf_start_st_addr_tto4[26]),
    .A1(st_da_sf_addr_tto4[26]),
    .S(_0366_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__nand2_1 _0855_ (
    .A(st_da_sf_addr_tto4[25]),
    .B(_0366_),
    .Y(_0404_)
  );
  sky130_fd_sc_hd__o21ai_0 _0856_ (
    .A1(_0163_),
    .A2(_0366_),
    .B1(_0404_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__mux2_1 _0857_ (
    .A0(sf_start_st_addr_tto4[24]),
    .A1(st_da_sf_addr_tto4[24]),
    .S(_0366_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__mux2_1 _0858_ (
    .A0(sf_start_st_addr_tto4[23]),
    .A1(st_da_sf_addr_tto4[23]),
    .S(_0366_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__mux2_1 _0859_ (
    .A0(sf_start_st_addr_tto4[22]),
    .A1(st_da_sf_addr_tto4[22]),
    .S(_0366_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__o21ai_0 _0860_ (
    .A1(sf_mispred_chk_clr_counter[3]),
    .A2(_0370_),
    .B1(_0327_),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__a21oi_1 _0861_ (
    .A1(sf_mispred_chk_clr_counter[3]),
    .A2(_0370_),
    .B1(_0405_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__mux2_1 _0862_ (
    .A0(sf_start_st_bytes_vld[15]),
    .A1(st_da_sf_bytes_vld[15]),
    .S(_0366_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__mux2_1 _0863_ (
    .A0(sf_start_st_addr_tto4[21]),
    .A1(st_da_sf_addr_tto4[21]),
    .S(_0366_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__mux2_1 _0864_ (
    .A0(sf_start_st_addr_tto4[20]),
    .A1(st_da_sf_addr_tto4[20]),
    .S(_0366_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__mux2_1 _0865_ (
    .A0(sf_start_st_addr_tto4[19]),
    .A1(st_da_sf_addr_tto4[19]),
    .S(_0366_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__nor2_1 _0866_ (
    .A(sf_start_clr_counter[0]),
    .B(sf_start_clr_counter[1]),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__a311oi_1 _0867_ (
    .A1(sf_start_clr_counter[2]),
    .A2(sf_start_clr_counter[3]),
    .A3(_0406_),
    .B1(_0157_),
    .C1(rtu_yy_xx_flush),
    .Y(_0407_)
  );
  sky130_fd_sc_hd__nand4_1 _0868_ (
    .A(ld_da_sf_spec_chk_req),
    .B(_0260_),
    .C(_0269_),
    .D(_0323_),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0869_ (
    .A(sf_start_st_iid[6]),
    .SLEEP(rtu_lsu_spec_fail_iid[6]),
    .X(_0409_)
  );
  sky130_fd_sc_hd__nand3_1 _0870_ (
    .A(rtu_yy_xx_flush),
    .B(sf_start_pre),
    .C(rtu_lsu_spec_fail_flush),
    .Y(_0410_)
  );
  sky130_fd_sc_hd__xor2_1 _0871_ (
    .A(sf_start_st_iid[5]),
    .B(rtu_lsu_spec_fail_iid[5]),
    .X(_0411_)
  );
  sky130_fd_sc_hd__xor2_1 _0872_ (
    .A(sf_start_st_iid[1]),
    .B(rtu_lsu_spec_fail_iid[1]),
    .X(_0412_)
  );
  sky130_fd_sc_hd__xor2_1 _0873_ (
    .A(rtu_lsu_spec_fail_iid[4]),
    .B(sf_start_st_iid[4]),
    .X(_0413_)
  );
  sky130_fd_sc_hd__xor2_1 _0874_ (
    .A(sf_start_st_iid[2]),
    .B(rtu_lsu_spec_fail_iid[2]),
    .X(_0414_)
  );
  sky130_fd_sc_hd__or4_1 _0875_ (
    .A(_0410_),
    .B(_0412_),
    .C(_0413_),
    .D(_0414_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__xor2_1 _0876_ (
    .A(sf_start_st_iid[0]),
    .B(rtu_lsu_spec_fail_iid[0]),
    .X(_0416_)
  );
  sky130_fd_sc_hd__o22ai_1 _0877_ (
    .A1(sf_start_st_iid[6]),
    .A2(_0129_),
    .B1(_0130_),
    .B2(rtu_lsu_spec_fail_iid[3]),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__a211o_1 _0878_ (
    .A1(_0130_),
    .A2(rtu_lsu_spec_fail_iid[3]),
    .B1(_0409_),
    .C1(_0417_),
    .X(_0418_)
  );
  sky130_fd_sc_hd__nor4_1 _0879_ (
    .A(_0411_),
    .B(_0415_),
    .C(_0416_),
    .D(_0418_),
    .Y(_0419_)
  );
  sky130_fd_sc_hd__a21o_1 _0880_ (
    .A1(_0407_),
    .A2(_0408_),
    .B1(_0419_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__mux2_1 _0881_ (
    .A0(sf_start_st_addr_tto4[18]),
    .A1(st_da_sf_addr_tto4[18]),
    .S(_0366_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__nand2_1 _0882_ (
    .A(st_da_sf_bytes_vld[15]),
    .B(_0326_),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__nand2_1 _0883_ (
    .A(sf_mispred_chk_bytes_vld[15]),
    .B(_0327_),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__nand2_1 _0884_ (
    .A(_0420_),
    .B(_0421_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__mux2_1 _0885_ (
    .A0(sf_start_st_addr_tto4[17]),
    .A1(st_da_sf_addr_tto4[17]),
    .S(_0366_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__mux2_1 _0886_ (
    .A0(sf_start_st_addr_tto4[16]),
    .A1(st_da_sf_addr_tto4[16]),
    .S(_0366_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__mux2_1 _0887_ (
    .A0(sf_start_st_addr_tto4[15]),
    .A1(st_da_sf_addr_tto4[15]),
    .S(_0366_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__mux2_1 _0888_ (
    .A0(sf_start_st_addr_tto4[14]),
    .A1(st_da_sf_addr_tto4[14]),
    .S(_0366_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__mux2_1 _0889_ (
    .A0(sf_start_st_addr_tto4[13]),
    .A1(st_da_sf_addr_tto4[13]),
    .S(_0366_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__mux2_1 _0890_ (
    .A0(sf_start_st_addr_tto4[12]),
    .A1(st_da_sf_addr_tto4[12]),
    .S(_0366_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__mux2_1 _0891_ (
    .A0(sf_start_st_addr_tto4[11]),
    .A1(st_da_sf_addr_tto4[11]),
    .S(_0366_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__nand2_1 _0892_ (
    .A(st_da_sf_addr_tto4[10]),
    .B(_0366_),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__o21ai_0 _0893_ (
    .A1(_0160_),
    .A2(_0366_),
    .B1(_0422_),
    .Y(_0087_)
  );
  sky130_fd_sc_hd__mux2_1 _0894_ (
    .A0(sf_start_st_addr_tto4[9]),
    .A1(st_da_sf_addr_tto4[9]),
    .S(_0366_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__mux2_1 _0895_ (
    .A0(sf_start_st_addr_tto4[8]),
    .A1(st_da_sf_addr_tto4[8]),
    .S(_0366_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__mux2_1 _0896_ (
    .A0(sf_start_st_addr_tto4[7]),
    .A1(st_da_sf_addr_tto4[7]),
    .S(_0366_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__mux2_1 _0897_ (
    .A0(sf_start_st_addr_tto4[6]),
    .A1(st_da_sf_addr_tto4[6]),
    .S(_0366_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__mux2_1 _0898_ (
    .A0(sf_start_st_addr_tto4[5]),
    .A1(st_da_sf_addr_tto4[5]),
    .S(_0366_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__mux2_1 _0899_ (
    .A0(sf_start_st_addr_tto4[4]),
    .A1(st_da_sf_addr_tto4[4]),
    .S(_0366_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__mux2_1 _0900_ (
    .A0(sf_start_st_addr_tto4[3]),
    .A1(st_da_sf_addr_tto4[3]),
    .S(_0366_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__nand2_1 _0901_ (
    .A(st_da_sf_addr_tto4[2]),
    .B(_0366_),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__o21ai_0 _0902_ (
    .A1(_0158_),
    .A2(_0366_),
    .B1(_0423_),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__mux2_1 _0903_ (
    .A0(sf_start_st_addr_tto4[1]),
    .A1(st_da_sf_addr_tto4[1]),
    .S(_0366_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__mux2_1 _0904_ (
    .A0(sf_start_st_addr_tto4[0]),
    .A1(st_da_sf_addr_tto4[0]),
    .S(_0366_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__nand2_1 _0905_ (
    .A(st_da_sf_iid[5]),
    .B(_0326_),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__nand2_1 _0906_ (
    .A(sf_mispred_chk_st_iid[5]),
    .B(_0327_),
    .Y(_0425_)
  );
  sky130_fd_sc_hd__nand2_1 _0907_ (
    .A(_0424_),
    .B(_0425_),
    .Y(_0098_)
  );
  sky130_fd_sc_hd__nand2_1 _0908_ (
    .A(st_da_sf_iid[4]),
    .B(_0326_),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__nand2_1 _0909_ (
    .A(sf_mispred_chk_st_iid[4]),
    .B(_0327_),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__nand2_1 _0910_ (
    .A(_0426_),
    .B(_0427_),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__nand2_1 _0911_ (
    .A(st_da_sf_iid[3]),
    .B(_0326_),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__nand2_1 _0912_ (
    .A(sf_mispred_chk_st_iid[3]),
    .B(_0327_),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__nand2_1 _0913_ (
    .A(_0428_),
    .B(_0429_),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__nand2_1 _0914_ (
    .A(st_da_sf_iid[2]),
    .B(_0326_),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__nand2_1 _0915_ (
    .A(sf_mispred_chk_st_iid[2]),
    .B(_0327_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__nand2_1 _0916_ (
    .A(_0430_),
    .B(_0431_),
    .Y(_0101_)
  );
  sky130_fd_sc_hd__nand2_1 _0917_ (
    .A(st_da_sf_iid[1]),
    .B(_0326_),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__nand2_1 _0918_ (
    .A(sf_mispred_chk_st_iid[1]),
    .B(_0327_),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__nand2_1 _0919_ (
    .A(_0432_),
    .B(_0433_),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__nand2_1 _0920_ (
    .A(st_da_sf_iid[0]),
    .B(_0326_),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__nand2_1 _0921_ (
    .A(sf_mispred_chk_st_iid[0]),
    .B(_0327_),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__nand2_1 _0922_ (
    .A(_0434_),
    .B(_0435_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__and3_1 _0923_ (
    .A(sf_start_clr_counter[0]),
    .B(ld_da_sf_spec_chk_req),
    .C(sf_start_vld),
    .X(_0436_)
  );
  sky130_fd_sc_hd__and2_0 _0924_ (
    .A(sf_start_clr_counter[1]),
    .B(_0436_),
    .X(_0437_)
  );
  sky130_fd_sc_hd__and3_1 _0925_ (
    .A(sf_start_clr_counter[1]),
    .B(sf_start_clr_counter[2]),
    .C(_0436_),
    .X(_0438_)
  );
  sky130_fd_sc_hd__nor2_1 _0926_ (
    .A(sf_start_clr_counter[2]),
    .B(_0437_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__nor3_1 _0927_ (
    .A(_0419_),
    .B(_0438_),
    .C(_0439_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__nor2_1 _0928_ (
    .A(sf_start_clr_counter[1]),
    .B(_0436_),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__nor3_1 _0929_ (
    .A(_0419_),
    .B(_0437_),
    .C(_0440_),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__a21oi_1 _0930_ (
    .A1(ld_da_sf_spec_chk_req),
    .A2(sf_start_vld),
    .B1(sf_start_clr_counter[0]),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__nor3_1 _0931_ (
    .A(_0419_),
    .B(_0436_),
    .C(_0441_),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__nand2_1 _0932_ (
    .A(st_da_sf_addr_tto4[34]),
    .B(_0326_),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__nand2_1 _0933_ (
    .A(sf_mispred_chk_st_addr_tto4[34]),
    .B(_0327_),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__nand2_1 _0934_ (
    .A(_0442_),
    .B(_0443_),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__nand2_1 _0935_ (
    .A(st_da_sf_addr_tto4[33]),
    .B(_0326_),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__nand2_1 _0936_ (
    .A(sf_mispred_chk_st_addr_tto4[33]),
    .B(_0327_),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__nand2_1 _0937_ (
    .A(_0444_),
    .B(_0445_),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__nand2_1 _0938_ (
    .A(st_da_sf_addr_tto4[32]),
    .B(_0326_),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__o21ai_0 _0939_ (
    .A1(_0143_),
    .A2(_0326_),
    .B1(_0446_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__nand2_1 _0940_ (
    .A(st_da_sf_addr_tto4[31]),
    .B(_0326_),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__nand2_1 _0941_ (
    .A(sf_mispred_chk_st_addr_tto4[31]),
    .B(_0327_),
    .Y(_0448_)
  );
  sky130_fd_sc_hd__nand2_1 _0942_ (
    .A(_0447_),
    .B(_0448_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__mux2_1 _0943_ (
    .A0(sf_start_st_iid[6]),
    .A1(st_da_sf_iid[6]),
    .S(_0366_),
    .X(_0111_)
  );
  sky130_fd_sc_hd__nand2_1 _0944_ (
    .A(st_da_sf_addr_tto4[30]),
    .B(_0326_),
    .Y(_0449_)
  );
  sky130_fd_sc_hd__nand2_1 _0945_ (
    .A(sf_mispred_chk_st_addr_tto4[30]),
    .B(_0327_),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__nand2_1 _0946_ (
    .A(_0449_),
    .B(_0450_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__nand2_1 _0947_ (
    .A(st_da_sf_addr_tto4[29]),
    .B(_0326_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__o21ai_0 _0948_ (
    .A1(_0145_),
    .A2(_0326_),
    .B1(_0451_),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__nand2_1 _0949_ (
    .A(st_da_sf_addr_tto4[35]),
    .B(_0326_),
    .Y(_0452_)
  );
  sky130_fd_sc_hd__nand2_1 _0950_ (
    .A(sf_mispred_chk_st_addr_tto4[35]),
    .B(_0327_),
    .Y(_0453_)
  );
  sky130_fd_sc_hd__nand2_1 _0951_ (
    .A(_0452_),
    .B(_0453_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__nand2_1 _0952_ (
    .A(st_da_sf_addr_tto4[28]),
    .B(_0326_),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__nand2_1 _0953_ (
    .A(sf_mispred_chk_st_addr_tto4[28]),
    .B(_0327_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__nand2_1 _0954_ (
    .A(_0454_),
    .B(_0455_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__nor2_1 _0955_ (
    .A(sf_start_clr_counter[3]),
    .B(_0438_),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__a211oi_1 _0956_ (
    .A1(sf_start_clr_counter[3]),
    .A2(_0438_),
    .B1(_0456_),
    .C1(_0419_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__a21oi_1 _0957_ (
    .A1(st_da_sf_no_spec_miss),
    .A2(_0157_),
    .B1(sf_start_pre),
    .Y(_0457_)
  );
  sky130_fd_sc_hd__nor2_1 _0958_ (
    .A(rtu_yy_xx_flush),
    .B(_0457_),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__nand2_1 _0959_ (
    .A(st_da_sf_addr_tto4[27]),
    .B(_0326_),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__nand2_1 _0960_ (
    .A(sf_mispred_chk_st_addr_tto4[27]),
    .B(_0327_),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__nand2_1 _0961_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__nand2_1 _0962_ (
    .A(st_da_sf_addr_tto4[26]),
    .B(_0326_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__o21ai_0 _0963_ (
    .A1(_0132_),
    .A2(_0326_),
    .B1(_0460_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__nand2_1 _0964_ (
    .A(st_da_sf_iid[6]),
    .B(_0326_),
    .Y(_0461_)
  );
  sky130_fd_sc_hd__nand2_1 _0965_ (
    .A(sf_mispred_chk_st_iid[6]),
    .B(_0327_),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__nand2_1 _0966_ (
    .A(_0461_),
    .B(_0462_),
    .Y(_0120_)
  );
  sky130_fd_sc_hd__nand2_1 _0967_ (
    .A(st_da_sf_addr_tto4[25]),
    .B(_0326_),
    .Y(_0463_)
  );
  sky130_fd_sc_hd__nand2_1 _0968_ (
    .A(sf_mispred_chk_st_addr_tto4[25]),
    .B(_0327_),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__nand2_1 _0969_ (
    .A(_0463_),
    .B(_0464_),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__nand2_1 _0970_ (
    .A(sf_mispred_chk_clr_counter[2]),
    .B(sf_mispred_chk_clr_counter[3]),
    .Y(_0465_)
  );
  sky130_fd_sc_hd__nor3_1 _0971_ (
    .A(sf_mispred_chk_clr_counter[0]),
    .B(sf_mispred_chk_clr_counter[1]),
    .C(_0465_),
    .Y(_0466_)
  );
  sky130_fd_sc_hd__nor4_1 _0972_ (
    .A(_0165_),
    .B(_0166_),
    .C(_0167_),
    .D(_0180_),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__nor4_1 _0973_ (
    .A(_0164_),
    .B(_0172_),
    .C(_0179_),
    .D(_0240_),
    .Y(_0468_)
  );
  sky130_fd_sc_hd__nor2_1 _0974_ (
    .A(_0238_),
    .B(_0243_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__nor4_1 _0975_ (
    .A(_0185_),
    .B(_0241_),
    .C(_0242_),
    .D(_0248_),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__nand4_1 _0976_ (
    .A(_0467_),
    .B(_0468_),
    .C(_0469_),
    .D(_0470_),
    .Y(_0471_)
  );
  sky130_fd_sc_hd__nor2_1 _0977_ (
    .A(_0236_),
    .B(_0237_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__a21oi_1 _0978_ (
    .A1(sf_mispred_chk_st_addr_tto4[22]),
    .A2(_0146_),
    .B1(_0245_),
    .Y(_0473_)
  );
  sky130_fd_sc_hd__nand4b_1 _0979_ (
    .A_N(_0215_),
    .B(_0472_),
    .C(_0473_),
    .D(_0184_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__nor3_1 _0980_ (
    .A(_0191_),
    .B(_0246_),
    .C(_0247_),
    .Y(_0475_)
  );
  sky130_fd_sc_hd__nand3b_1 _0981_ (
    .A_N(_0213_),
    .B(_0216_),
    .C(_0475_),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__nor4_1 _0982_ (
    .A(_0235_),
    .B(_0471_),
    .C(_0474_),
    .D(_0476_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__o21ai_0 _0983_ (
    .A1(ld_da_sf_addr_tto4[32]),
    .A2(_0143_),
    .B1(_0208_),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__nand2_1 _0984_ (
    .A(sf_mispred_chk_vld),
    .B(_0201_),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__or4_1 _0985_ (
    .A(_0169_),
    .B(_0188_),
    .C(_0478_),
    .D(_0479_),
    .X(_0480_)
  );
  sky130_fd_sc_hd__xor2_1 _0986_ (
    .A(sf_mispred_chk_st_addr_tto4[11]),
    .B(ld_da_sf_addr_tto4[11]),
    .X(_0481_)
  );
  sky130_fd_sc_hd__xor2_1 _0987_ (
    .A(ld_da_sf_addr_tto4[24]),
    .B(sf_mispred_chk_st_addr_tto4[24]),
    .X(_0482_)
  );
  sky130_fd_sc_hd__nor2_1 _0988_ (
    .A(_0481_),
    .B(_0482_),
    .Y(_0483_)
  );
  sky130_fd_sc_hd__xnor2_1 _0989_ (
    .A(sf_mispred_chk_st_addr_tto4[3]),
    .B(ld_da_sf_addr_tto4[3]),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0990_ (
    .A1(sf_mispred_chk_st_addr_tto4[8]),
    .A2(_0142_),
    .B1(_0202_),
    .C1(_0483_),
    .D1(_0484_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__nor3_1 _0991_ (
    .A(_0211_),
    .B(_0480_),
    .C(_0485_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__nand2b_1 _0992_ (
    .A_N(_0181_),
    .B(_0196_),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__o21ai_0 _0993_ (
    .A1(ld_da_sf_addr_tto4[29]),
    .A2(_0145_),
    .B1(_0174_),
    .Y(_0488_)
  );
  sky130_fd_sc_hd__o2111ai_1 _0994_ (
    .A1(_0141_),
    .A2(sf_mispred_chk_st_addr_tto4[15]),
    .B1(_0175_),
    .C1(_0176_),
    .D1(_0177_),
    .Y(_0489_)
  );
  sky130_fd_sc_hd__a211oi_1 _0995_ (
    .A1(ld_da_sf_addr_tto4[29]),
    .A2(_0145_),
    .B1(_0488_),
    .C1(_0489_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__o221ai_1 _0996_ (
    .A1(_0140_),
    .A2(sf_mispred_chk_st_addr_tto4[30]),
    .B1(_0152_),
    .B2(ld_da_sf_addr_tto4[12]),
    .C1(_0183_),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _0997_ (
    .A1_N(_0140_),
    .A2_N(sf_mispred_chk_st_addr_tto4[30]),
    .B1(_0133_),
    .B2(sf_mispred_chk_st_addr_tto4[6]),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__o21ai_0 _0998_ (
    .A1(_0132_),
    .A2(ld_da_sf_addr_tto4[26]),
    .B1(_0206_),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__nor3_1 _0999_ (
    .A(_0491_),
    .B(_0492_),
    .C(_0493_),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__nand4_1 _1000_ (
    .A(_0205_),
    .B(_0207_),
    .C(_0220_),
    .D(_0222_),
    .Y(_0495_)
  );
  sky130_fd_sc_hd__o21ai_0 _1001_ (
    .A1(sf_mispred_chk_st_addr_tto4[1]),
    .A2(_0135_),
    .B1(_0223_),
    .Y(_0496_)
  );
  sky130_fd_sc_hd__nor4b_1 _1002_ (
    .A(_0218_),
    .B(_0495_),
    .C(_0496_),
    .D_N(_0221_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__and4b_1 _1003_ (
    .A_N(_0487_),
    .B(_0490_),
    .C(_0494_),
    .D(_0497_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__and4_1 _1004_ (
    .A(ld_da_sf_spec_chk_req),
    .B(_0477_),
    .C(_0486_),
    .D(_0498_),
    .X(_0499_)
  );
  sky130_fd_sc_hd__o41ai_1 _1005_ (
    .A1(rtu_yy_xx_flush),
    .A2(_0131_),
    .A3(_0466_),
    .A4(_0499_),
    .B1(_0327_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__mux2_1 _1006_ (
    .A0(sf_start_st_addr_tto4[35]),
    .A1(st_da_sf_addr_tto4[35]),
    .S(_0366_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__nand2_1 _1007_ (
    .A(st_da_sf_addr_tto4[24]),
    .B(_0326_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__o21ai_0 _1008_ (
    .A1(_0138_),
    .A2(_0326_),
    .B1(_0500_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__nand2_1 _1009_ (
    .A(st_da_sf_addr_tto4[23]),
    .B(_0326_),
    .Y(_0501_)
  );
  sky130_fd_sc_hd__nand2_1 _1010_ (
    .A(sf_mispred_chk_st_addr_tto4[23]),
    .B(_0327_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__nand2_1 _1011_ (
    .A(_0501_),
    .B(_0502_),
    .Y(_0125_)
  );
  sky130_fd_sc_hd__nand2_1 _1012_ (
    .A(st_da_sf_addr_tto4[22]),
    .B(_0326_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__nand2_1 _1013_ (
    .A(sf_mispred_chk_st_addr_tto4[22]),
    .B(_0327_),
    .Y(_0504_)
  );
  sky130_fd_sc_hd__nand2_1 _1014_ (
    .A(_0503_),
    .B(_0504_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__nand2_1 _1015_ (
    .A(st_da_sf_addr_tto4[21]),
    .B(_0326_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__nand2_1 _1016_ (
    .A(sf_mispred_chk_st_addr_tto4[21]),
    .B(_0327_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__nand2_1 _1017_ (
    .A(_0505_),
    .B(_0506_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__nand2_1 _1018_ (
    .A(st_da_sf_addr_tto4[20]),
    .B(_0326_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__nand2_1 _1019_ (
    .A(sf_mispred_chk_st_addr_tto4[20]),
    .B(_0327_),
    .Y(_0508_)
  );
  sky130_fd_sc_hd__nand2_1 _1020_ (
    .A(_0507_),
    .B(_0508_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__dfrtp_1 _1021_ (
    .CLK(sf_start_dp_clk),
    .D(_0058_),
    .Q(sf_start_st_bytes_vld[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1022_ (
    .CLK(sf_start_dp_clk),
    .D(_0057_),
    .Q(sf_start_st_bytes_vld[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1023_ (
    .CLK(sf_start_dp_clk),
    .D(_0056_),
    .Q(sf_start_st_bytes_vld[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1024_ (
    .CLK(sf_start_dp_clk),
    .D(_0055_),
    .Q(sf_start_st_bytes_vld[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1025_ (
    .CLK(sf_start_dp_clk),
    .D(_0054_),
    .Q(sf_start_st_bytes_vld[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1026_ (
    .CLK(sf_start_dp_clk),
    .D(_0053_),
    .Q(sf_start_st_bytes_vld[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1027_ (
    .CLK(sf_start_dp_clk),
    .D(_0052_),
    .Q(sf_start_st_bytes_vld[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1028_ (
    .CLK(sf_start_dp_clk),
    .D(_0051_),
    .Q(sf_start_st_bytes_vld[7]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1029_ (
    .CLK(sf_start_dp_clk),
    .D(_0050_),
    .Q(sf_start_st_bytes_vld[8]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1030_ (
    .CLK(sf_start_dp_clk),
    .D(_0049_),
    .Q(sf_start_st_bytes_vld[9]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1031_ (
    .CLK(sf_start_dp_clk),
    .D(_0048_),
    .Q(sf_start_st_bytes_vld[10]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1032_ (
    .CLK(sf_start_dp_clk),
    .D(_0047_),
    .Q(sf_start_st_bytes_vld[11]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1033_ (
    .CLK(sf_start_dp_clk),
    .D(_0046_),
    .Q(sf_start_st_bytes_vld[12]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1034_ (
    .CLK(sf_start_dp_clk),
    .D(_0045_),
    .Q(sf_start_st_bytes_vld[13]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1035_ (
    .CLK(sf_start_dp_clk),
    .D(_0044_),
    .Q(sf_start_st_bytes_vld[14]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1036_ (
    .CLK(sf_start_dp_clk),
    .D(_0073_),
    .Q(sf_start_st_bytes_vld[15]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1037_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0043_),
    .Q(sf_mispred_chk_bytes_vld[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1038_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0042_),
    .Q(sf_mispred_chk_bytes_vld[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1039_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0041_),
    .Q(sf_mispred_chk_bytes_vld[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1040_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0040_),
    .Q(sf_mispred_chk_bytes_vld[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1041_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0039_),
    .Q(sf_mispred_chk_bytes_vld[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1042_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0038_),
    .Q(sf_mispred_chk_bytes_vld[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1043_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0037_),
    .Q(sf_mispred_chk_bytes_vld[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1044_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0036_),
    .Q(sf_mispred_chk_bytes_vld[7]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1045_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0035_),
    .Q(sf_mispred_chk_bytes_vld[8]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1046_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0034_),
    .Q(sf_mispred_chk_bytes_vld[9]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1047_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0033_),
    .Q(sf_mispred_chk_bytes_vld[10]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1048_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0032_),
    .Q(sf_mispred_chk_bytes_vld[11]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1049_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0031_),
    .Q(sf_mispred_chk_bytes_vld[12]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1050_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0030_),
    .Q(sf_mispred_chk_bytes_vld[13]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1051_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0029_),
    .Q(sf_mispred_chk_bytes_vld[14]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1052_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0079_),
    .Q(sf_mispred_chk_bytes_vld[15]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1053_ (
    .CLK(sf_clk),
    .D(_0077_),
    .Q(sf_start_vld),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1054_ (
    .CLK(sf_clk),
    .D(_0028_),
    .Q(sf_mispred_chk_clr_counter[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1055_ (
    .CLK(sf_clk),
    .D(_0027_),
    .Q(sf_mispred_chk_clr_counter[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1056_ (
    .CLK(sf_clk),
    .D(_0026_),
    .Q(sf_mispred_chk_clr_counter[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1057_ (
    .CLK(sf_clk),
    .D(_0072_),
    .Q(sf_mispred_chk_clr_counter[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1058_ (
    .CLK(sf_start_dp_clk),
    .D(_0025_),
    .Q(sf_start_st_iid[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1059_ (
    .CLK(sf_start_dp_clk),
    .D(_0024_),
    .Q(sf_start_st_iid[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1060_ (
    .CLK(sf_start_dp_clk),
    .D(_0023_),
    .Q(sf_start_st_iid[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1061_ (
    .CLK(sf_start_dp_clk),
    .D(_0022_),
    .Q(sf_start_st_iid[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1062_ (
    .CLK(sf_start_dp_clk),
    .D(_0021_),
    .Q(sf_start_st_iid[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1063_ (
    .CLK(sf_start_dp_clk),
    .D(_0020_),
    .Q(sf_start_st_iid[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1064_ (
    .CLK(sf_start_dp_clk),
    .D(_0111_),
    .Q(sf_start_st_iid[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1065_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0019_),
    .Q(sf_mispred_chk_st_addr_tto4[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1066_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0018_),
    .Q(sf_mispred_chk_st_addr_tto4[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1067_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0017_),
    .Q(sf_mispred_chk_st_addr_tto4[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1068_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0016_),
    .Q(sf_mispred_chk_st_addr_tto4[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1069_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0015_),
    .Q(sf_mispred_chk_st_addr_tto4[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1070_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0014_),
    .Q(sf_mispred_chk_st_addr_tto4[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1071_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0013_),
    .Q(sf_mispred_chk_st_addr_tto4[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1072_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0012_),
    .Q(sf_mispred_chk_st_addr_tto4[7]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1073_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0011_),
    .Q(sf_mispred_chk_st_addr_tto4[8]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1074_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0010_),
    .Q(sf_mispred_chk_st_addr_tto4[9]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1075_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0009_),
    .Q(sf_mispred_chk_st_addr_tto4[10]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1076_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0008_),
    .Q(sf_mispred_chk_st_addr_tto4[11]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1077_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0007_),
    .Q(sf_mispred_chk_st_addr_tto4[12]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1078_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0006_),
    .Q(sf_mispred_chk_st_addr_tto4[13]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1079_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0005_),
    .Q(sf_mispred_chk_st_addr_tto4[14]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1080_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0004_),
    .Q(sf_mispred_chk_st_addr_tto4[15]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1081_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0003_),
    .Q(sf_mispred_chk_st_addr_tto4[16]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1082_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0002_),
    .Q(sf_mispred_chk_st_addr_tto4[17]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1083_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0001_),
    .Q(sf_mispred_chk_st_addr_tto4[18]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1084_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0000_),
    .Q(sf_mispred_chk_st_addr_tto4[19]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1085_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0128_),
    .Q(sf_mispred_chk_st_addr_tto4[20]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1086_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0127_),
    .Q(sf_mispred_chk_st_addr_tto4[21]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1087_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0126_),
    .Q(sf_mispred_chk_st_addr_tto4[22]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1088_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0125_),
    .Q(sf_mispred_chk_st_addr_tto4[23]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1089_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0124_),
    .Q(sf_mispred_chk_st_addr_tto4[24]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1090_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0121_),
    .Q(sf_mispred_chk_st_addr_tto4[25]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1091_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0119_),
    .Q(sf_mispred_chk_st_addr_tto4[26]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1092_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0118_),
    .Q(sf_mispred_chk_st_addr_tto4[27]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1093_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0115_),
    .Q(sf_mispred_chk_st_addr_tto4[28]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1094_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0113_),
    .Q(sf_mispred_chk_st_addr_tto4[29]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1095_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0112_),
    .Q(sf_mispred_chk_st_addr_tto4[30]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1096_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0110_),
    .Q(sf_mispred_chk_st_addr_tto4[31]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1097_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0109_),
    .Q(sf_mispred_chk_st_addr_tto4[32]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1098_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0108_),
    .Q(sf_mispred_chk_st_addr_tto4[33]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1099_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0107_),
    .Q(sf_mispred_chk_st_addr_tto4[34]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1100_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0114_),
    .Q(sf_mispred_chk_st_addr_tto4[35]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1101_ (
    .CLK(sf_clk),
    .D(_0106_),
    .Q(sf_start_clr_counter[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1102_ (
    .CLK(sf_clk),
    .D(_0105_),
    .Q(sf_start_clr_counter[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1103_ (
    .CLK(sf_clk),
    .D(_0104_),
    .Q(sf_start_clr_counter[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1104_ (
    .CLK(sf_clk),
    .D(_0116_),
    .Q(sf_start_clr_counter[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1105_ (
    .CLK(sf_clk),
    .D(_0117_),
    .Q(sf_start_pre),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1106_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0103_),
    .Q(sf_mispred_chk_st_iid[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1107_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0102_),
    .Q(sf_mispred_chk_st_iid[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1108_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0101_),
    .Q(sf_mispred_chk_st_iid[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1109_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0100_),
    .Q(sf_mispred_chk_st_iid[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1110_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0099_),
    .Q(sf_mispred_chk_st_iid[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1111_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0098_),
    .Q(sf_mispred_chk_st_iid[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1112_ (
    .CLK(sf_pred_chk_dp_clk),
    .D(_0120_),
    .Q(sf_mispred_chk_st_iid[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1113_ (
    .CLK(sf_clk),
    .D(_0122_),
    .Q(sf_mispred_chk_vld),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1114_ (
    .CLK(sf_start_dp_clk),
    .D(_0097_),
    .Q(sf_start_st_addr_tto4[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1115_ (
    .CLK(sf_start_dp_clk),
    .D(_0096_),
    .Q(sf_start_st_addr_tto4[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1116_ (
    .CLK(sf_start_dp_clk),
    .D(_0095_),
    .Q(sf_start_st_addr_tto4[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1117_ (
    .CLK(sf_start_dp_clk),
    .D(_0094_),
    .Q(sf_start_st_addr_tto4[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1118_ (
    .CLK(sf_start_dp_clk),
    .D(_0093_),
    .Q(sf_start_st_addr_tto4[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1119_ (
    .CLK(sf_start_dp_clk),
    .D(_0092_),
    .Q(sf_start_st_addr_tto4[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1120_ (
    .CLK(sf_start_dp_clk),
    .D(_0091_),
    .Q(sf_start_st_addr_tto4[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1121_ (
    .CLK(sf_start_dp_clk),
    .D(_0090_),
    .Q(sf_start_st_addr_tto4[7]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1122_ (
    .CLK(sf_start_dp_clk),
    .D(_0089_),
    .Q(sf_start_st_addr_tto4[8]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1123_ (
    .CLK(sf_start_dp_clk),
    .D(_0088_),
    .Q(sf_start_st_addr_tto4[9]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1124_ (
    .CLK(sf_start_dp_clk),
    .D(_0087_),
    .Q(sf_start_st_addr_tto4[10]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1125_ (
    .CLK(sf_start_dp_clk),
    .D(_0086_),
    .Q(sf_start_st_addr_tto4[11]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1126_ (
    .CLK(sf_start_dp_clk),
    .D(_0085_),
    .Q(sf_start_st_addr_tto4[12]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1127_ (
    .CLK(sf_start_dp_clk),
    .D(_0084_),
    .Q(sf_start_st_addr_tto4[13]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1128_ (
    .CLK(sf_start_dp_clk),
    .D(_0083_),
    .Q(sf_start_st_addr_tto4[14]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1129_ (
    .CLK(sf_start_dp_clk),
    .D(_0082_),
    .Q(sf_start_st_addr_tto4[15]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1130_ (
    .CLK(sf_start_dp_clk),
    .D(_0081_),
    .Q(sf_start_st_addr_tto4[16]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1131_ (
    .CLK(sf_start_dp_clk),
    .D(_0080_),
    .Q(sf_start_st_addr_tto4[17]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1132_ (
    .CLK(sf_start_dp_clk),
    .D(_0078_),
    .Q(sf_start_st_addr_tto4[18]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1133_ (
    .CLK(sf_start_dp_clk),
    .D(_0076_),
    .Q(sf_start_st_addr_tto4[19]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1134_ (
    .CLK(sf_start_dp_clk),
    .D(_0075_),
    .Q(sf_start_st_addr_tto4[20]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1135_ (
    .CLK(sf_start_dp_clk),
    .D(_0074_),
    .Q(sf_start_st_addr_tto4[21]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1136_ (
    .CLK(sf_start_dp_clk),
    .D(_0071_),
    .Q(sf_start_st_addr_tto4[22]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1137_ (
    .CLK(sf_start_dp_clk),
    .D(_0070_),
    .Q(sf_start_st_addr_tto4[23]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1138_ (
    .CLK(sf_start_dp_clk),
    .D(_0069_),
    .Q(sf_start_st_addr_tto4[24]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1139_ (
    .CLK(sf_start_dp_clk),
    .D(_0068_),
    .Q(sf_start_st_addr_tto4[25]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1140_ (
    .CLK(sf_start_dp_clk),
    .D(_0067_),
    .Q(sf_start_st_addr_tto4[26]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1141_ (
    .CLK(sf_start_dp_clk),
    .D(_0066_),
    .Q(sf_start_st_addr_tto4[27]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1142_ (
    .CLK(sf_start_dp_clk),
    .D(_0065_),
    .Q(sf_start_st_addr_tto4[28]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1143_ (
    .CLK(sf_start_dp_clk),
    .D(_0064_),
    .Q(sf_start_st_addr_tto4[29]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1144_ (
    .CLK(sf_start_dp_clk),
    .D(_0063_),
    .Q(sf_start_st_addr_tto4[30]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1145_ (
    .CLK(sf_start_dp_clk),
    .D(_0062_),
    .Q(sf_start_st_addr_tto4[31]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1146_ (
    .CLK(sf_start_dp_clk),
    .D(_0061_),
    .Q(sf_start_st_addr_tto4[32]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1147_ (
    .CLK(sf_start_dp_clk),
    .D(_0060_),
    .Q(sf_start_st_addr_tto4[33]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1148_ (
    .CLK(sf_start_dp_clk),
    .D(_0059_),
    .Q(sf_start_st_addr_tto4[34]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _1149_ (
    .CLK(sf_start_dp_clk),
    .D(_0123_),
    .Q(sf_start_st_addr_tto4[35]),
    .RESET_B(cpurst_b)
  );
  gated_clk_cell x_lsu_sf_gated_clk (
    .clk_in(forever_cpuclk),
    .clk_out(sf_clk),
    .external_en(1'h0),
    .global_en(1'h1),
    .local_en(sf_clk_en),
    .module_en(cp0_lsu_icg_en),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en)
  );
  ct_rtu_compare_iid x_lsu_sf_mispred_chk_compare_iid (
    .x_iid0(st_da_sf_iid),
    .x_iid0_older(sf_mispred_chk_iid_newer_than_st_da),
    .x_iid1(sf_mispred_chk_st_iid)
  );
  gated_clk_cell x_lsu_sf_pred_chk_dp_gated_clk (
    .clk_in(forever_cpuclk),
    .clk_out(sf_pred_chk_dp_clk),
    .external_en(1'h0),
    .global_en(1'h1),
    .local_en(st_da_sf_spec_chk_gate),
    .module_en(cp0_lsu_icg_en),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en)
  );
  ct_rtu_compare_iid x_lsu_sf_start_compare_iid (
    .x_iid0(st_da_sf_iid),
    .x_iid0_older(sf_start_iid_newer_than_st_da),
    .x_iid1(sf_start_st_iid)
  );
  gated_clk_cell x_lsu_sf_start_dp_gated_clk (
    .clk_in(forever_cpuclk),
    .clk_out(sf_start_dp_clk),
    .external_en(1'h0),
    .global_en(1'h1),
    .local_en(st_da_sf_no_spec_miss_gate),
    .module_en(cp0_lsu_icg_en),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en)
  );
  assign sf_start_dp_clk_en = st_da_sf_no_spec_miss_gate;
  assign sf_pred_chk_dp_clk_en = st_da_sf_spec_chk_gate;
  assign ld_hit_sf_start = sf_spec_mark;
  assign ld_hit_sf_mispred_chk = sf_spec_hit;
endmodule

module ct_rtu_compare_iid(x_iid0, x_iid0_older, x_iid1);
  input [6:0] x_iid0;
  wire [6:0] x_iid0;
  output x_iid0_older;
  wire x_iid0_older;
  input [6:0] x_iid1;
  wire [6:0] x_iid1;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(x_iid0[5]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(x_iid0[4]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(x_iid0[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _21_ (
    .A(x_iid1[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _22_ (
    .A1_N(_02_),
    .A2_N(x_iid1[3]),
    .B1(_03_),
    .B2(x_iid0[2]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2b_1 _23_ (
    .A_N(x_iid0[1]),
    .B(x_iid1[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _24_ (
    .A(x_iid0[1]),
    .SLEEP(x_iid1[1]),
    .X(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _25_ (
    .A(x_iid0[0]),
    .SLEEP(x_iid1[0]),
    .X(_07_)
  );
  sky130_fd_sc_hd__o221ai_1 _26_ (
    .A1(_03_),
    .A2(x_iid0[2]),
    .B1(_06_),
    .B2(_07_),
    .C1(_05_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a222oi_1 _27_ (
    .A1(x_iid1[4]),
    .A2(_01_),
    .B1(_02_),
    .B2(x_iid1[3]),
    .C1(_04_),
    .C2(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o22ai_1 _28_ (
    .A1(_00_),
    .A2(x_iid1[5]),
    .B1(x_iid1[4]),
    .B2(_01_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _29_ (
    .A1_N(_00_),
    .A2_N(x_iid1[5]),
    .B1(_09_),
    .B2(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__xor2_1 _30_ (
    .A(x_iid0[6]),
    .B(x_iid1[6]),
    .X(_12_)
  );
  sky130_fd_sc_hd__nand2b_1 _31_ (
    .A_N(x_iid0[0]),
    .B(x_iid1[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o221ai_1 _32_ (
    .A1(_03_),
    .A2(x_iid0[2]),
    .B1(_06_),
    .B2(_13_),
    .C1(_05_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a222oi_1 _33_ (
    .A1(x_iid1[4]),
    .A2(_01_),
    .B1(_02_),
    .B2(x_iid1[3]),
    .C1(_04_),
    .C2(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _34_ (
    .A1(_00_),
    .A2(x_iid1[5]),
    .B1(_12_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__o21ai_0 _35_ (
    .A1(_10_),
    .A2(_15_),
    .B1(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a21boi_0 _36_ (
    .A1(_11_),
    .A2(_12_),
    .B1_N(_17_),
    .Y(x_iid0_older)
  );
endmodule

module gated_clk_cell(clk_in, global_en, module_en, local_en, external_en, pad_yy_icg_scan_en, clk_out);
  input clk_in;
  wire clk_in;
  input global_en;
  wire global_en;
  input module_en;
  wire module_en;
  input local_en;
  wire local_en;
  input external_en;
  wire external_en;
  input pad_yy_icg_scan_en;
  wire pad_yy_icg_scan_en;
  output clk_out;
  wire clk_out;
  wire SE;
  assign SE = pad_yy_icg_scan_en;
  assign clk_out = clk_in;
endmodule
