/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_rtu_compare_iid(x_iid0, x_iid0_older, x_iid1);
  input [6:0] x_iid0;
  wire [6:0] x_iid0;
  output x_iid0_older;
  wire x_iid0_older;
  input [6:0] x_iid1;
  wire [6:0] x_iid1;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(x_iid1[3]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(x_iid0[2]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(x_iid1[5]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2b_1 _25_ (
    .A_N(x_iid0[3]),
    .B(x_iid1[3]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor2_1 _26_ (
    .A(x_iid1[2]),
    .B(_01_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _27_ (
    .A(x_iid1[1]),
    .SLEEP(x_iid0[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nand2b_1 _28_ (
    .A_N(x_iid1[1]),
    .B(x_iid0[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _29_ (
    .A(x_iid1[0]),
    .SLEEP(x_iid0[0]),
    .X(_07_)
  );
  sky130_fd_sc_hd__a221oi_1 _30_ (
    .A1(x_iid1[2]),
    .A2(_01_),
    .B1(_06_),
    .B2(_07_),
    .C1(_05_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__o21ai_0 _31_ (
    .A1(_04_),
    .A2(_08_),
    .B1(_03_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _32_ (
    .A(x_iid0[4]),
    .SLEEP(x_iid1[4]),
    .X(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _33_ (
    .A1(x_iid0[3]),
    .A2(_00_),
    .B1(_10_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2b_1 _34_ (
    .A_N(x_iid0[4]),
    .B(x_iid1[4]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o21ai_0 _35_ (
    .A1(x_iid0[5]),
    .A2(_02_),
    .B1(_12_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a21oi_1 _36_ (
    .A1(_09_),
    .A2(_11_),
    .B1(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xor2_1 _37_ (
    .A(x_iid0[6]),
    .B(x_iid1[6]),
    .X(_15_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _38_ (
    .A(x_iid0[5]),
    .SLEEP(x_iid1[5]),
    .X(_16_)
  );
  sky130_fd_sc_hd__nand2b_1 _39_ (
    .A_N(x_iid1[0]),
    .B(x_iid0[0]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a221oi_1 _40_ (
    .A1(x_iid1[2]),
    .A2(_01_),
    .B1(_06_),
    .B2(_17_),
    .C1(_05_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a211o_1 _41_ (
    .A1(x_iid0[3]),
    .A2(_00_),
    .B1(_04_),
    .C1(_18_),
    .X(_19_)
  );
  sky130_fd_sc_hd__a311oi_1 _42_ (
    .A1(_03_),
    .A2(_12_),
    .A3(_19_),
    .B1(_16_),
    .C1(_10_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _43_ (
    .A1(x_iid0[5]),
    .A2(_02_),
    .B1(_15_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o32ai_1 _44_ (
    .A1(_14_),
    .A2(_15_),
    .A3(_16_),
    .B1(_20_),
    .B2(_21_),
    .Y(x_iid0_older)
  );
endmodule
