/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_fadd_onehot_sel_h(data_in, onehot, result);
  input [11:0] data_in;
  wire [11:0] data_in;
  input [11:0] onehot;
  wire [11:0] onehot;
  output [11:0] result;
  wire [11:0] result;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire [11:0] result_h;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _073_ (
    .A(onehot[0]),
    .SLEEP(onehot[1]),
    .X(_016_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _074_ (
    .A(onehot[6]),
    .SLEEP(onehot[7]),
    .X(_017_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _075_ (
    .A(onehot[4]),
    .SLEEP(onehot[5]),
    .X(_018_)
  );
  sky130_fd_sc_hd__or4_1 _076_ (
    .A(onehot[6]),
    .B(onehot[7]),
    .C(onehot[4]),
    .D(onehot[5]),
    .X(_019_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _077_ (
    .A(onehot[10]),
    .SLEEP(onehot[11]),
    .X(_020_)
  );
  sky130_fd_sc_hd__or4_1 _078_ (
    .A(onehot[8]),
    .B(onehot[9]),
    .C(onehot[10]),
    .D(onehot[11]),
    .X(_021_)
  );
  sky130_fd_sc_hd__nand2b_1 _079_ (
    .A_N(onehot[3]),
    .B(onehot[2]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor4_1 _080_ (
    .A(_016_),
    .B(_019_),
    .C(_021_),
    .D(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _081_ (
    .A(onehot[2]),
    .SLEEP(onehot[3]),
    .X(_024_)
  );
  sky130_fd_sc_hd__or4_1 _082_ (
    .A(onehot[2]),
    .B(onehot[3]),
    .C(onehot[0]),
    .D(onehot[1]),
    .X(_025_)
  );
  sky130_fd_sc_hd__a2111oi_0 _083_ (
    .A1(onehot[8]),
    .A2(onehot[9]),
    .B1(_019_),
    .C1(_020_),
    .D1(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2b_1 _084_ (
    .A_N(onehot[7]),
    .B(onehot[6]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor4_1 _085_ (
    .A(_018_),
    .B(_021_),
    .C(_025_),
    .D(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2b_1 _086_ (
    .A_N(onehot[5]),
    .B(onehot[4]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor4_1 _087_ (
    .A(_017_),
    .B(_021_),
    .C(_025_),
    .D(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__or4b_1 _088_ (
    .A(onehot[8]),
    .B(onehot[9]),
    .C(onehot[11]),
    .D_N(onehot[10]),
    .X(_031_)
  );
  sky130_fd_sc_hd__nor3_1 _089_ (
    .A(_019_),
    .B(_025_),
    .C(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _090_ (
    .A_N(onehot[6]),
    .B(onehot[7]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor4_1 _091_ (
    .A(_018_),
    .B(_021_),
    .C(_025_),
    .D(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2b_1 _092_ (
    .A_N(onehot[2]),
    .B(onehot[3]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor4_1 _093_ (
    .A(_016_),
    .B(_019_),
    .C(_021_),
    .D(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2b_1 _094_ (
    .A_N(onehot[4]),
    .B(onehot[5]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor4_1 _095_ (
    .A(_017_),
    .B(_021_),
    .C(_025_),
    .D(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2b_1 _096_ (
    .A_N(onehot[1]),
    .B(onehot[0]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor4_1 _097_ (
    .A(_019_),
    .B(_021_),
    .C(_024_),
    .D(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2b_1 _098_ (
    .A_N(onehot[0]),
    .B(onehot[1]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor4_1 _099_ (
    .A(_019_),
    .B(_021_),
    .C(_024_),
    .D(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__or4_1 _100_ (
    .A(_023_),
    .B(_026_),
    .C(_036_),
    .D(_038_),
    .X(_043_)
  );
  sky130_fd_sc_hd__or4_1 _101_ (
    .A(_030_),
    .B(_032_),
    .C(_040_),
    .D(_042_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor4_1 _102_ (
    .A(_028_),
    .B(_034_),
    .C(_043_),
    .D(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2b_1 _103_ (
    .A_N(onehot[9]),
    .B(onehot[8]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor4_1 _104_ (
    .A(_019_),
    .B(_020_),
    .C(_025_),
    .D(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a22oi_1 _105_ (
    .A1(data_in[5]),
    .A2(_032_),
    .B1(_047_),
    .B2(data_in[3]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2b_1 _106_ (
    .A_N(onehot[8]),
    .B(onehot[9]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor4_1 _107_ (
    .A(_019_),
    .B(_020_),
    .C(_025_),
    .D(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a222oi_1 _108_ (
    .A1(data_in[1]),
    .A2(_028_),
    .B1(_034_),
    .B2(data_in[2]),
    .C1(data_in[0]),
    .C2(_038_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(_048_),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__a221o_1 _110_ (
    .A1(data_in[6]),
    .A2(_045_),
    .B1(_050_),
    .B2(data_in[4]),
    .C1(_052_),
    .X(result[6])
  );
  sky130_fd_sc_hd__a22oi_1 _111_ (
    .A1(data_in[4]),
    .A2(_032_),
    .B1(_047_),
    .B2(data_in[2]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a222oi_1 _112_ (
    .A1(data_in[0]),
    .A2(_028_),
    .B1(_034_),
    .B2(data_in[1]),
    .C1(_050_),
    .C2(data_in[3]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _113_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a21o_1 _114_ (
    .A1(data_in[5]),
    .A2(_045_),
    .B1(_055_),
    .X(result[5])
  );
  sky130_fd_sc_hd__a222oi_1 _115_ (
    .A1(data_in[0]),
    .A2(_034_),
    .B1(_050_),
    .B2(data_in[2]),
    .C1(data_in[3]),
    .C2(_032_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _116_ (
    .A(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a221o_1 _117_ (
    .A1(data_in[4]),
    .A2(_045_),
    .B1(_047_),
    .B2(data_in[1]),
    .C1(_057_),
    .X(result[4])
  );
  sky130_fd_sc_hd__a222oi_1 _118_ (
    .A1(data_in[2]),
    .A2(_032_),
    .B1(_050_),
    .B2(data_in[1]),
    .C1(_047_),
    .C2(data_in[0]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21bo_1 _119_ (
    .A1(data_in[3]),
    .A2(_045_),
    .B1_N(_058_),
    .X(result[3])
  );
  sky130_fd_sc_hd__a22oi_1 _120_ (
    .A1(data_in[5]),
    .A2(_034_),
    .B1(_036_),
    .B2(data_in[1]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a22oi_1 _121_ (
    .A1(data_in[8]),
    .A2(_032_),
    .B1(_038_),
    .B2(data_in[3]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _122_ (
    .A(_059_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a22oi_1 _123_ (
    .A1(data_in[2]),
    .A2(_030_),
    .B1(_047_),
    .B2(data_in[6]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a222oi_1 _124_ (
    .A1(data_in[0]),
    .A2(_023_),
    .B1(_028_),
    .B2(data_in[4]),
    .C1(_050_),
    .C2(data_in[7]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _125_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a211o_1 _126_ (
    .A1(data_in[9]),
    .A2(_045_),
    .B1(_061_),
    .C1(_064_),
    .X(result[9])
  );
  sky130_fd_sc_hd__a22o_1 _127_ (
    .A1(data_in[1]),
    .A2(_032_),
    .B1(_050_),
    .B2(data_in[0]),
    .X(_065_)
  );
  sky130_fd_sc_hd__a21o_1 _128_ (
    .A1(data_in[2]),
    .A2(_045_),
    .B1(_065_),
    .X(result[2])
  );
  sky130_fd_sc_hd__nand2_1 _129_ (
    .A(data_in[2]),
    .B(_036_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a22oi_1 _130_ (
    .A1(data_in[9]),
    .A2(_032_),
    .B1(_050_),
    .B2(data_in[8]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a22oi_1 _131_ (
    .A1(data_in[6]),
    .A2(_034_),
    .B1(_047_),
    .B2(data_in[7]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a222oi_1 _132_ (
    .A1(data_in[3]),
    .A2(_030_),
    .B1(_038_),
    .B2(data_in[4]),
    .C1(_042_),
    .C2(data_in[0]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _133_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a22oi_1 _134_ (
    .A1(data_in[1]),
    .A2(_023_),
    .B1(_028_),
    .B2(data_in[5]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand3_1 _135_ (
    .A(_066_),
    .B(_067_),
    .C(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a211o_1 _136_ (
    .A1(data_in[10]),
    .A2(_045_),
    .B1(_070_),
    .C1(_072_),
    .X(result[10])
  );
  sky130_fd_sc_hd__a22o_1 _137_ (
    .A1(data_in[0]),
    .A2(_032_),
    .B1(_045_),
    .B2(data_in[1]),
    .X(result[1])
  );
  sky130_fd_sc_hd__a222oi_1 _138_ (
    .A1(data_in[2]),
    .A2(_028_),
    .B1(_038_),
    .B2(data_in[1]),
    .C1(_050_),
    .C2(data_in[5]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a22oi_1 _139_ (
    .A1(data_in[6]),
    .A2(_032_),
    .B1(_034_),
    .B2(data_in[3]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a22oi_1 _140_ (
    .A1(data_in[0]),
    .A2(_030_),
    .B1(_047_),
    .B2(data_in[4]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand3_1 _141_ (
    .A(_000_),
    .B(_001_),
    .C(_002_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a21o_1 _142_ (
    .A1(data_in[7]),
    .A2(_045_),
    .B1(_003_),
    .X(result[7])
  );
  sky130_fd_sc_hd__and2_0 _143_ (
    .A(data_in[0]),
    .B(_045_),
    .X(result[0])
  );
  sky130_fd_sc_hd__a222oi_1 _144_ (
    .A1(data_in[3]),
    .A2(_028_),
    .B1(_032_),
    .B2(data_in[7]),
    .C1(_034_),
    .C2(data_in[4]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a22oi_1 _145_ (
    .A1(data_in[2]),
    .A2(_038_),
    .B1(_047_),
    .B2(data_in[5]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a22oi_1 _146_ (
    .A1(data_in[1]),
    .A2(_030_),
    .B1(_050_),
    .B2(data_in[6]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand3_1 _147_ (
    .A(_004_),
    .B(_005_),
    .C(_006_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a221o_1 _148_ (
    .A1(data_in[0]),
    .A2(_036_),
    .B1(_045_),
    .B2(data_in[8]),
    .C1(_007_),
    .X(result[8])
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(data_in[3]),
    .B(_036_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a22oi_1 _150_ (
    .A1(data_in[6]),
    .A2(_028_),
    .B1(_047_),
    .B2(data_in[8]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(_008_),
    .B(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a22oi_1 _152_ (
    .A1(data_in[7]),
    .A2(_034_),
    .B1(_042_),
    .B2(data_in[1]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__a22oi_1 _153_ (
    .A1(data_in[2]),
    .A2(_023_),
    .B1(_030_),
    .B2(data_in[4]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a22oi_1 _154_ (
    .A1(data_in[10]),
    .A2(_032_),
    .B1(_050_),
    .B2(data_in[9]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a22oi_1 _155_ (
    .A1(data_in[5]),
    .A2(_038_),
    .B1(_040_),
    .B2(data_in[0]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand4_1 _156_ (
    .A(_011_),
    .B(_012_),
    .C(_013_),
    .D(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a211o_1 _157_ (
    .A1(data_in[11]),
    .A2(_045_),
    .B1(_010_),
    .C1(_015_),
    .X(result[11])
  );
  assign result_h = result;
endmodule
