/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_fadd_onehot_sel_h(data_in, onehot, result);
  input [11:0] data_in;
  wire [11:0] data_in;
  input [11:0] onehot;
  wire [11:0] onehot;
  output [11:0] result;
  wire [11:0] result;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  sky130_fd_sc_hd__and2_0 _34_ (
    .A(onehot[11]),
    .B(data_in[0]),
    .X(result[0])
  );
  sky130_fd_sc_hd__a22o_1 _35_ (
    .A1(onehot[11]),
    .A2(data_in[1]),
    .B1(onehot[10]),
    .B2(data_in[0]),
    .X(result[1])
  );
  sky130_fd_sc_hd__a222oi_1 _36_ (
    .A1(onehot[11]),
    .A2(data_in[2]),
    .B1(onehot[9]),
    .B2(data_in[0]),
    .C1(data_in[1]),
    .C2(onehot[10]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _37_ (
    .A(_00_),
    .Y(result[2])
  );
  sky130_fd_sc_hd__nand2_1 _38_ (
    .A(onehot[11]),
    .B(data_in[3]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__a222oi_1 _39_ (
    .A1(onehot[10]),
    .A2(data_in[2]),
    .B1(onehot[9]),
    .B2(data_in[1]),
    .C1(data_in[0]),
    .C2(onehot[8]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _40_ (
    .A(_01_),
    .B(_02_),
    .Y(result[3])
  );
  sky130_fd_sc_hd__a22oi_1 _41_ (
    .A1(data_in[2]),
    .A2(onehot[9]),
    .B1(onehot[7]),
    .B2(data_in[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a222oi_1 _42_ (
    .A1(data_in[1]),
    .A2(onehot[8]),
    .B1(data_in[3]),
    .B2(onehot[10]),
    .C1(data_in[4]),
    .C2(onehot[11]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _43_ (
    .A(_03_),
    .B(_04_),
    .Y(result[4])
  );
  sky130_fd_sc_hd__a222oi_1 _44_ (
    .A1(data_in[2]),
    .A2(onehot[8]),
    .B1(data_in[3]),
    .B2(onehot[9]),
    .C1(data_in[4]),
    .C2(onehot[10]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a222oi_1 _45_ (
    .A1(onehot[11]),
    .A2(data_in[5]),
    .B1(onehot[6]),
    .B2(data_in[0]),
    .C1(data_in[1]),
    .C2(onehot[7]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(_05_),
    .B(_06_),
    .Y(result[5])
  );
  sky130_fd_sc_hd__nand2_1 _47_ (
    .A(data_in[2]),
    .B(onehot[7]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a222oi_1 _48_ (
    .A1(onehot[8]),
    .A2(data_in[3]),
    .B1(onehot[5]),
    .B2(data_in[0]),
    .C1(onehot[11]),
    .C2(data_in[6]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a222oi_1 _49_ (
    .A1(onehot[9]),
    .A2(data_in[4]),
    .B1(data_in[5]),
    .B2(onehot[10]),
    .C1(data_in[1]),
    .C2(onehot[6]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nand3_1 _50_ (
    .A(_07_),
    .B(_08_),
    .C(_09_),
    .Y(result[6])
  );
  sky130_fd_sc_hd__a22oi_1 _51_ (
    .A1(onehot[8]),
    .A2(data_in[4]),
    .B1(data_in[5]),
    .B2(onehot[9]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a222oi_1 _52_ (
    .A1(data_in[2]),
    .A2(onehot[6]),
    .B1(onehot[5]),
    .B2(data_in[1]),
    .C1(onehot[11]),
    .C2(data_in[7]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a222oi_1 _53_ (
    .A1(data_in[3]),
    .A2(onehot[7]),
    .B1(data_in[6]),
    .B2(onehot[10]),
    .C1(data_in[0]),
    .C2(onehot[4]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nand3_1 _54_ (
    .A(_10_),
    .B(_11_),
    .C(_12_),
    .Y(result[7])
  );
  sky130_fd_sc_hd__a222oi_1 _55_ (
    .A1(onehot[7]),
    .A2(data_in[4]),
    .B1(data_in[5]),
    .B2(onehot[8]),
    .C1(onehot[10]),
    .C2(data_in[7]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__a222oi_1 _56_ (
    .A1(data_in[2]),
    .A2(onehot[5]),
    .B1(data_in[6]),
    .B2(onehot[9]),
    .C1(onehot[4]),
    .C2(data_in[1]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__a222oi_1 _57_ (
    .A1(onehot[11]),
    .A2(data_in[8]),
    .B1(onehot[3]),
    .B2(data_in[0]),
    .C1(data_in[3]),
    .C2(onehot[6]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand3_1 _58_ (
    .A(_13_),
    .B(_14_),
    .C(_15_),
    .Y(result[8])
  );
  sky130_fd_sc_hd__nand2_1 _59_ (
    .A(onehot[9]),
    .B(data_in[7]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand2_1 _60_ (
    .A(onehot[8]),
    .B(data_in[6]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a222oi_1 _61_ (
    .A1(onehot[7]),
    .A2(data_in[5]),
    .B1(data_in[8]),
    .B2(onehot[10]),
    .C1(onehot[11]),
    .C2(data_in[9]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and3_1 _62_ (
    .A(_16_),
    .B(_17_),
    .C(_18_),
    .X(_19_)
  );
  sky130_fd_sc_hd__a22oi_1 _63_ (
    .A1(data_in[4]),
    .A2(onehot[6]),
    .B1(onehot[5]),
    .B2(data_in[3]),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a222oi_1 _64_ (
    .A1(data_in[2]),
    .A2(onehot[4]),
    .B1(onehot[3]),
    .B2(data_in[1]),
    .C1(data_in[0]),
    .C2(onehot[2]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nand3_1 _65_ (
    .A(_19_),
    .B(_20_),
    .C(_21_),
    .Y(result[9])
  );
  sky130_fd_sc_hd__a222oi_1 _66_ (
    .A1(onehot[7]),
    .A2(data_in[6]),
    .B1(data_in[7]),
    .B2(onehot[8]),
    .C1(data_in[0]),
    .C2(onehot[1]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a222oi_1 _67_ (
    .A1(onehot[9]),
    .A2(data_in[8]),
    .B1(onehot[3]),
    .B2(data_in[2]),
    .C1(onehot[10]),
    .C2(data_in[9]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__and2_0 _68_ (
    .A(_22_),
    .B(_23_),
    .X(_24_)
  );
  sky130_fd_sc_hd__a222oi_1 _69_ (
    .A1(data_in[4]),
    .A2(onehot[5]),
    .B1(onehot[4]),
    .B2(data_in[3]),
    .C1(onehot[11]),
    .C2(data_in[10]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a22oi_1 _70_ (
    .A1(data_in[5]),
    .A2(onehot[6]),
    .B1(onehot[2]),
    .B2(data_in[1]),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nand3_1 _71_ (
    .A(_24_),
    .B(_25_),
    .C(_26_),
    .Y(result[10])
  );
  sky130_fd_sc_hd__nand2_1 _72_ (
    .A(onehot[11]),
    .B(data_in[11]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a22oi_1 _73_ (
    .A1(data_in[5]),
    .A2(onehot[5]),
    .B1(onehot[3]),
    .B2(data_in[3]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a22oi_1 _74_ (
    .A1(onehot[6]),
    .A2(data_in[6]),
    .B1(onehot[0]),
    .B2(data_in[0]),
    .Y(_29_)
  );
  sky130_fd_sc_hd__a222oi_1 _75_ (
    .A1(onehot[7]),
    .A2(data_in[7]),
    .B1(data_in[9]),
    .B2(onehot[9]),
    .C1(onehot[10]),
    .C2(data_in[10]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a22oi_1 _76_ (
    .A1(onehot[8]),
    .A2(data_in[8]),
    .B1(onehot[2]),
    .B2(data_in[2]),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a22oi_1 _77_ (
    .A1(data_in[4]),
    .A2(onehot[4]),
    .B1(onehot[1]),
    .B2(data_in[1]),
    .Y(_32_)
  );
  sky130_fd_sc_hd__and3_1 _78_ (
    .A(_30_),
    .B(_31_),
    .C(_32_),
    .X(_33_)
  );
  sky130_fd_sc_hd__nand4_1 _79_ (
    .A(_27_),
    .B(_28_),
    .C(_29_),
    .D(_33_),
    .Y(result[11])
  );
endmodule
