/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_fifo_gate(clk, rst_b, fifo_create_en, fifo_create_en_dp, fifo_pop_en, fifo_create_data, fifo_pop_data, fifo_pop_data_vld, fifo_full, fifo_empty, pad_yy_icg_scan_en, fifo_icg_en);
  input clk;
  wire clk;
  input rst_b;
  wire rst_b;
  input fifo_create_en;
  wire fifo_create_en;
  input fifo_create_en_dp;
  wire fifo_create_en_dp;
  input fifo_pop_en;
  wire fifo_pop_en;
  input [5:0] fifo_create_data;
  wire [5:0] fifo_create_data;
  output [5:0] fifo_pop_data;
  wire [5:0] fifo_pop_data;
  output fifo_pop_data_vld;
  wire fifo_pop_data_vld;
  output fifo_full;
  wire fifo_full;
  output fifo_empty;
  wire fifo_empty;
  input pad_yy_icg_scan_en;
  wire pad_yy_icg_scan_en;
  input fifo_icg_en;
  wire fifo_icg_en;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire \DFIFO_GEN[0].x_entry_gated_clk.SE ;
  wire \DFIFO_GEN[0].x_entry_gated_clk.clk_in ;
  wire \DFIFO_GEN[0].x_entry_gated_clk.clk_out ;
  wire \DFIFO_GEN[0].x_entry_gated_clk.external_en ;
  wire \DFIFO_GEN[0].x_entry_gated_clk.global_en ;
  wire \DFIFO_GEN[0].x_entry_gated_clk.module_en ;
  wire \DFIFO_GEN[0].x_entry_gated_clk.pad_yy_icg_scan_en ;
  wire \DFIFO_GEN[1].x_entry_gated_clk.SE ;
  wire \DFIFO_GEN[1].x_entry_gated_clk.clk_in ;
  wire \DFIFO_GEN[1].x_entry_gated_clk.clk_out ;
  wire \DFIFO_GEN[1].x_entry_gated_clk.external_en ;
  wire \DFIFO_GEN[1].x_entry_gated_clk.global_en ;
  wire \DFIFO_GEN[1].x_entry_gated_clk.module_en ;
  wire \DFIFO_GEN[1].x_entry_gated_clk.pad_yy_icg_scan_en ;
  wire ctrl_clk;
  wire [1:0] entry_clk;
  wire fifo_create_idx;
  wire [1:0] fifo_create_ptr;
  wire [5:0] \fifo_entry_cont[0] ;
  wire [5:0] \fifo_entry_cont[1] ;
  wire [1:0] fifo_entry_vld;
  wire fifo_not_empty;
  wire fifo_pop_idx;
  wire [1:0] fifo_pop_sel;
  wire \x_fifo_ctrl_gated_clk.SE ;
  wire \x_fifo_ctrl_gated_clk.clk_in ;
  wire \x_fifo_ctrl_gated_clk.clk_out ;
  wire \x_fifo_ctrl_gated_clk.external_en ;
  wire \x_fifo_ctrl_gated_clk.global_en ;
  wire \x_fifo_ctrl_gated_clk.module_en ;
  wire \x_fifo_ctrl_gated_clk.pad_yy_icg_scan_en ;
  sky130_fd_sc_hd__clkinv_1 _32_ (
    .A(fifo_create_en),
    .Y(_16_)
  );
  sky130_fd_sc_hd__clkinv_1 _33_ (
    .A(fifo_pop_en),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _34_ (
    .A(fifo_create_data[5]),
    .B(fifo_create_data[4]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(fifo_create_en),
    .B(fifo_create_data[0]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__xnor3_1 _36_ (
    .A(pad_yy_icg_scan_en),
    .B(fifo_create_data[3]),
    .C(fifo_pop_en),
    .X(_20_)
  );
  sky130_fd_sc_hd__xnor3_1 _37_ (
    .A(_18_),
    .B(_19_),
    .C(_20_),
    .X(_21_)
  );
  sky130_fd_sc_hd__mux2i_1 _38_ (
    .A0(\fifo_entry_cont[0] [0]),
    .A1(\fifo_entry_cont[1] [0]),
    .S(fifo_pop_idx),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(_21_),
    .B(_22_),
    .Y(fifo_pop_data[0])
  );
  sky130_fd_sc_hd__mux2i_1 _40_ (
    .A0(\fifo_entry_cont[0] [5]),
    .A1(\fifo_entry_cont[1] [5]),
    .S(fifo_pop_idx),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_21_),
    .B(_23_),
    .Y(fifo_pop_data[5])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _42_ (
    .A(fifo_entry_vld[0]),
    .SLEEP(fifo_entry_vld[1]),
    .X(fifo_pop_data_vld)
  );
  sky130_fd_sc_hd__clkinv_1 _43_ (
    .A(fifo_pop_data_vld),
    .Y(fifo_empty)
  );
  sky130_fd_sc_hd__and2_0 _44_ (
    .A(fifo_entry_vld[0]),
    .B(fifo_entry_vld[1]),
    .X(fifo_full)
  );
  sky130_fd_sc_hd__mux2i_1 _45_ (
    .A0(\fifo_entry_cont[0] [4]),
    .A1(\fifo_entry_cont[1] [4]),
    .S(fifo_pop_idx),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xnor2_1 _46_ (
    .A(_21_),
    .B(_24_),
    .Y(fifo_pop_data[4])
  );
  sky130_fd_sc_hd__mux2i_1 _47_ (
    .A0(\fifo_entry_cont[0] [3]),
    .A1(\fifo_entry_cont[1] [3]),
    .S(fifo_pop_idx),
    .Y(_25_)
  );
  sky130_fd_sc_hd__xnor2_1 _48_ (
    .A(_21_),
    .B(_25_),
    .Y(fifo_pop_data[3])
  );
  sky130_fd_sc_hd__mux2i_1 _49_ (
    .A0(\fifo_entry_cont[0] [2]),
    .A1(\fifo_entry_cont[1] [2]),
    .S(fifo_pop_idx),
    .Y(_26_)
  );
  sky130_fd_sc_hd__xnor2_1 _50_ (
    .A(_21_),
    .B(_26_),
    .Y(fifo_pop_data[2])
  );
  sky130_fd_sc_hd__mux2i_1 _51_ (
    .A0(\fifo_entry_cont[0] [1]),
    .A1(\fifo_entry_cont[1] [1]),
    .S(fifo_pop_idx),
    .Y(_27_)
  );
  sky130_fd_sc_hd__xnor2_1 _52_ (
    .A(_21_),
    .B(_27_),
    .Y(fifo_pop_data[1])
  );
  sky130_fd_sc_hd__nand2_1 _53_ (
    .A(fifo_create_idx),
    .B(fifo_create_en_dp),
    .Y(_28_)
  );
  sky130_fd_sc_hd__mux2_1 _54_ (
    .A0(fifo_create_data[0]),
    .A1(\fifo_entry_cont[1] [0]),
    .S(_28_),
    .X(_00_)
  );
  sky130_fd_sc_hd__nand2b_1 _55_ (
    .A_N(fifo_create_idx),
    .B(fifo_create_en_dp),
    .Y(_29_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(fifo_create_data[4]),
    .A1(\fifo_entry_cont[0] [4]),
    .S(_29_),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _57_ (
    .A0(fifo_create_data[5]),
    .A1(\fifo_entry_cont[1] [5]),
    .S(_28_),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _58_ (
    .A0(fifo_create_data[3]),
    .A1(\fifo_entry_cont[0] [3]),
    .S(_29_),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _59_ (
    .A(fifo_create_idx),
    .B(fifo_create_en),
    .X(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _60_ (
    .A(fifo_pop_idx),
    .B(fifo_pop_en),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a22o_1 _61_ (
    .A1(fifo_create_idx),
    .A2(fifo_create_en),
    .B1(fifo_entry_vld[1]),
    .B2(_30_),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _62_ (
    .A0(fifo_create_data[2]),
    .A1(\fifo_entry_cont[0] [2]),
    .S(_29_),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _63_ (
    .A0(fifo_create_data[1]),
    .A1(\fifo_entry_cont[0] [1]),
    .S(_29_),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _64_ (
    .A0(fifo_create_data[0]),
    .A1(\fifo_entry_cont[0] [0]),
    .S(_29_),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _65_ (
    .A0(fifo_create_data[4]),
    .A1(\fifo_entry_cont[1] [4]),
    .S(_28_),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _66_ (
    .A0(fifo_create_data[3]),
    .A1(\fifo_entry_cont[1] [3]),
    .S(_28_),
    .X(_10_)
  );
  sky130_fd_sc_hd__o21ai_0 _67_ (
    .A1(fifo_pop_idx),
    .A2(_17_),
    .B1(fifo_entry_vld[0]),
    .Y(_31_)
  );
  sky130_fd_sc_hd__o21ai_0 _68_ (
    .A1(fifo_create_idx),
    .A2(_16_),
    .B1(_31_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _69_ (
    .A0(fifo_create_data[2]),
    .A1(\fifo_entry_cont[1] [2]),
    .S(_28_),
    .X(_12_)
  );
  sky130_fd_sc_hd__xor2_1 _70_ (
    .A(fifo_pop_idx),
    .B(fifo_pop_en),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _71_ (
    .A0(fifo_create_data[5]),
    .A1(\fifo_entry_cont[0] [5]),
    .S(_29_),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _72_ (
    .A0(fifo_create_data[1]),
    .A1(\fifo_entry_cont[1] [1]),
    .S(_28_),
    .X(_15_)
  );
  sky130_fd_sc_hd__dfrtp_1 _73_ (
    .CLK(clk),
    .D(_00_),
    .Q(\fifo_entry_cont[1] [0]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _74_ (
    .CLK(clk),
    .D(_15_),
    .Q(\fifo_entry_cont[1] [1]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _75_ (
    .CLK(clk),
    .D(_12_),
    .Q(\fifo_entry_cont[1] [2]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _76_ (
    .CLK(clk),
    .D(_10_),
    .Q(\fifo_entry_cont[1] [3]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _77_ (
    .CLK(clk),
    .D(_09_),
    .Q(\fifo_entry_cont[1] [4]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _78_ (
    .CLK(clk),
    .D(_02_),
    .Q(\fifo_entry_cont[1] [5]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _79_ (
    .CLK(clk),
    .D(_04_),
    .Q(fifo_create_idx),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _80_ (
    .CLK(clk),
    .D(_05_),
    .Q(fifo_entry_vld[1]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _81_ (
    .CLK(clk),
    .D(_11_),
    .Q(fifo_entry_vld[0]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _82_ (
    .CLK(clk),
    .D(_13_),
    .Q(fifo_pop_idx),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _83_ (
    .CLK(clk),
    .D(_08_),
    .Q(\fifo_entry_cont[0] [0]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _84_ (
    .CLK(clk),
    .D(_07_),
    .Q(\fifo_entry_cont[0] [1]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _85_ (
    .CLK(clk),
    .D(_06_),
    .Q(\fifo_entry_cont[0] [2]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _86_ (
    .CLK(clk),
    .D(_03_),
    .Q(\fifo_entry_cont[0] [3]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _87_ (
    .CLK(clk),
    .D(_01_),
    .Q(\fifo_entry_cont[0] [4]),
    .RESET_B(rst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _88_ (
    .CLK(clk),
    .D(_14_),
    .Q(\fifo_entry_cont[0] [5]),
    .RESET_B(rst_b)
  );
  assign \DFIFO_GEN[0].x_entry_gated_clk.clk_in  = clk;
  assign \x_fifo_ctrl_gated_clk.module_en  = fifo_icg_en;
  assign \x_fifo_ctrl_gated_clk.SE  = pad_yy_icg_scan_en;
  assign \x_fifo_ctrl_gated_clk.global_en  = 1'h1;
  assign \DFIFO_GEN[1].x_entry_gated_clk.SE  = pad_yy_icg_scan_en;
  assign \x_fifo_ctrl_gated_clk.pad_yy_icg_scan_en  = pad_yy_icg_scan_en;
  assign \DFIFO_GEN[1].x_entry_gated_clk.clk_out  = clk;
  assign \DFIFO_GEN[1].x_entry_gated_clk.pad_yy_icg_scan_en  = pad_yy_icg_scan_en;
  assign \DFIFO_GEN[1].x_entry_gated_clk.external_en  = 1'h0;
  assign \x_fifo_ctrl_gated_clk.clk_in  = clk;
  assign \DFIFO_GEN[1].x_entry_gated_clk.module_en  = fifo_icg_en;
  assign \DFIFO_GEN[1].x_entry_gated_clk.global_en  = 1'h1;
  assign \x_fifo_ctrl_gated_clk.external_en  = 1'h0;
  assign \DFIFO_GEN[0].x_entry_gated_clk.SE  = pad_yy_icg_scan_en;
  assign \x_fifo_ctrl_gated_clk.clk_out  = clk;
  assign \DFIFO_GEN[0].x_entry_gated_clk.clk_out  = clk;
  assign \DFIFO_GEN[0].x_entry_gated_clk.pad_yy_icg_scan_en  = pad_yy_icg_scan_en;
  assign \DFIFO_GEN[0].x_entry_gated_clk.external_en  = 1'h0;
  assign \DFIFO_GEN[0].x_entry_gated_clk.module_en  = fifo_icg_en;
  assign \DFIFO_GEN[0].x_entry_gated_clk.global_en  = 1'h1;
  assign fifo_not_empty = fifo_pop_data_vld;
  assign fifo_pop_sel[1] = fifo_pop_idx;
  assign fifo_create_ptr[1] = fifo_create_idx;
  assign entry_clk = { clk, clk };
  assign \DFIFO_GEN[1].x_entry_gated_clk.clk_in  = clk;
  assign ctrl_clk = clk;
endmodule
