/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_rtu_expand_32(x_num, x_num_expand);
  input [4:0] x_num;
  wire [4:0] x_num;
  output [31:0] x_num_expand;
  wire [31:0] x_num_expand;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  sky130_fd_sc_hd__and2_0 _14_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .X(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _15_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and2_0 _16_ (
    .A(x_num[3]),
    .B(x_num[2]),
    .X(_02_)
  );
  sky130_fd_sc_hd__nand2_1 _17_ (
    .A(x_num[3]),
    .B(x_num[2]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and3_1 _18_ (
    .A(x_num[4]),
    .B(_00_),
    .C(_02_),
    .X(x_num_expand[31])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _19_ (
    .A(x_num[1]),
    .SLEEP(x_num[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__nand2b_1 _20_ (
    .A_N(x_num[0]),
    .B(x_num[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__and3_1 _21_ (
    .A(x_num[4]),
    .B(_02_),
    .C(_04_),
    .X(x_num_expand[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _22_ (
    .A(x_num[0]),
    .SLEEP(x_num[1]),
    .X(_06_)
  );
  sky130_fd_sc_hd__nand2b_1 _23_ (
    .A_N(x_num[1]),
    .B(x_num[0]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and3_1 _24_ (
    .A(x_num[4]),
    .B(_02_),
    .C(_06_),
    .X(x_num_expand[29])
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__and3_1 _26_ (
    .A(x_num[4]),
    .B(_02_),
    .C(_08_),
    .X(x_num_expand[28])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _27_ (
    .A(x_num[3]),
    .SLEEP(x_num[2]),
    .X(_09_)
  );
  sky130_fd_sc_hd__nand2b_1 _28_ (
    .A_N(x_num[2]),
    .B(x_num[3]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and3_1 _29_ (
    .A(x_num[4]),
    .B(_00_),
    .C(_09_),
    .X(x_num_expand[27])
  );
  sky130_fd_sc_hd__and3_1 _30_ (
    .A(x_num[4]),
    .B(_04_),
    .C(_09_),
    .X(x_num_expand[26])
  );
  sky130_fd_sc_hd__and3_1 _31_ (
    .A(x_num[4]),
    .B(_06_),
    .C(_09_),
    .X(x_num_expand[25])
  );
  sky130_fd_sc_hd__and3_1 _32_ (
    .A(x_num[4]),
    .B(_08_),
    .C(_09_),
    .X(x_num_expand[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _33_ (
    .A(x_num[2]),
    .SLEEP(x_num[3]),
    .X(_11_)
  );
  sky130_fd_sc_hd__nand2b_1 _34_ (
    .A_N(x_num[3]),
    .B(x_num[2]),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and3_1 _35_ (
    .A(x_num[4]),
    .B(_00_),
    .C(_11_),
    .X(x_num_expand[23])
  );
  sky130_fd_sc_hd__and3_1 _36_ (
    .A(x_num[4]),
    .B(_04_),
    .C(_11_),
    .X(x_num_expand[22])
  );
  sky130_fd_sc_hd__and3_1 _37_ (
    .A(x_num[4]),
    .B(_06_),
    .C(_11_),
    .X(x_num_expand[21])
  );
  sky130_fd_sc_hd__and3_1 _38_ (
    .A(x_num[4]),
    .B(_08_),
    .C(_11_),
    .X(x_num_expand[20])
  );
  sky130_fd_sc_hd__nor2_1 _39_ (
    .A(x_num[3]),
    .B(x_num[2]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and3_1 _40_ (
    .A(x_num[4]),
    .B(_00_),
    .C(_13_),
    .X(x_num_expand[19])
  );
  sky130_fd_sc_hd__and3_1 _41_ (
    .A(x_num[4]),
    .B(_04_),
    .C(_13_),
    .X(x_num_expand[18])
  );
  sky130_fd_sc_hd__and3_1 _42_ (
    .A(x_num[4]),
    .B(_06_),
    .C(_13_),
    .X(x_num_expand[17])
  );
  sky130_fd_sc_hd__and3_1 _43_ (
    .A(x_num[4]),
    .B(_08_),
    .C(_13_),
    .X(x_num_expand[16])
  );
  sky130_fd_sc_hd__nor3_1 _44_ (
    .A(x_num[4]),
    .B(_01_),
    .C(_03_),
    .Y(x_num_expand[15])
  );
  sky130_fd_sc_hd__nor3_1 _45_ (
    .A(x_num[4]),
    .B(_03_),
    .C(_05_),
    .Y(x_num_expand[14])
  );
  sky130_fd_sc_hd__nor3_1 _46_ (
    .A(x_num[4]),
    .B(_03_),
    .C(_07_),
    .Y(x_num_expand[13])
  );
  sky130_fd_sc_hd__nor4_1 _47_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .C(x_num[4]),
    .D(_03_),
    .Y(x_num_expand[12])
  );
  sky130_fd_sc_hd__nor3_1 _48_ (
    .A(x_num[4]),
    .B(_01_),
    .C(_10_),
    .Y(x_num_expand[11])
  );
  sky130_fd_sc_hd__nor3_1 _49_ (
    .A(x_num[4]),
    .B(_05_),
    .C(_10_),
    .Y(x_num_expand[10])
  );
  sky130_fd_sc_hd__nor3_1 _50_ (
    .A(x_num[4]),
    .B(_07_),
    .C(_10_),
    .Y(x_num_expand[9])
  );
  sky130_fd_sc_hd__nor4_1 _51_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .C(x_num[4]),
    .D(_10_),
    .Y(x_num_expand[8])
  );
  sky130_fd_sc_hd__nor3_1 _52_ (
    .A(x_num[4]),
    .B(_01_),
    .C(_12_),
    .Y(x_num_expand[7])
  );
  sky130_fd_sc_hd__nor3_1 _53_ (
    .A(x_num[4]),
    .B(_05_),
    .C(_12_),
    .Y(x_num_expand[6])
  );
  sky130_fd_sc_hd__nor3_1 _54_ (
    .A(x_num[4]),
    .B(_07_),
    .C(_12_),
    .Y(x_num_expand[5])
  );
  sky130_fd_sc_hd__nor4_1 _55_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .C(x_num[4]),
    .D(_12_),
    .Y(x_num_expand[4])
  );
  sky130_fd_sc_hd__nor4_1 _56_ (
    .A(x_num[3]),
    .B(x_num[2]),
    .C(x_num[4]),
    .D(_01_),
    .Y(x_num_expand[3])
  );
  sky130_fd_sc_hd__nor4_1 _57_ (
    .A(x_num[3]),
    .B(x_num[2]),
    .C(x_num[4]),
    .D(_05_),
    .Y(x_num_expand[2])
  );
  sky130_fd_sc_hd__nor4_1 _58_ (
    .A(x_num[3]),
    .B(x_num[2]),
    .C(x_num[4]),
    .D(_07_),
    .Y(x_num_expand[1])
  );
  sky130_fd_sc_hd__and3b_1 _59_ (
    .A_N(x_num[4]),
    .B(_08_),
    .C(_13_),
    .X(x_num_expand[0])
  );
endmodule

module ct_rtu_expand_96(x_num, x_num_expand);
  input [6:0] x_num;
  wire [6:0] x_num;
  output [95:0] x_num_expand;
  wire [95:0] x_num_expand;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  sky130_fd_sc_hd__nand4_1 _022_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .C(x_num[3]),
    .D(x_num[2]),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand3b_1 _023_ (
    .A_N(x_num[5]),
    .B(x_num[6]),
    .C(x_num[4]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor2_1 _024_ (
    .A(_000_),
    .B(_001_),
    .Y(x_num_expand[95])
  );
  sky130_fd_sc_hd__nand4b_1 _025_ (
    .A_N(x_num[0]),
    .B(x_num[1]),
    .C(x_num[3]),
    .D(x_num[2]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _026_ (
    .A(_001_),
    .B(_002_),
    .Y(x_num_expand[94])
  );
  sky130_fd_sc_hd__nand4b_1 _027_ (
    .A_N(x_num[1]),
    .B(x_num[3]),
    .C(x_num[2]),
    .D(x_num[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _028_ (
    .A(_001_),
    .B(_003_),
    .Y(x_num_expand[93])
  );
  sky130_fd_sc_hd__nand4bb_1 _029_ (
    .A_N(x_num[0]),
    .B_N(x_num[1]),
    .C(x_num[3]),
    .D(x_num[2]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _030_ (
    .A(_001_),
    .B(_004_),
    .Y(x_num_expand[92])
  );
  sky130_fd_sc_hd__nand4b_1 _031_ (
    .A_N(x_num[2]),
    .B(x_num[3]),
    .C(x_num[1]),
    .D(x_num[0]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _032_ (
    .A(_001_),
    .B(_005_),
    .Y(x_num_expand[91])
  );
  sky130_fd_sc_hd__nand4bb_1 _033_ (
    .A_N(x_num[0]),
    .B_N(x_num[2]),
    .C(x_num[3]),
    .D(x_num[1]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _034_ (
    .A(_001_),
    .B(_006_),
    .Y(x_num_expand[90])
  );
  sky130_fd_sc_hd__nand4bb_1 _035_ (
    .A_N(x_num[1]),
    .B_N(x_num[2]),
    .C(x_num[3]),
    .D(x_num[0]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _036_ (
    .A(_001_),
    .B(_007_),
    .Y(x_num_expand[89])
  );
  sky130_fd_sc_hd__or4b_1 _037_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .C(x_num[2]),
    .D_N(x_num[3]),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _038_ (
    .A(_001_),
    .B(_008_),
    .Y(x_num_expand[88])
  );
  sky130_fd_sc_hd__nand4b_1 _039_ (
    .A_N(x_num[3]),
    .B(x_num[2]),
    .C(x_num[0]),
    .D(x_num[1]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nor2_1 _040_ (
    .A(_001_),
    .B(_009_),
    .Y(x_num_expand[87])
  );
  sky130_fd_sc_hd__nand4bb_1 _041_ (
    .A_N(x_num[0]),
    .B_N(x_num[3]),
    .C(x_num[2]),
    .D(x_num[1]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor2_1 _042_ (
    .A(_001_),
    .B(_010_),
    .Y(x_num_expand[86])
  );
  sky130_fd_sc_hd__nand4bb_1 _043_ (
    .A_N(x_num[1]),
    .B_N(x_num[3]),
    .C(x_num[2]),
    .D(x_num[0]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _044_ (
    .A(_001_),
    .B(_011_),
    .Y(x_num_expand[85])
  );
  sky130_fd_sc_hd__or4b_1 _045_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .C(x_num[3]),
    .D_N(x_num[2]),
    .X(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _046_ (
    .A(_001_),
    .B(_012_),
    .Y(x_num_expand[84])
  );
  sky130_fd_sc_hd__nand4bb_1 _047_ (
    .A_N(x_num[3]),
    .B_N(x_num[2]),
    .C(x_num[0]),
    .D(x_num[1]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor2_1 _048_ (
    .A(_001_),
    .B(_013_),
    .Y(x_num_expand[83])
  );
  sky130_fd_sc_hd__or4b_1 _049_ (
    .A(x_num[0]),
    .B(x_num[3]),
    .C(x_num[2]),
    .D_N(x_num[1]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nor2_1 _050_ (
    .A(_001_),
    .B(_014_),
    .Y(x_num_expand[82])
  );
  sky130_fd_sc_hd__or4b_1 _051_ (
    .A(x_num[1]),
    .B(x_num[3]),
    .C(x_num[2]),
    .D_N(x_num[0]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nor2_1 _052_ (
    .A(_001_),
    .B(_015_),
    .Y(x_num_expand[81])
  );
  sky130_fd_sc_hd__or4_1 _053_ (
    .A(x_num[0]),
    .B(x_num[1]),
    .C(x_num[3]),
    .D(x_num[2]),
    .X(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _054_ (
    .A(_001_),
    .B(_016_),
    .Y(x_num_expand[80])
  );
  sky130_fd_sc_hd__or3b_1 _055_ (
    .A(x_num[4]),
    .B(x_num[5]),
    .C_N(x_num[6]),
    .X(_017_)
  );
  sky130_fd_sc_hd__nor2_1 _056_ (
    .A(_000_),
    .B(_017_),
    .Y(x_num_expand[79])
  );
  sky130_fd_sc_hd__nor2_1 _057_ (
    .A(_002_),
    .B(_017_),
    .Y(x_num_expand[78])
  );
  sky130_fd_sc_hd__nor2_1 _058_ (
    .A(_003_),
    .B(_017_),
    .Y(x_num_expand[77])
  );
  sky130_fd_sc_hd__nor2_1 _059_ (
    .A(_004_),
    .B(_017_),
    .Y(x_num_expand[76])
  );
  sky130_fd_sc_hd__nor2_1 _060_ (
    .A(_005_),
    .B(_017_),
    .Y(x_num_expand[75])
  );
  sky130_fd_sc_hd__nor2_1 _061_ (
    .A(_006_),
    .B(_017_),
    .Y(x_num_expand[74])
  );
  sky130_fd_sc_hd__nor2_1 _062_ (
    .A(_007_),
    .B(_017_),
    .Y(x_num_expand[73])
  );
  sky130_fd_sc_hd__nor2_1 _063_ (
    .A(_008_),
    .B(_017_),
    .Y(x_num_expand[72])
  );
  sky130_fd_sc_hd__nor2_1 _064_ (
    .A(_009_),
    .B(_017_),
    .Y(x_num_expand[71])
  );
  sky130_fd_sc_hd__nor2_1 _065_ (
    .A(_010_),
    .B(_017_),
    .Y(x_num_expand[70])
  );
  sky130_fd_sc_hd__nor2_1 _066_ (
    .A(_011_),
    .B(_017_),
    .Y(x_num_expand[69])
  );
  sky130_fd_sc_hd__nor2_1 _067_ (
    .A(_012_),
    .B(_017_),
    .Y(x_num_expand[68])
  );
  sky130_fd_sc_hd__nor2_1 _068_ (
    .A(_013_),
    .B(_017_),
    .Y(x_num_expand[67])
  );
  sky130_fd_sc_hd__nor2_1 _069_ (
    .A(_014_),
    .B(_017_),
    .Y(x_num_expand[66])
  );
  sky130_fd_sc_hd__nor2_1 _070_ (
    .A(_015_),
    .B(_017_),
    .Y(x_num_expand[65])
  );
  sky130_fd_sc_hd__nor2_1 _071_ (
    .A(_016_),
    .B(_017_),
    .Y(x_num_expand[64])
  );
  sky130_fd_sc_hd__nand3b_1 _072_ (
    .A_N(x_num[6]),
    .B(x_num[5]),
    .C(x_num[4]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _073_ (
    .A(_000_),
    .B(_018_),
    .Y(x_num_expand[63])
  );
  sky130_fd_sc_hd__nor2_1 _074_ (
    .A(_002_),
    .B(_018_),
    .Y(x_num_expand[62])
  );
  sky130_fd_sc_hd__nor2_1 _075_ (
    .A(_003_),
    .B(_018_),
    .Y(x_num_expand[61])
  );
  sky130_fd_sc_hd__nor2_1 _076_ (
    .A(_004_),
    .B(_018_),
    .Y(x_num_expand[60])
  );
  sky130_fd_sc_hd__nor2_1 _077_ (
    .A(_005_),
    .B(_018_),
    .Y(x_num_expand[59])
  );
  sky130_fd_sc_hd__nor2_1 _078_ (
    .A(_006_),
    .B(_018_),
    .Y(x_num_expand[58])
  );
  sky130_fd_sc_hd__nor2_1 _079_ (
    .A(_007_),
    .B(_018_),
    .Y(x_num_expand[57])
  );
  sky130_fd_sc_hd__nor2_1 _080_ (
    .A(_008_),
    .B(_018_),
    .Y(x_num_expand[56])
  );
  sky130_fd_sc_hd__nor2_1 _081_ (
    .A(_009_),
    .B(_018_),
    .Y(x_num_expand[55])
  );
  sky130_fd_sc_hd__nor2_1 _082_ (
    .A(_010_),
    .B(_018_),
    .Y(x_num_expand[54])
  );
  sky130_fd_sc_hd__nor2_1 _083_ (
    .A(_011_),
    .B(_018_),
    .Y(x_num_expand[53])
  );
  sky130_fd_sc_hd__nor2_1 _084_ (
    .A(_012_),
    .B(_018_),
    .Y(x_num_expand[52])
  );
  sky130_fd_sc_hd__nor2_1 _085_ (
    .A(_013_),
    .B(_018_),
    .Y(x_num_expand[51])
  );
  sky130_fd_sc_hd__nor2_1 _086_ (
    .A(_014_),
    .B(_018_),
    .Y(x_num_expand[50])
  );
  sky130_fd_sc_hd__nor2_1 _087_ (
    .A(_015_),
    .B(_018_),
    .Y(x_num_expand[49])
  );
  sky130_fd_sc_hd__nor2_1 _088_ (
    .A(_016_),
    .B(_018_),
    .Y(x_num_expand[48])
  );
  sky130_fd_sc_hd__or3b_1 _089_ (
    .A(x_num[4]),
    .B(x_num[6]),
    .C_N(x_num[5]),
    .X(_019_)
  );
  sky130_fd_sc_hd__nor2_1 _090_ (
    .A(_000_),
    .B(_019_),
    .Y(x_num_expand[47])
  );
  sky130_fd_sc_hd__nor2_1 _091_ (
    .A(_002_),
    .B(_019_),
    .Y(x_num_expand[46])
  );
  sky130_fd_sc_hd__nor2_1 _092_ (
    .A(_003_),
    .B(_019_),
    .Y(x_num_expand[45])
  );
  sky130_fd_sc_hd__nor2_1 _093_ (
    .A(_004_),
    .B(_019_),
    .Y(x_num_expand[44])
  );
  sky130_fd_sc_hd__nor2_1 _094_ (
    .A(_005_),
    .B(_019_),
    .Y(x_num_expand[43])
  );
  sky130_fd_sc_hd__nor2_1 _095_ (
    .A(_006_),
    .B(_019_),
    .Y(x_num_expand[42])
  );
  sky130_fd_sc_hd__nor2_1 _096_ (
    .A(_007_),
    .B(_019_),
    .Y(x_num_expand[41])
  );
  sky130_fd_sc_hd__nor2_1 _097_ (
    .A(_008_),
    .B(_019_),
    .Y(x_num_expand[40])
  );
  sky130_fd_sc_hd__nor2_1 _098_ (
    .A(_009_),
    .B(_019_),
    .Y(x_num_expand[39])
  );
  sky130_fd_sc_hd__nor2_1 _099_ (
    .A(_010_),
    .B(_019_),
    .Y(x_num_expand[38])
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(_011_),
    .B(_019_),
    .Y(x_num_expand[37])
  );
  sky130_fd_sc_hd__nor2_1 _101_ (
    .A(_012_),
    .B(_019_),
    .Y(x_num_expand[36])
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(_013_),
    .B(_019_),
    .Y(x_num_expand[35])
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(_014_),
    .B(_019_),
    .Y(x_num_expand[34])
  );
  sky130_fd_sc_hd__nor2_1 _104_ (
    .A(_015_),
    .B(_019_),
    .Y(x_num_expand[33])
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(_016_),
    .B(_019_),
    .Y(x_num_expand[32])
  );
  sky130_fd_sc_hd__or3b_1 _106_ (
    .A(x_num[5]),
    .B(x_num[6]),
    .C_N(x_num[4]),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _107_ (
    .A(_000_),
    .B(_020_),
    .Y(x_num_expand[31])
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(_002_),
    .B(_020_),
    .Y(x_num_expand[30])
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(_003_),
    .B(_020_),
    .Y(x_num_expand[29])
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(_004_),
    .B(_020_),
    .Y(x_num_expand[28])
  );
  sky130_fd_sc_hd__nor2_1 _111_ (
    .A(_005_),
    .B(_020_),
    .Y(x_num_expand[27])
  );
  sky130_fd_sc_hd__nor2_1 _112_ (
    .A(_006_),
    .B(_020_),
    .Y(x_num_expand[26])
  );
  sky130_fd_sc_hd__nor2_1 _113_ (
    .A(_007_),
    .B(_020_),
    .Y(x_num_expand[25])
  );
  sky130_fd_sc_hd__nor2_1 _114_ (
    .A(_008_),
    .B(_020_),
    .Y(x_num_expand[24])
  );
  sky130_fd_sc_hd__nor2_1 _115_ (
    .A(_009_),
    .B(_020_),
    .Y(x_num_expand[23])
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(_010_),
    .B(_020_),
    .Y(x_num_expand[22])
  );
  sky130_fd_sc_hd__nor2_1 _117_ (
    .A(_011_),
    .B(_020_),
    .Y(x_num_expand[21])
  );
  sky130_fd_sc_hd__nor2_1 _118_ (
    .A(_012_),
    .B(_020_),
    .Y(x_num_expand[20])
  );
  sky130_fd_sc_hd__nor2_1 _119_ (
    .A(_013_),
    .B(_020_),
    .Y(x_num_expand[19])
  );
  sky130_fd_sc_hd__nor2_1 _120_ (
    .A(_014_),
    .B(_020_),
    .Y(x_num_expand[18])
  );
  sky130_fd_sc_hd__nor2_1 _121_ (
    .A(_015_),
    .B(_020_),
    .Y(x_num_expand[17])
  );
  sky130_fd_sc_hd__nor2_1 _122_ (
    .A(_016_),
    .B(_020_),
    .Y(x_num_expand[16])
  );
  sky130_fd_sc_hd__or3_1 _123_ (
    .A(x_num[4]),
    .B(x_num[5]),
    .C(x_num[6]),
    .X(_021_)
  );
  sky130_fd_sc_hd__nor2_1 _124_ (
    .A(_000_),
    .B(_021_),
    .Y(x_num_expand[15])
  );
  sky130_fd_sc_hd__nor2_1 _125_ (
    .A(_002_),
    .B(_021_),
    .Y(x_num_expand[14])
  );
  sky130_fd_sc_hd__nor2_1 _126_ (
    .A(_003_),
    .B(_021_),
    .Y(x_num_expand[13])
  );
  sky130_fd_sc_hd__nor2_1 _127_ (
    .A(_004_),
    .B(_021_),
    .Y(x_num_expand[12])
  );
  sky130_fd_sc_hd__nor2_1 _128_ (
    .A(_005_),
    .B(_021_),
    .Y(x_num_expand[11])
  );
  sky130_fd_sc_hd__nor2_1 _129_ (
    .A(_006_),
    .B(_021_),
    .Y(x_num_expand[10])
  );
  sky130_fd_sc_hd__nor2_1 _130_ (
    .A(_007_),
    .B(_021_),
    .Y(x_num_expand[9])
  );
  sky130_fd_sc_hd__nor2_1 _131_ (
    .A(_008_),
    .B(_021_),
    .Y(x_num_expand[8])
  );
  sky130_fd_sc_hd__nor2_1 _132_ (
    .A(_009_),
    .B(_021_),
    .Y(x_num_expand[7])
  );
  sky130_fd_sc_hd__nor2_1 _133_ (
    .A(_010_),
    .B(_021_),
    .Y(x_num_expand[6])
  );
  sky130_fd_sc_hd__nor2_1 _134_ (
    .A(_011_),
    .B(_021_),
    .Y(x_num_expand[5])
  );
  sky130_fd_sc_hd__nor2_1 _135_ (
    .A(_012_),
    .B(_021_),
    .Y(x_num_expand[4])
  );
  sky130_fd_sc_hd__nor2_1 _136_ (
    .A(_013_),
    .B(_021_),
    .Y(x_num_expand[3])
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(_014_),
    .B(_021_),
    .Y(x_num_expand[2])
  );
  sky130_fd_sc_hd__nor2_1 _138_ (
    .A(_015_),
    .B(_021_),
    .Y(x_num_expand[1])
  );
  sky130_fd_sc_hd__nor2_1 _139_ (
    .A(_016_),
    .B(_021_),
    .Y(x_num_expand[0])
  );
endmodule

module ct_rtu_pst_preg_entry(cp0_rtu_icg_en, cp0_yy_clk_en, cpurst_b, dealloc_vld_for_gateclk, forever_cpuclk, idu_rtu_pst_dis_inst0_dst_reg, idu_rtu_pst_dis_inst0_preg_iid, idu_rtu_pst_dis_inst0_rel_preg, idu_rtu_pst_dis_inst1_dst_reg, idu_rtu_pst_dis_inst1_preg_iid, idu_rtu_pst_dis_inst1_rel_preg, idu_rtu_pst_dis_inst2_dst_reg, idu_rtu_pst_dis_inst2_preg_iid, idu_rtu_pst_dis_inst2_rel_preg, idu_rtu_pst_dis_inst3_dst_reg, idu_rtu_pst_dis_inst3_preg_iid, idu_rtu_pst_dis_inst3_rel_preg, ifu_xx_sync_reset, pad_yy_icg_scan_en, retire_pst_async_flush, retire_pst_wb_retire_inst0_preg_vld
, retire_pst_wb_retire_inst1_preg_vld, retire_pst_wb_retire_inst2_preg_vld, rob_pst_retire_inst0_gateclk_vld, rob_pst_retire_inst0_iid_updt_val, rob_pst_retire_inst1_gateclk_vld, rob_pst_retire_inst1_iid_updt_val, rob_pst_retire_inst2_gateclk_vld, rob_pst_retire_inst2_iid_updt_val, rtu_yy_xx_flush, x_create_vld, x_cur_state_dealloc, x_dealloc_mask, x_dealloc_vld, x_dreg, x_rel_preg_expand, x_release_vld, x_reset_dst_reg, x_reset_mapped, x_retired_released_wb, x_wb_vld);
  input cp0_rtu_icg_en;
  wire cp0_rtu_icg_en;
  input cp0_yy_clk_en;
  wire cp0_yy_clk_en;
  input cpurst_b;
  wire cpurst_b;
  input dealloc_vld_for_gateclk;
  wire dealloc_vld_for_gateclk;
  input forever_cpuclk;
  wire forever_cpuclk;
  input [4:0] idu_rtu_pst_dis_inst0_dst_reg;
  wire [4:0] idu_rtu_pst_dis_inst0_dst_reg;
  input [6:0] idu_rtu_pst_dis_inst0_preg_iid;
  wire [6:0] idu_rtu_pst_dis_inst0_preg_iid;
  input [6:0] idu_rtu_pst_dis_inst0_rel_preg;
  wire [6:0] idu_rtu_pst_dis_inst0_rel_preg;
  input [4:0] idu_rtu_pst_dis_inst1_dst_reg;
  wire [4:0] idu_rtu_pst_dis_inst1_dst_reg;
  input [6:0] idu_rtu_pst_dis_inst1_preg_iid;
  wire [6:0] idu_rtu_pst_dis_inst1_preg_iid;
  input [6:0] idu_rtu_pst_dis_inst1_rel_preg;
  wire [6:0] idu_rtu_pst_dis_inst1_rel_preg;
  input [4:0] idu_rtu_pst_dis_inst2_dst_reg;
  wire [4:0] idu_rtu_pst_dis_inst2_dst_reg;
  input [6:0] idu_rtu_pst_dis_inst2_preg_iid;
  wire [6:0] idu_rtu_pst_dis_inst2_preg_iid;
  input [6:0] idu_rtu_pst_dis_inst2_rel_preg;
  wire [6:0] idu_rtu_pst_dis_inst2_rel_preg;
  input [4:0] idu_rtu_pst_dis_inst3_dst_reg;
  wire [4:0] idu_rtu_pst_dis_inst3_dst_reg;
  input [6:0] idu_rtu_pst_dis_inst3_preg_iid;
  wire [6:0] idu_rtu_pst_dis_inst3_preg_iid;
  input [6:0] idu_rtu_pst_dis_inst3_rel_preg;
  wire [6:0] idu_rtu_pst_dis_inst3_rel_preg;
  input ifu_xx_sync_reset;
  wire ifu_xx_sync_reset;
  input pad_yy_icg_scan_en;
  wire pad_yy_icg_scan_en;
  input retire_pst_async_flush;
  wire retire_pst_async_flush;
  input retire_pst_wb_retire_inst0_preg_vld;
  wire retire_pst_wb_retire_inst0_preg_vld;
  input retire_pst_wb_retire_inst1_preg_vld;
  wire retire_pst_wb_retire_inst1_preg_vld;
  input retire_pst_wb_retire_inst2_preg_vld;
  wire retire_pst_wb_retire_inst2_preg_vld;
  input rob_pst_retire_inst0_gateclk_vld;
  wire rob_pst_retire_inst0_gateclk_vld;
  input [6:0] rob_pst_retire_inst0_iid_updt_val;
  wire [6:0] rob_pst_retire_inst0_iid_updt_val;
  input rob_pst_retire_inst1_gateclk_vld;
  wire rob_pst_retire_inst1_gateclk_vld;
  input [6:0] rob_pst_retire_inst1_iid_updt_val;
  wire [6:0] rob_pst_retire_inst1_iid_updt_val;
  input rob_pst_retire_inst2_gateclk_vld;
  wire rob_pst_retire_inst2_gateclk_vld;
  input [6:0] rob_pst_retire_inst2_iid_updt_val;
  wire [6:0] rob_pst_retire_inst2_iid_updt_val;
  input rtu_yy_xx_flush;
  wire rtu_yy_xx_flush;
  input [3:0] x_create_vld;
  wire [3:0] x_create_vld;
  output x_cur_state_dealloc;
  wire x_cur_state_dealloc;
  input x_dealloc_mask;
  wire x_dealloc_mask;
  input x_dealloc_vld;
  wire x_dealloc_vld;
  output [31:0] x_dreg;
  wire [31:0] x_dreg;
  output [95:0] x_rel_preg_expand;
  wire [95:0] x_rel_preg_expand;
  input x_release_vld;
  wire x_release_vld;
  input [4:0] x_reset_dst_reg;
  wire [4:0] x_reset_dst_reg;
  input x_reset_mapped;
  wire x_reset_mapped;
  output x_retired_released_wb;
  wire x_retired_released_wb;
  input x_wb_vld;
  wire x_wb_vld;
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire alloc_clk;
  wire alloc_clk_en;
  wire [4:0] dst_reg;
  wire [31:0] dst_reg_expand;
  wire [6:0] iid;
  wire [4:0] lifecycle_cur_state;
  wire lifecycle_cur_state_alloc;
  wire lifecycle_cur_state_dealloc;
  wire lifecycle_cur_state_release;
  wire lifecycle_cur_state_retire;
  wire [6:0] rel_preg;
  wire [95:0] rel_preg_expand;
  wire [3:0] reset_lifecycle_state;
  wire reset_wb_state;
  wire retire_inst0_iid_match;
  wire retire_inst1_iid_match;
  wire retire_inst2_iid_match;
  wire sm_clk;
  wire sm_clk_en;
  wire wb_cur_state;
  wire wb_cur_state_wb;
  sky130_fd_sc_hd__clkinv_1 _171_ (
    .A(retire_inst2_iid_match),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _172_ (
    .A(iid[1]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _173_ (
    .A(iid[3]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _174_ (
    .A(iid[0]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _175_ (
    .A(rob_pst_retire_inst0_iid_updt_val[4]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _176_ (
    .A(iid[6]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _177_ (
    .A(iid[2]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _178_ (
    .A(iid[5]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _179_ (
    .A(rob_pst_retire_inst2_iid_updt_val[2]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__or3_1 _180_ (
    .A(lifecycle_cur_state[1]),
    .B(lifecycle_cur_state[0]),
    .C(lifecycle_cur_state[2]),
    .X(_033_)
  );
  sky130_fd_sc_hd__nand2b_1 _181_ (
    .A_N(lifecycle_cur_state[4]),
    .B(lifecycle_cur_state[3]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _182_ (
    .A(_033_),
    .SLEEP(_034_),
    .X(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(rtu_yy_xx_flush),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _184_ (
    .A(ifu_xx_sync_reset),
    .B(x_release_vld),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a222oi_1 _185_ (
    .A1(retire_pst_wb_retire_inst1_preg_vld),
    .A2(retire_inst1_iid_match),
    .B1(retire_pst_wb_retire_inst0_preg_vld),
    .B2(retire_inst0_iid_match),
    .C1(retire_pst_wb_retire_inst2_preg_vld),
    .C2(retire_inst2_iid_match),
    .Y(_038_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _186_ (
    .A(lifecycle_cur_state[4]),
    .SLEEP(lifecycle_cur_state[3]),
    .X(_039_)
  );
  sky130_fd_sc_hd__or3b_1 _187_ (
    .A(lifecycle_cur_state[1]),
    .B(lifecycle_cur_state[0]),
    .C_N(lifecycle_cur_state[2]),
    .X(_040_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _188_ (
    .A(_039_),
    .SLEEP(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__o22ai_1 _189_ (
    .A1(_033_),
    .A2(_034_),
    .B1(_039_),
    .B2(_040_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _190_ (
    .A1(rtu_yy_xx_flush),
    .A2(_038_),
    .B1(_035_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a32o_1 _191_ (
    .A1(_037_),
    .A2(_042_),
    .A3(_043_),
    .B1(ifu_xx_sync_reset),
    .B2(x_reset_mapped),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__nor3_1 _192_ (
    .A(lifecycle_cur_state[4]),
    .B(lifecycle_cur_state[2]),
    .C(lifecycle_cur_state[3]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand4b_1 _193_ (
    .A_N(lifecycle_cur_state[1]),
    .B(lifecycle_cur_state[0]),
    .C(x_dealloc_vld),
    .D(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3b_1 _194_ (
    .A_N(lifecycle_cur_state[0]),
    .B(_044_),
    .C(lifecycle_cur_state[1]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor4_1 _195_ (
    .A(x_create_vld[0]),
    .B(x_create_vld[1]),
    .C(x_create_vld[2]),
    .D(x_create_vld[3]),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2b_1 _196_ (
    .A_N(_046_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a211oi_1 _197_ (
    .A1(_045_),
    .A2(_048_),
    .B1(ifu_xx_sync_reset),
    .C1(rtu_yy_xx_flush),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(_046_),
    .B(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _199_ (
    .A(x_release_vld),
    .B(_041_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _200_ (
    .A1(_038_),
    .A2(_050_),
    .B1(_049_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor3_1 _201_ (
    .A(ifu_xx_sync_reset),
    .B(rtu_yy_xx_flush),
    .C(_051_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__and2_0 _202_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[30]),
    .X(x_dreg[30])
  );
  sky130_fd_sc_hd__and2_0 _203_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[29]),
    .X(x_dreg[29])
  );
  sky130_fd_sc_hd__and2_0 _204_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[28]),
    .X(x_dreg[28])
  );
  sky130_fd_sc_hd__and2_0 _205_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[27]),
    .X(x_dreg[27])
  );
  sky130_fd_sc_hd__and2_0 _206_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[26]),
    .X(x_dreg[26])
  );
  sky130_fd_sc_hd__and2_0 _207_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[25]),
    .X(x_dreg[25])
  );
  sky130_fd_sc_hd__and2_0 _208_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[24]),
    .X(x_dreg[24])
  );
  sky130_fd_sc_hd__and2_0 _209_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[23]),
    .X(x_dreg[23])
  );
  sky130_fd_sc_hd__and2_0 _210_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[22]),
    .X(x_dreg[22])
  );
  sky130_fd_sc_hd__and2_0 _211_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[21]),
    .X(x_dreg[21])
  );
  sky130_fd_sc_hd__and2_0 _212_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[20]),
    .X(x_dreg[20])
  );
  sky130_fd_sc_hd__and2_0 _213_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[19]),
    .X(x_dreg[19])
  );
  sky130_fd_sc_hd__and2_0 _214_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[18]),
    .X(x_dreg[18])
  );
  sky130_fd_sc_hd__and2_0 _215_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[17]),
    .X(x_dreg[17])
  );
  sky130_fd_sc_hd__and2_0 _216_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[16]),
    .X(x_dreg[16])
  );
  sky130_fd_sc_hd__and2_0 _217_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[15]),
    .X(x_dreg[15])
  );
  sky130_fd_sc_hd__and2_0 _218_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[14]),
    .X(x_dreg[14])
  );
  sky130_fd_sc_hd__and2_0 _219_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[13]),
    .X(x_dreg[13])
  );
  sky130_fd_sc_hd__and2_0 _220_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[12]),
    .X(x_dreg[12])
  );
  sky130_fd_sc_hd__and2_0 _221_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[11]),
    .X(x_dreg[11])
  );
  sky130_fd_sc_hd__and2_0 _222_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[10]),
    .X(x_dreg[10])
  );
  sky130_fd_sc_hd__and2_0 _223_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[9]),
    .X(x_dreg[9])
  );
  sky130_fd_sc_hd__and2_0 _224_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[8]),
    .X(x_dreg[8])
  );
  sky130_fd_sc_hd__and2_0 _225_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[7]),
    .X(x_dreg[7])
  );
  sky130_fd_sc_hd__and2_0 _226_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[6]),
    .X(x_dreg[6])
  );
  sky130_fd_sc_hd__and2_0 _227_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[5]),
    .X(x_dreg[5])
  );
  sky130_fd_sc_hd__and2_0 _228_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[4]),
    .X(x_dreg[4])
  );
  sky130_fd_sc_hd__and2_0 _229_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[3]),
    .X(x_dreg[3])
  );
  sky130_fd_sc_hd__and2_0 _230_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[2]),
    .X(x_dreg[2])
  );
  sky130_fd_sc_hd__and2_0 _231_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[1]),
    .X(x_dreg[1])
  );
  sky130_fd_sc_hd__and2_0 _232_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[0]),
    .X(x_dreg[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _233_ (
    .A(lifecycle_cur_state[2]),
    .SLEEP(_038_),
    .X(_052_)
  );
  sky130_fd_sc_hd__and2_0 _234_ (
    .A(rel_preg_expand[94]),
    .B(_052_),
    .X(x_rel_preg_expand[94])
  );
  sky130_fd_sc_hd__and2_0 _235_ (
    .A(rel_preg_expand[93]),
    .B(_052_),
    .X(x_rel_preg_expand[93])
  );
  sky130_fd_sc_hd__and2_0 _236_ (
    .A(rel_preg_expand[92]),
    .B(_052_),
    .X(x_rel_preg_expand[92])
  );
  sky130_fd_sc_hd__and2_0 _237_ (
    .A(rel_preg_expand[91]),
    .B(_052_),
    .X(x_rel_preg_expand[91])
  );
  sky130_fd_sc_hd__and2_0 _238_ (
    .A(rel_preg_expand[90]),
    .B(_052_),
    .X(x_rel_preg_expand[90])
  );
  sky130_fd_sc_hd__and2_0 _239_ (
    .A(rel_preg_expand[89]),
    .B(_052_),
    .X(x_rel_preg_expand[89])
  );
  sky130_fd_sc_hd__and2_0 _240_ (
    .A(rel_preg_expand[88]),
    .B(_052_),
    .X(x_rel_preg_expand[88])
  );
  sky130_fd_sc_hd__and2_0 _241_ (
    .A(rel_preg_expand[87]),
    .B(_052_),
    .X(x_rel_preg_expand[87])
  );
  sky130_fd_sc_hd__and2_0 _242_ (
    .A(rel_preg_expand[86]),
    .B(_052_),
    .X(x_rel_preg_expand[86])
  );
  sky130_fd_sc_hd__and2_0 _243_ (
    .A(rel_preg_expand[85]),
    .B(_052_),
    .X(x_rel_preg_expand[85])
  );
  sky130_fd_sc_hd__and2_0 _244_ (
    .A(rel_preg_expand[84]),
    .B(_052_),
    .X(x_rel_preg_expand[84])
  );
  sky130_fd_sc_hd__and2_0 _245_ (
    .A(rel_preg_expand[83]),
    .B(_052_),
    .X(x_rel_preg_expand[83])
  );
  sky130_fd_sc_hd__and2_0 _246_ (
    .A(rel_preg_expand[82]),
    .B(_052_),
    .X(x_rel_preg_expand[82])
  );
  sky130_fd_sc_hd__and2_0 _247_ (
    .A(rel_preg_expand[81]),
    .B(_052_),
    .X(x_rel_preg_expand[81])
  );
  sky130_fd_sc_hd__and2_0 _248_ (
    .A(rel_preg_expand[80]),
    .B(_052_),
    .X(x_rel_preg_expand[80])
  );
  sky130_fd_sc_hd__and2_0 _249_ (
    .A(rel_preg_expand[79]),
    .B(_052_),
    .X(x_rel_preg_expand[79])
  );
  sky130_fd_sc_hd__and2_0 _250_ (
    .A(rel_preg_expand[78]),
    .B(_052_),
    .X(x_rel_preg_expand[78])
  );
  sky130_fd_sc_hd__and2_0 _251_ (
    .A(rel_preg_expand[77]),
    .B(_052_),
    .X(x_rel_preg_expand[77])
  );
  sky130_fd_sc_hd__and2_0 _252_ (
    .A(rel_preg_expand[76]),
    .B(_052_),
    .X(x_rel_preg_expand[76])
  );
  sky130_fd_sc_hd__and2_0 _253_ (
    .A(rel_preg_expand[75]),
    .B(_052_),
    .X(x_rel_preg_expand[75])
  );
  sky130_fd_sc_hd__and2_0 _254_ (
    .A(rel_preg_expand[74]),
    .B(_052_),
    .X(x_rel_preg_expand[74])
  );
  sky130_fd_sc_hd__and2_0 _255_ (
    .A(rel_preg_expand[73]),
    .B(_052_),
    .X(x_rel_preg_expand[73])
  );
  sky130_fd_sc_hd__and2_0 _256_ (
    .A(rel_preg_expand[72]),
    .B(_052_),
    .X(x_rel_preg_expand[72])
  );
  sky130_fd_sc_hd__and2_0 _257_ (
    .A(rel_preg_expand[71]),
    .B(_052_),
    .X(x_rel_preg_expand[71])
  );
  sky130_fd_sc_hd__and2_0 _258_ (
    .A(rel_preg_expand[70]),
    .B(_052_),
    .X(x_rel_preg_expand[70])
  );
  sky130_fd_sc_hd__and2_0 _259_ (
    .A(rel_preg_expand[69]),
    .B(_052_),
    .X(x_rel_preg_expand[69])
  );
  sky130_fd_sc_hd__and2_0 _260_ (
    .A(rel_preg_expand[68]),
    .B(_052_),
    .X(x_rel_preg_expand[68])
  );
  sky130_fd_sc_hd__and2_0 _261_ (
    .A(rel_preg_expand[67]),
    .B(_052_),
    .X(x_rel_preg_expand[67])
  );
  sky130_fd_sc_hd__and2_0 _262_ (
    .A(rel_preg_expand[66]),
    .B(_052_),
    .X(x_rel_preg_expand[66])
  );
  sky130_fd_sc_hd__and2_0 _263_ (
    .A(rel_preg_expand[65]),
    .B(_052_),
    .X(x_rel_preg_expand[65])
  );
  sky130_fd_sc_hd__and2_0 _264_ (
    .A(rel_preg_expand[64]),
    .B(_052_),
    .X(x_rel_preg_expand[64])
  );
  sky130_fd_sc_hd__and2_0 _265_ (
    .A(rel_preg_expand[63]),
    .B(_052_),
    .X(x_rel_preg_expand[63])
  );
  sky130_fd_sc_hd__and2_0 _266_ (
    .A(rel_preg_expand[62]),
    .B(_052_),
    .X(x_rel_preg_expand[62])
  );
  sky130_fd_sc_hd__and2_0 _267_ (
    .A(rel_preg_expand[61]),
    .B(_052_),
    .X(x_rel_preg_expand[61])
  );
  sky130_fd_sc_hd__and2_0 _268_ (
    .A(rel_preg_expand[60]),
    .B(_052_),
    .X(x_rel_preg_expand[60])
  );
  sky130_fd_sc_hd__and2_0 _269_ (
    .A(rel_preg_expand[59]),
    .B(_052_),
    .X(x_rel_preg_expand[59])
  );
  sky130_fd_sc_hd__and2_0 _270_ (
    .A(rel_preg_expand[58]),
    .B(_052_),
    .X(x_rel_preg_expand[58])
  );
  sky130_fd_sc_hd__and2_0 _271_ (
    .A(rel_preg_expand[57]),
    .B(_052_),
    .X(x_rel_preg_expand[57])
  );
  sky130_fd_sc_hd__and2_0 _272_ (
    .A(rel_preg_expand[56]),
    .B(_052_),
    .X(x_rel_preg_expand[56])
  );
  sky130_fd_sc_hd__and2_0 _273_ (
    .A(rel_preg_expand[55]),
    .B(_052_),
    .X(x_rel_preg_expand[55])
  );
  sky130_fd_sc_hd__and2_0 _274_ (
    .A(rel_preg_expand[54]),
    .B(_052_),
    .X(x_rel_preg_expand[54])
  );
  sky130_fd_sc_hd__and2_0 _275_ (
    .A(rel_preg_expand[53]),
    .B(_052_),
    .X(x_rel_preg_expand[53])
  );
  sky130_fd_sc_hd__and2_0 _276_ (
    .A(rel_preg_expand[52]),
    .B(_052_),
    .X(x_rel_preg_expand[52])
  );
  sky130_fd_sc_hd__and2_0 _277_ (
    .A(rel_preg_expand[51]),
    .B(_052_),
    .X(x_rel_preg_expand[51])
  );
  sky130_fd_sc_hd__and2_0 _278_ (
    .A(rel_preg_expand[50]),
    .B(_052_),
    .X(x_rel_preg_expand[50])
  );
  sky130_fd_sc_hd__and2_0 _279_ (
    .A(rel_preg_expand[49]),
    .B(_052_),
    .X(x_rel_preg_expand[49])
  );
  sky130_fd_sc_hd__and2_0 _280_ (
    .A(rel_preg_expand[48]),
    .B(_052_),
    .X(x_rel_preg_expand[48])
  );
  sky130_fd_sc_hd__and2_0 _281_ (
    .A(rel_preg_expand[47]),
    .B(_052_),
    .X(x_rel_preg_expand[47])
  );
  sky130_fd_sc_hd__and2_0 _282_ (
    .A(rel_preg_expand[46]),
    .B(_052_),
    .X(x_rel_preg_expand[46])
  );
  sky130_fd_sc_hd__and2_0 _283_ (
    .A(rel_preg_expand[45]),
    .B(_052_),
    .X(x_rel_preg_expand[45])
  );
  sky130_fd_sc_hd__and2_0 _284_ (
    .A(rel_preg_expand[44]),
    .B(_052_),
    .X(x_rel_preg_expand[44])
  );
  sky130_fd_sc_hd__and2_0 _285_ (
    .A(rel_preg_expand[43]),
    .B(_052_),
    .X(x_rel_preg_expand[43])
  );
  sky130_fd_sc_hd__and2_0 _286_ (
    .A(rel_preg_expand[42]),
    .B(_052_),
    .X(x_rel_preg_expand[42])
  );
  sky130_fd_sc_hd__and2_0 _287_ (
    .A(rel_preg_expand[41]),
    .B(_052_),
    .X(x_rel_preg_expand[41])
  );
  sky130_fd_sc_hd__and2_0 _288_ (
    .A(rel_preg_expand[40]),
    .B(_052_),
    .X(x_rel_preg_expand[40])
  );
  sky130_fd_sc_hd__and2_0 _289_ (
    .A(rel_preg_expand[39]),
    .B(_052_),
    .X(x_rel_preg_expand[39])
  );
  sky130_fd_sc_hd__and2_0 _290_ (
    .A(rel_preg_expand[38]),
    .B(_052_),
    .X(x_rel_preg_expand[38])
  );
  sky130_fd_sc_hd__and2_0 _291_ (
    .A(rel_preg_expand[37]),
    .B(_052_),
    .X(x_rel_preg_expand[37])
  );
  sky130_fd_sc_hd__and2_0 _292_ (
    .A(rel_preg_expand[36]),
    .B(_052_),
    .X(x_rel_preg_expand[36])
  );
  sky130_fd_sc_hd__and2_0 _293_ (
    .A(rel_preg_expand[35]),
    .B(_052_),
    .X(x_rel_preg_expand[35])
  );
  sky130_fd_sc_hd__and2_0 _294_ (
    .A(rel_preg_expand[34]),
    .B(_052_),
    .X(x_rel_preg_expand[34])
  );
  sky130_fd_sc_hd__and2_0 _295_ (
    .A(rel_preg_expand[33]),
    .B(_052_),
    .X(x_rel_preg_expand[33])
  );
  sky130_fd_sc_hd__and2_0 _296_ (
    .A(rel_preg_expand[32]),
    .B(_052_),
    .X(x_rel_preg_expand[32])
  );
  sky130_fd_sc_hd__and2_0 _297_ (
    .A(rel_preg_expand[31]),
    .B(_052_),
    .X(x_rel_preg_expand[31])
  );
  sky130_fd_sc_hd__and2_0 _298_ (
    .A(rel_preg_expand[30]),
    .B(_052_),
    .X(x_rel_preg_expand[30])
  );
  sky130_fd_sc_hd__and2_0 _299_ (
    .A(rel_preg_expand[29]),
    .B(_052_),
    .X(x_rel_preg_expand[29])
  );
  sky130_fd_sc_hd__and2_0 _300_ (
    .A(rel_preg_expand[28]),
    .B(_052_),
    .X(x_rel_preg_expand[28])
  );
  sky130_fd_sc_hd__and2_0 _301_ (
    .A(rel_preg_expand[27]),
    .B(_052_),
    .X(x_rel_preg_expand[27])
  );
  sky130_fd_sc_hd__and2_0 _302_ (
    .A(rel_preg_expand[26]),
    .B(_052_),
    .X(x_rel_preg_expand[26])
  );
  sky130_fd_sc_hd__and2_0 _303_ (
    .A(rel_preg_expand[25]),
    .B(_052_),
    .X(x_rel_preg_expand[25])
  );
  sky130_fd_sc_hd__and2_0 _304_ (
    .A(rel_preg_expand[24]),
    .B(_052_),
    .X(x_rel_preg_expand[24])
  );
  sky130_fd_sc_hd__and2_0 _305_ (
    .A(rel_preg_expand[23]),
    .B(_052_),
    .X(x_rel_preg_expand[23])
  );
  sky130_fd_sc_hd__and2_0 _306_ (
    .A(rel_preg_expand[22]),
    .B(_052_),
    .X(x_rel_preg_expand[22])
  );
  sky130_fd_sc_hd__and2_0 _307_ (
    .A(rel_preg_expand[21]),
    .B(_052_),
    .X(x_rel_preg_expand[21])
  );
  sky130_fd_sc_hd__and2_0 _308_ (
    .A(rel_preg_expand[20]),
    .B(_052_),
    .X(x_rel_preg_expand[20])
  );
  sky130_fd_sc_hd__and2_0 _309_ (
    .A(rel_preg_expand[19]),
    .B(_052_),
    .X(x_rel_preg_expand[19])
  );
  sky130_fd_sc_hd__and2_0 _310_ (
    .A(rel_preg_expand[18]),
    .B(_052_),
    .X(x_rel_preg_expand[18])
  );
  sky130_fd_sc_hd__and2_0 _311_ (
    .A(rel_preg_expand[17]),
    .B(_052_),
    .X(x_rel_preg_expand[17])
  );
  sky130_fd_sc_hd__and2_0 _312_ (
    .A(rel_preg_expand[16]),
    .B(_052_),
    .X(x_rel_preg_expand[16])
  );
  sky130_fd_sc_hd__and2_0 _313_ (
    .A(rel_preg_expand[15]),
    .B(_052_),
    .X(x_rel_preg_expand[15])
  );
  sky130_fd_sc_hd__and2_0 _314_ (
    .A(rel_preg_expand[14]),
    .B(_052_),
    .X(x_rel_preg_expand[14])
  );
  sky130_fd_sc_hd__and2_0 _315_ (
    .A(rel_preg_expand[13]),
    .B(_052_),
    .X(x_rel_preg_expand[13])
  );
  sky130_fd_sc_hd__and2_0 _316_ (
    .A(rel_preg_expand[12]),
    .B(_052_),
    .X(x_rel_preg_expand[12])
  );
  sky130_fd_sc_hd__and2_0 _317_ (
    .A(rel_preg_expand[11]),
    .B(_052_),
    .X(x_rel_preg_expand[11])
  );
  sky130_fd_sc_hd__and2_0 _318_ (
    .A(rel_preg_expand[10]),
    .B(_052_),
    .X(x_rel_preg_expand[10])
  );
  sky130_fd_sc_hd__and2_0 _319_ (
    .A(rel_preg_expand[9]),
    .B(_052_),
    .X(x_rel_preg_expand[9])
  );
  sky130_fd_sc_hd__and2_0 _320_ (
    .A(rel_preg_expand[8]),
    .B(_052_),
    .X(x_rel_preg_expand[8])
  );
  sky130_fd_sc_hd__and2_0 _321_ (
    .A(rel_preg_expand[7]),
    .B(_052_),
    .X(x_rel_preg_expand[7])
  );
  sky130_fd_sc_hd__and2_0 _322_ (
    .A(rel_preg_expand[6]),
    .B(_052_),
    .X(x_rel_preg_expand[6])
  );
  sky130_fd_sc_hd__and2_0 _323_ (
    .A(rel_preg_expand[5]),
    .B(_052_),
    .X(x_rel_preg_expand[5])
  );
  sky130_fd_sc_hd__and2_0 _324_ (
    .A(rel_preg_expand[4]),
    .B(_052_),
    .X(x_rel_preg_expand[4])
  );
  sky130_fd_sc_hd__and2_0 _325_ (
    .A(rel_preg_expand[3]),
    .B(_052_),
    .X(x_rel_preg_expand[3])
  );
  sky130_fd_sc_hd__and2_0 _326_ (
    .A(rel_preg_expand[2]),
    .B(_052_),
    .X(x_rel_preg_expand[2])
  );
  sky130_fd_sc_hd__and2_0 _327_ (
    .A(rel_preg_expand[1]),
    .B(_052_),
    .X(x_rel_preg_expand[1])
  );
  sky130_fd_sc_hd__and2_0 _328_ (
    .A(rel_preg_expand[0]),
    .B(_052_),
    .X(x_rel_preg_expand[0])
  );
  sky130_fd_sc_hd__nor3b_1 _329_ (
    .A(lifecycle_cur_state[3]),
    .B(_033_),
    .C_N(lifecycle_cur_state[4]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a21o_1 _330_ (
    .A1(x_release_vld),
    .A2(_042_),
    .B1(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _331_ (
    .A(wb_cur_state),
    .SLEEP(x_dealloc_mask),
    .X(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _332_ (
    .A(ifu_xx_sync_reset),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o211a_1 _333_ (
    .A1(_036_),
    .A2(_053_),
    .B1(_054_),
    .C1(_056_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _334_ (
    .A(_047_),
    .SLEEP(ifu_xx_sync_reset),
    .X(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _335_ (
    .A(_057_),
    .Y(alloc_clk_en)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(lifecycle_cur_state[0]),
    .B(wb_cur_state),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21ai_0 _337_ (
    .A1(x_wb_vld),
    .A2(wb_cur_state),
    .B1(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a21oi_1 _338_ (
    .A1(x_reset_mapped),
    .A2(ifu_xx_sync_reset),
    .B1(retire_pst_async_flush),
    .Y(_060_)
  );
  sky130_fd_sc_hd__o21ai_0 _339_ (
    .A1(alloc_clk_en),
    .A2(_059_),
    .B1(_060_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21bai_1 _340_ (
    .A1(_039_),
    .A2(_052_),
    .B1_N(wb_cur_state),
    .Y(x_retired_released_wb)
  );
  sky130_fd_sc_hd__and2_0 _341_ (
    .A(lifecycle_cur_state[3]),
    .B(dst_reg_expand[31]),
    .X(x_dreg[31])
  );
  sky130_fd_sc_hd__and2_0 _342_ (
    .A(rel_preg_expand[95]),
    .B(_052_),
    .X(x_rel_preg_expand[95])
  );
  sky130_fd_sc_hd__nand2_1 _343_ (
    .A(_041_),
    .B(_046_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _344_ (
    .A1(rtu_yy_xx_flush),
    .A2(_045_),
    .B1(_046_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__or3_1 _345_ (
    .A(_042_),
    .B(_053_),
    .C(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__a221oi_1 _346_ (
    .A1(_054_),
    .A2(_055_),
    .B1(_061_),
    .B2(rtu_yy_xx_flush),
    .C1(ifu_xx_sync_reset),
    .Y(_064_)
  );
  sky130_fd_sc_hd__a22oi_1 _347_ (
    .A1(x_reset_mapped),
    .A2(ifu_xx_sync_reset),
    .B1(_063_),
    .B2(_064_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__o31ai_1 _348_ (
    .A1(rob_pst_retire_inst1_gateclk_vld),
    .A2(rob_pst_retire_inst2_gateclk_vld),
    .A3(rob_pst_retire_inst0_gateclk_vld),
    .B1(lifecycle_cur_state[2]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _349_ (
    .A1(wb_cur_state),
    .A2(dealloc_vld_for_gateclk),
    .B1(lifecycle_cur_state[0]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a21oi_1 _350_ (
    .A1(lifecycle_cur_state[4]),
    .A2(wb_cur_state),
    .B1(x_wb_vld),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor3_1 _351_ (
    .A(ifu_xx_sync_reset),
    .B(rtu_yy_xx_flush),
    .C(retire_pst_async_flush),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand4_1 _352_ (
    .A(_065_),
    .B(_066_),
    .C(_067_),
    .D(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor3_1 _353_ (
    .A(retire_pst_wb_retire_inst1_preg_vld),
    .B(retire_pst_wb_retire_inst0_preg_vld),
    .C(retire_pst_wb_retire_inst2_preg_vld),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(_035_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__or4_1 _355_ (
    .A(_049_),
    .B(_052_),
    .C(_069_),
    .D(_071_),
    .X(sm_clk_en)
  );
  sky130_fd_sc_hd__nor2_1 _356_ (
    .A(ifu_xx_sync_reset),
    .B(_047_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor4b_1 _357_ (
    .A(x_create_vld[0]),
    .B(x_create_vld[1]),
    .C(x_create_vld[3]),
    .D_N(x_create_vld[2]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor4b_1 _358_ (
    .A(x_create_vld[0]),
    .B(x_create_vld[1]),
    .C(x_create_vld[2]),
    .D_N(x_create_vld[3]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor4b_1 _359_ (
    .A(x_create_vld[0]),
    .B(x_create_vld[2]),
    .C(x_create_vld[3]),
    .D_N(x_create_vld[1]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor3_1 _360_ (
    .A(_073_),
    .B(_074_),
    .C(_075_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(idu_rtu_pst_dis_inst3_preg_iid[2]),
    .B(_074_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a222oi_1 _362_ (
    .A1(idu_rtu_pst_dis_inst2_preg_iid[2]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_preg_iid[2]),
    .C1(idu_rtu_pst_dis_inst0_preg_iid[2]),
    .C2(_076_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _363_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a22o_1 _364_ (
    .A1(iid[2]),
    .A2(_057_),
    .B1(_072_),
    .B2(_079_),
    .X(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(idu_rtu_pst_dis_inst2_preg_iid[6]),
    .B(_073_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__a222oi_1 _366_ (
    .A1(idu_rtu_pst_dis_inst3_preg_iid[6]),
    .A2(_074_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_preg_iid[6]),
    .C1(_076_),
    .C2(idu_rtu_pst_dis_inst0_preg_iid[6]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _367_ (
    .A(_080_),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a22o_1 _368_ (
    .A1(iid[6]),
    .A2(_057_),
    .B1(_072_),
    .B2(_082_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _369_ (
    .A(dst_reg[4]),
    .B(_057_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a22o_1 _370_ (
    .A1(idu_rtu_pst_dis_inst3_dst_reg[4]),
    .A2(_074_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_dst_reg[4]),
    .X(_084_)
  );
  sky130_fd_sc_hd__a221o_1 _371_ (
    .A1(idu_rtu_pst_dis_inst2_dst_reg[4]),
    .A2(_073_),
    .B1(_076_),
    .B2(idu_rtu_pst_dis_inst0_dst_reg[4]),
    .C1(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2i_1 _372_ (
    .A0(_085_),
    .A1(x_reset_dst_reg[4]),
    .S(ifu_xx_sync_reset),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _373_ (
    .A1(_057_),
    .A2(_086_),
    .B1(_083_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _374_ (
    .A(idu_rtu_pst_dis_inst2_rel_preg[6]),
    .B(_073_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a222oi_1 _375_ (
    .A1(idu_rtu_pst_dis_inst3_rel_preg[6]),
    .A2(_074_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_rel_preg[6]),
    .C1(_076_),
    .C2(idu_rtu_pst_dis_inst0_rel_preg[6]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(_087_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a22o_1 _377_ (
    .A1(rel_preg[6]),
    .A2(_057_),
    .B1(_072_),
    .B2(_089_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(idu_rtu_pst_dis_inst0_preg_iid[1]),
    .B(_076_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__a222oi_1 _379_ (
    .A1(idu_rtu_pst_dis_inst2_preg_iid[1]),
    .A2(_073_),
    .B1(_074_),
    .B2(idu_rtu_pst_dis_inst3_preg_iid[1]),
    .C1(_075_),
    .C2(idu_rtu_pst_dis_inst1_preg_iid[1]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand2_1 _380_ (
    .A(_090_),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a22o_1 _381_ (
    .A1(iid[1]),
    .A2(_057_),
    .B1(_072_),
    .B2(_092_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(idu_rtu_pst_dis_inst3_preg_iid[0]),
    .B(_074_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a222oi_1 _383_ (
    .A1(idu_rtu_pst_dis_inst2_preg_iid[0]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_preg_iid[0]),
    .C1(idu_rtu_pst_dis_inst0_preg_iid[0]),
    .C2(_076_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _384_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a22o_1 _385_ (
    .A1(iid[0]),
    .A2(_057_),
    .B1(_072_),
    .B2(_095_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _386_ (
    .A(ifu_xx_sync_reset),
    .B(rob_pst_retire_inst1_gateclk_vld),
    .Y(_096_)
  );
  sky130_fd_sc_hd__o22ai_1 _387_ (
    .A1(_031_),
    .A2(rob_pst_retire_inst1_iid_updt_val[5]),
    .B1(rob_pst_retire_inst1_iid_updt_val[1]),
    .B2(_025_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _388_ (
    .A(rob_pst_retire_inst1_iid_updt_val[2]),
    .SLEEP(iid[2]),
    .X(_098_)
  );
  sky130_fd_sc_hd__xor2_1 _389_ (
    .A(iid[0]),
    .B(rob_pst_retire_inst1_iid_updt_val[0]),
    .X(_099_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _390_ (
    .A(lifecycle_cur_state[2]),
    .SLEEP(ifu_xx_sync_reset),
    .X(_100_)
  );
  sky130_fd_sc_hd__xor2_1 _391_ (
    .A(iid[3]),
    .B(rob_pst_retire_inst1_iid_updt_val[3]),
    .X(_101_)
  );
  sky130_fd_sc_hd__xor2_1 _392_ (
    .A(iid[6]),
    .B(rob_pst_retire_inst1_iid_updt_val[6]),
    .X(_102_)
  );
  sky130_fd_sc_hd__a2111oi_0 _393_ (
    .A1(_031_),
    .A2(rob_pst_retire_inst1_iid_updt_val[5]),
    .B1(_098_),
    .C1(_101_),
    .D1(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__xnor2_1 _394_ (
    .A(iid[4]),
    .B(rob_pst_retire_inst1_iid_updt_val[4]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand3_1 _395_ (
    .A(rob_pst_retire_inst1_gateclk_vld),
    .B(_100_),
    .C(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _396_ (
    .A1_N(_025_),
    .A2_N(rob_pst_retire_inst1_iid_updt_val[1]),
    .B1(rob_pst_retire_inst1_iid_updt_val[2]),
    .B2(_030_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nor4_1 _397_ (
    .A(_097_),
    .B(_099_),
    .C(_105_),
    .D(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a22o_1 _398_ (
    .A1(retire_inst1_iid_match),
    .A2(_096_),
    .B1(_103_),
    .B2(_107_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(idu_rtu_pst_dis_inst1_rel_preg[5]),
    .B(_075_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a222oi_1 _400_ (
    .A1(idu_rtu_pst_dis_inst2_rel_preg[5]),
    .A2(_073_),
    .B1(_074_),
    .B2(idu_rtu_pst_dis_inst3_rel_preg[5]),
    .C1(_076_),
    .C2(idu_rtu_pst_dis_inst0_rel_preg[5]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _401_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a22o_1 _402_ (
    .A1(rel_preg[5]),
    .A2(_057_),
    .B1(_072_),
    .B2(_110_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _403_ (
    .A(idu_rtu_pst_dis_inst1_rel_preg[4]),
    .B(_075_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a222oi_1 _404_ (
    .A1(idu_rtu_pst_dis_inst2_rel_preg[4]),
    .A2(_073_),
    .B1(_074_),
    .B2(idu_rtu_pst_dis_inst3_rel_preg[4]),
    .C1(idu_rtu_pst_dis_inst0_rel_preg[4]),
    .C2(_076_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _405_ (
    .A(_111_),
    .B(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a22o_1 _406_ (
    .A1(rel_preg[4]),
    .A2(_057_),
    .B1(_072_),
    .B2(_113_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(idu_rtu_pst_dis_inst2_rel_preg[3]),
    .B(_073_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a222oi_1 _408_ (
    .A1(idu_rtu_pst_dis_inst3_rel_preg[3]),
    .A2(_074_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_rel_preg[3]),
    .C1(idu_rtu_pst_dis_inst0_rel_preg[3]),
    .C2(_076_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _409_ (
    .A(_114_),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a22o_1 _410_ (
    .A1(rel_preg[3]),
    .A2(_057_),
    .B1(_072_),
    .B2(_116_),
    .X(_011_)
  );
  sky130_fd_sc_hd__nor3b_1 _411_ (
    .A(ifu_xx_sync_reset),
    .B(rob_pst_retire_inst0_gateclk_vld),
    .C_N(retire_inst0_iid_match),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _412_ (
    .A(rob_pst_retire_inst0_iid_updt_val[6]),
    .B(_029_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o22ai_1 _413_ (
    .A1(_025_),
    .A2(rob_pst_retire_inst0_iid_updt_val[1]),
    .B1(_027_),
    .B2(rob_pst_retire_inst0_iid_updt_val[0]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__xnor2_1 _414_ (
    .A(rob_pst_retire_inst0_iid_updt_val[5]),
    .B(iid[5]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a222oi_1 _415_ (
    .A1(_025_),
    .A2(rob_pst_retire_inst0_iid_updt_val[1]),
    .B1(_027_),
    .B2(rob_pst_retire_inst0_iid_updt_val[0]),
    .C1(_028_),
    .C2(iid[4]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand4_1 _416_ (
    .A(rob_pst_retire_inst0_gateclk_vld),
    .B(_100_),
    .C(_120_),
    .D(_121_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a211oi_1 _417_ (
    .A1(rob_pst_retire_inst0_iid_updt_val[6]),
    .A2(_029_),
    .B1(_119_),
    .C1(_122_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o22ai_1 _418_ (
    .A1(_028_),
    .A2(iid[4]),
    .B1(rob_pst_retire_inst0_iid_updt_val[2]),
    .B2(_030_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__xor2_1 _419_ (
    .A(iid[3]),
    .B(rob_pst_retire_inst0_iid_updt_val[3]),
    .X(_125_)
  );
  sky130_fd_sc_hd__a2111oi_0 _420_ (
    .A1(rob_pst_retire_inst0_iid_updt_val[2]),
    .A2(_030_),
    .B1(_118_),
    .C1(_124_),
    .D1(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a21o_1 _421_ (
    .A1(_123_),
    .A2(_126_),
    .B1(_117_),
    .X(_012_)
  );
  sky130_fd_sc_hd__xor2_1 _422_ (
    .A(iid[0]),
    .B(rob_pst_retire_inst2_iid_updt_val[0]),
    .X(_127_)
  );
  sky130_fd_sc_hd__xor2_1 _423_ (
    .A(iid[5]),
    .B(rob_pst_retire_inst2_iid_updt_val[5]),
    .X(_128_)
  );
  sky130_fd_sc_hd__o22ai_1 _424_ (
    .A1(iid[2]),
    .A2(_032_),
    .B1(rob_pst_retire_inst2_iid_updt_val[3]),
    .B2(_026_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a22o_1 _425_ (
    .A1(iid[2]),
    .A2(_032_),
    .B1(rob_pst_retire_inst2_iid_updt_val[3]),
    .B2(_026_),
    .X(_130_)
  );
  sky130_fd_sc_hd__or4_1 _426_ (
    .A(_127_),
    .B(_128_),
    .C(_129_),
    .D(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__xor2_1 _427_ (
    .A(iid[1]),
    .B(rob_pst_retire_inst2_iid_updt_val[1]),
    .X(_132_)
  );
  sky130_fd_sc_hd__xor2_1 _428_ (
    .A(iid[4]),
    .B(rob_pst_retire_inst2_iid_updt_val[4]),
    .X(_133_)
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(_132_),
    .B(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__xnor2_1 _430_ (
    .A(iid[6]),
    .B(rob_pst_retire_inst2_iid_updt_val[6]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand4_1 _431_ (
    .A(rob_pst_retire_inst2_gateclk_vld),
    .B(_100_),
    .C(_134_),
    .D(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o32ai_1 _432_ (
    .A1(ifu_xx_sync_reset),
    .A2(_024_),
    .A3(rob_pst_retire_inst2_gateclk_vld),
    .B1(_131_),
    .B2(_136_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _433_ (
    .A(idu_rtu_pst_dis_inst3_rel_preg[2]),
    .B(_074_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a222oi_1 _434_ (
    .A1(idu_rtu_pst_dis_inst2_rel_preg[2]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_rel_preg[2]),
    .C1(idu_rtu_pst_dis_inst0_rel_preg[2]),
    .C2(_076_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _435_ (
    .A(_137_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a22o_1 _436_ (
    .A1(rel_preg[2]),
    .A2(_057_),
    .B1(_072_),
    .B2(_139_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _437_ (
    .A(idu_rtu_pst_dis_inst3_rel_preg[1]),
    .B(_074_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a222oi_1 _438_ (
    .A1(idu_rtu_pst_dis_inst2_rel_preg[1]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_rel_preg[1]),
    .C1(idu_rtu_pst_dis_inst0_rel_preg[1]),
    .C2(_076_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(_140_),
    .B(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a22o_1 _440_ (
    .A1(rel_preg[1]),
    .A2(_057_),
    .B1(_072_),
    .B2(_142_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _441_ (
    .A(idu_rtu_pst_dis_inst3_rel_preg[0]),
    .B(_074_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a222oi_1 _442_ (
    .A1(idu_rtu_pst_dis_inst2_rel_preg[0]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_rel_preg[0]),
    .C1(_076_),
    .C2(idu_rtu_pst_dis_inst0_rel_preg[0]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _443_ (
    .A(_143_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a22o_1 _444_ (
    .A1(rel_preg[0]),
    .A2(_057_),
    .B1(_072_),
    .B2(_145_),
    .X(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(dst_reg[3]),
    .B(_057_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a22o_1 _446_ (
    .A1(idu_rtu_pst_dis_inst3_dst_reg[3]),
    .A2(_074_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_dst_reg[3]),
    .X(_147_)
  );
  sky130_fd_sc_hd__a221o_1 _447_ (
    .A1(idu_rtu_pst_dis_inst2_dst_reg[3]),
    .A2(_073_),
    .B1(_076_),
    .B2(idu_rtu_pst_dis_inst0_dst_reg[3]),
    .C1(_147_),
    .X(_148_)
  );
  sky130_fd_sc_hd__mux2i_1 _448_ (
    .A0(_148_),
    .A1(x_reset_dst_reg[3]),
    .S(ifu_xx_sync_reset),
    .Y(_149_)
  );
  sky130_fd_sc_hd__o21ai_0 _449_ (
    .A1(_057_),
    .A2(_149_),
    .B1(_146_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(dst_reg[2]),
    .B(_057_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a221o_1 _451_ (
    .A1(idu_rtu_pst_dis_inst3_dst_reg[2]),
    .A2(_074_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_dst_reg[2]),
    .C1(ifu_xx_sync_reset),
    .X(_151_)
  );
  sky130_fd_sc_hd__a221oi_1 _452_ (
    .A1(idu_rtu_pst_dis_inst2_dst_reg[2]),
    .A2(_073_),
    .B1(_076_),
    .B2(idu_rtu_pst_dis_inst0_dst_reg[2]),
    .C1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _453_ (
    .A(ifu_xx_sync_reset),
    .SLEEP(x_reset_dst_reg[2]),
    .X(_153_)
  );
  sky130_fd_sc_hd__o31ai_1 _454_ (
    .A1(_057_),
    .A2(_152_),
    .A3(_153_),
    .B1(_150_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _455_ (
    .A(dst_reg[1]),
    .B(_057_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a22o_1 _456_ (
    .A1(idu_rtu_pst_dis_inst2_dst_reg[1]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_dst_reg[1]),
    .X(_155_)
  );
  sky130_fd_sc_hd__a221o_1 _457_ (
    .A1(idu_rtu_pst_dis_inst3_dst_reg[1]),
    .A2(_074_),
    .B1(_076_),
    .B2(idu_rtu_pst_dis_inst0_dst_reg[1]),
    .C1(_155_),
    .X(_156_)
  );
  sky130_fd_sc_hd__mux2i_1 _458_ (
    .A0(_156_),
    .A1(x_reset_dst_reg[1]),
    .S(ifu_xx_sync_reset),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _459_ (
    .A1(_057_),
    .A2(_157_),
    .B1(_154_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _460_ (
    .A(dst_reg[0]),
    .B(_057_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__a221o_1 _461_ (
    .A1(idu_rtu_pst_dis_inst2_dst_reg[0]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_dst_reg[0]),
    .C1(ifu_xx_sync_reset),
    .X(_159_)
  );
  sky130_fd_sc_hd__a221oi_1 _462_ (
    .A1(idu_rtu_pst_dis_inst3_dst_reg[0]),
    .A2(_074_),
    .B1(_076_),
    .B2(idu_rtu_pst_dis_inst0_dst_reg[0]),
    .C1(_159_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _463_ (
    .A(ifu_xx_sync_reset),
    .SLEEP(x_reset_dst_reg[0]),
    .X(_161_)
  );
  sky130_fd_sc_hd__o31ai_1 _464_ (
    .A1(_057_),
    .A2(_160_),
    .A3(_161_),
    .B1(_158_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _465_ (
    .A(idu_rtu_pst_dis_inst3_preg_iid[5]),
    .B(_074_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__a222oi_1 _466_ (
    .A1(idu_rtu_pst_dis_inst2_preg_iid[5]),
    .A2(_073_),
    .B1(_075_),
    .B2(idu_rtu_pst_dis_inst1_preg_iid[5]),
    .C1(_076_),
    .C2(idu_rtu_pst_dis_inst0_preg_iid[5]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__nand2_1 _467_ (
    .A(_162_),
    .B(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a22o_1 _468_ (
    .A1(iid[5]),
    .A2(_057_),
    .B1(_072_),
    .B2(_164_),
    .X(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _469_ (
    .A(idu_rtu_pst_dis_inst1_preg_iid[4]),
    .B(_075_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__a222oi_1 _470_ (
    .A1(idu_rtu_pst_dis_inst2_preg_iid[4]),
    .A2(_073_),
    .B1(_074_),
    .B2(idu_rtu_pst_dis_inst3_preg_iid[4]),
    .C1(_076_),
    .C2(idu_rtu_pst_dis_inst0_preg_iid[4]),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _471_ (
    .A(_165_),
    .B(_166_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a22o_1 _472_ (
    .A1(iid[4]),
    .A2(_057_),
    .B1(_072_),
    .B2(_167_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _473_ (
    .A(idu_rtu_pst_dis_inst1_preg_iid[3]),
    .B(_075_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a222oi_1 _474_ (
    .A1(idu_rtu_pst_dis_inst2_preg_iid[3]),
    .A2(_073_),
    .B1(_074_),
    .B2(idu_rtu_pst_dis_inst3_preg_iid[3]),
    .C1(idu_rtu_pst_dis_inst0_preg_iid[3]),
    .C2(_076_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nand2_1 _475_ (
    .A(_168_),
    .B(_169_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__a22o_1 _476_ (
    .A1(iid[3]),
    .A2(_057_),
    .B1(_072_),
    .B2(_170_),
    .X(_023_)
  );
  sky130_fd_sc_hd__dfrtp_1 _477_ (
    .CLK(sm_clk),
    .D(_012_),
    .Q(retire_inst0_iid_match),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _478_ (
    .CLK(sm_clk),
    .D(_013_),
    .Q(retire_inst2_iid_match),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _479_ (
    .CLK(alloc_clk),
    .D(_007_),
    .Q(iid[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _480_ (
    .CLK(alloc_clk),
    .D(_006_),
    .Q(iid[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _481_ (
    .CLK(alloc_clk),
    .D(_002_),
    .Q(iid[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _482_ (
    .CLK(alloc_clk),
    .D(_023_),
    .Q(iid[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _483_ (
    .CLK(alloc_clk),
    .D(_022_),
    .Q(iid[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _484_ (
    .CLK(alloc_clk),
    .D(_021_),
    .Q(iid[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _485_ (
    .CLK(alloc_clk),
    .D(_003_),
    .Q(iid[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _486_ (
    .CLK(alloc_clk),
    .D(_020_),
    .Q(dst_reg[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _487_ (
    .CLK(alloc_clk),
    .D(_019_),
    .Q(dst_reg[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _488_ (
    .CLK(alloc_clk),
    .D(_018_),
    .Q(dst_reg[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _489_ (
    .CLK(alloc_clk),
    .D(_017_),
    .Q(dst_reg[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _490_ (
    .CLK(alloc_clk),
    .D(_004_),
    .Q(dst_reg[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _491_ (
    .CLK(alloc_clk),
    .D(_016_),
    .Q(rel_preg[0]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _492_ (
    .CLK(alloc_clk),
    .D(_015_),
    .Q(rel_preg[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _493_ (
    .CLK(alloc_clk),
    .D(_014_),
    .Q(rel_preg[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _494_ (
    .CLK(alloc_clk),
    .D(_011_),
    .Q(rel_preg[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _495_ (
    .CLK(alloc_clk),
    .D(_010_),
    .Q(rel_preg[4]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _496_ (
    .CLK(alloc_clk),
    .D(_009_),
    .Q(rel_preg[5]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _497_ (
    .CLK(alloc_clk),
    .D(_005_),
    .Q(rel_preg[6]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _498_ (
    .CLK(sm_clk),
    .D(_008_),
    .Q(retire_inst1_iid_match),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _499_ (
    .CLK(sm_clk),
    .D(_001_),
    .Q(wb_cur_state),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfstp_2 _500_ (
    .CLK(sm_clk),
    .D(_000_[0]),
    .Q(lifecycle_cur_state[0]),
    .SET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _501_ (
    .CLK(sm_clk),
    .D(_000_[1]),
    .Q(lifecycle_cur_state[1]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _502_ (
    .CLK(sm_clk),
    .D(_000_[2]),
    .Q(lifecycle_cur_state[2]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _503_ (
    .CLK(sm_clk),
    .D(_000_[3]),
    .Q(lifecycle_cur_state[3]),
    .RESET_B(cpurst_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _504_ (
    .CLK(sm_clk),
    .D(_000_[4]),
    .Q(lifecycle_cur_state[4]),
    .RESET_B(cpurst_b)
  );
  gated_clk_cell x_alloc_gated_clk (
    .clk_in(forever_cpuclk),
    .clk_out(alloc_clk),
    .external_en(1'h0),
    .global_en(cp0_yy_clk_en),
    .local_en(alloc_clk_en),
    .module_en(cp0_rtu_icg_en),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en)
  );
  ct_rtu_expand_32 x_ct_rtu_expand_32_dst_reg (
    .x_num(dst_reg),
    .x_num_expand(dst_reg_expand)
  );
  ct_rtu_expand_96 x_ct_rtu_expand_96_rel_preg (
    .x_num(rel_preg),
    .x_num_expand(rel_preg_expand)
  );
  gated_clk_cell x_sm_gated_clk (
    .clk_in(forever_cpuclk),
    .clk_out(sm_clk),
    .external_en(1'h0),
    .global_en(cp0_yy_clk_en),
    .local_en(sm_clk_en),
    .module_en(cp0_rtu_icg_en),
    .pad_yy_icg_scan_en(pad_yy_icg_scan_en)
  );
  assign reset_lifecycle_state[3:1] = { x_reset_mapped, 2'h0 };
  assign wb_cur_state_wb = wb_cur_state;
  assign reset_wb_state = x_reset_mapped;
  assign lifecycle_cur_state_retire = lifecycle_cur_state[3];
  assign lifecycle_cur_state_release = lifecycle_cur_state[4];
  assign lifecycle_cur_state_dealloc = lifecycle_cur_state[0];
  assign lifecycle_cur_state_alloc = lifecycle_cur_state[2];
  assign x_cur_state_dealloc = lifecycle_cur_state[0];
endmodule

module gated_clk_cell(clk_in, global_en, module_en, local_en, external_en, pad_yy_icg_scan_en, clk_out);
  input clk_in;
  wire clk_in;
  input global_en;
  wire global_en;
  input module_en;
  wire module_en;
  input local_en;
  wire local_en;
  input external_en;
  wire external_en;
  input pad_yy_icg_scan_en;
  wire pad_yy_icg_scan_en;
  output clk_out;
  wire clk_out;
  wire SE;
  assign SE = pad_yy_icg_scan_en;
  assign clk_out = clk_in;
endmodule
