/* Generated by Yosys 0.66+181 (git sha1 afe6b18f2, Release, Clang /usr/bin/clang++ 18.1.8) */

module ct_pmp_acc(cp0_pmp_mpp, cur_priv_mode, mmu_pmp_pa_y, pmp_mmu_flg_y, pmp_mprv_status_y, pmpaddr0_value, pmpaddr1_value, pmpaddr2_value, pmpaddr3_value, pmpaddr4_value, pmpaddr5_value, pmpaddr6_value, pmpaddr7_value, pmpcfg0_value, pmpcfg2_value);
  input [1:0] cp0_pmp_mpp;
  wire [1:0] cp0_pmp_mpp;
  input [1:0] cur_priv_mode;
  wire [1:0] cur_priv_mode;
  input [27:0] mmu_pmp_pa_y;
  wire [27:0] mmu_pmp_pa_y;
  output [3:0] pmp_mmu_flg_y;
  wire [3:0] pmp_mmu_flg_y;
  input pmp_mprv_status_y;
  wire pmp_mprv_status_y;
  input [28:0] pmpaddr0_value;
  wire [28:0] pmpaddr0_value;
  input [28:0] pmpaddr1_value;
  wire [28:0] pmpaddr1_value;
  input [28:0] pmpaddr2_value;
  wire [28:0] pmpaddr2_value;
  input [28:0] pmpaddr3_value;
  wire [28:0] pmpaddr3_value;
  input [28:0] pmpaddr4_value;
  wire [28:0] pmpaddr4_value;
  input [28:0] pmpaddr5_value;
  wire [28:0] pmpaddr5_value;
  input [28:0] pmpaddr6_value;
  wire [28:0] pmpaddr6_value;
  input [28:0] pmpaddr7_value;
  wire [28:0] pmpaddr7_value;
  input [63:0] pmpcfg0_value;
  wire [63:0] pmpcfg0_value;
  input [63:0] pmpcfg2_value;
  wire [63:0] pmpcfg2_value;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire [1:0] addr_match_mode0;
  wire [1:0] addr_match_mode1;
  wire [1:0] addr_match_mode2;
  wire [1:0] addr_match_mode3;
  wire [1:0] addr_match_mode4;
  wire [1:0] addr_match_mode5;
  wire [1:0] addr_match_mode6;
  wire [1:0] addr_match_mode7;
  wire mmu_addr_ge_bottom0;
  wire mmu_addr_ge_bottom1;
  wire mmu_addr_ge_bottom2;
  wire mmu_addr_ge_bottom3;
  wire mmu_addr_ge_bottom4;
  wire mmu_addr_ge_bottom5;
  wire mmu_addr_ge_bottom6;
  wire mmu_addr_ge_bottom7;
  wire mmu_addr_ge_upaddr0;
  wire mmu_addr_ge_upaddr1;
  wire mmu_addr_ge_upaddr2;
  wire mmu_addr_ge_upaddr3;
  wire mmu_addr_ge_upaddr4;
  wire mmu_addr_ge_upaddr5;
  wire mmu_addr_ge_upaddr6;
  wire mmu_addr_ge_upaddr7;
  wire [7:0] pmp_hit;
  wire pmp_mmu_hit0;
  wire pmp_mmu_hit1;
  wire pmp_mmu_hit2;
  wire pmp_mmu_hit3;
  wire pmp_mmu_hit4;
  wire pmp_mmu_hit5;
  wire pmp_mmu_hit6;
  wire pmp_mmu_hit7;
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(pmp_mmu_hit0),
    .B(pmp_mmu_hit1),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nor4_1 _35_ (
    .A(pmp_mmu_hit0),
    .B(pmp_mmu_hit1),
    .C(pmp_mmu_hit2),
    .D(pmp_mmu_hit3),
    .Y(_01_)
  );
  sky130_fd_sc_hd__or4_1 _36_ (
    .A(pmp_mmu_hit0),
    .B(pmp_mmu_hit1),
    .C(pmp_mmu_hit2),
    .D(pmp_mmu_hit3),
    .X(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _37_ (
    .A(pmp_mmu_hit5),
    .B(pmp_mmu_hit4),
    .Y(_03_)
  );
  sky130_fd_sc_hd__and3_1 _38_ (
    .A(pmp_mmu_hit6),
    .B(_01_),
    .C(_03_),
    .X(_04_)
  );
  sky130_fd_sc_hd__nor3b_1 _39_ (
    .A(pmp_mmu_hit4),
    .B(_02_),
    .C_N(pmp_mmu_hit5),
    .Y(_05_)
  );
  sky130_fd_sc_hd__and2_0 _40_ (
    .A(pmp_mmu_hit4),
    .B(_01_),
    .X(_06_)
  );
  sky130_fd_sc_hd__a222oi_1 _41_ (
    .A1(pmpcfg0_value[42]),
    .A2(_05_),
    .B1(_06_),
    .B2(pmpcfg0_value[34]),
    .C1(pmpcfg0_value[50]),
    .C2(_04_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _42_ (
    .A(cp0_pmp_mpp[0]),
    .B(cp0_pmp_mpp[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_1 _43_ (
    .A1(cur_priv_mode[0]),
    .A2(cur_priv_mode[1]),
    .B1(pmp_mprv_status_y),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor4_1 _44_ (
    .A(pmp_mmu_hit5),
    .B(pmp_mmu_hit4),
    .C(pmp_mmu_hit6),
    .D(_02_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a211oi_1 _45_ (
    .A1(pmp_mprv_status_y),
    .A2(_08_),
    .B1(_09_),
    .C1(pmp_mmu_hit7),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and4b_1 _47_ (
    .A_N(pmp_mmu_hit6),
    .B(pmp_mmu_hit7),
    .C(_01_),
    .D(_03_),
    .X(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _48_ (
    .A(pmpcfg0_value[58]),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor4b_1 _49_ (
    .A(pmp_mmu_hit0),
    .B(pmp_mmu_hit1),
    .C(pmp_mmu_hit2),
    .D_N(pmp_mmu_hit3),
    .Y(_15_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _50_ (
    .A(pmp_mmu_hit1),
    .SLEEP(pmp_mmu_hit0),
    .X(_16_)
  );
  sky130_fd_sc_hd__a32o_1 _51_ (
    .A1(pmp_mmu_hit2),
    .A2(pmpcfg0_value[18]),
    .A3(_00_),
    .B1(_15_),
    .B2(pmpcfg0_value[26]),
    .X(_17_)
  );
  sky130_fd_sc_hd__a221oi_1 _52_ (
    .A1(pmp_mmu_hit0),
    .A2(pmpcfg0_value[2]),
    .B1(_16_),
    .B2(pmpcfg0_value[10]),
    .C1(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nand4_1 _53_ (
    .A(_07_),
    .B(_12_),
    .C(_14_),
    .D(_18_),
    .Y(pmp_mmu_flg_y[2])
  );
  sky130_fd_sc_hd__a222oi_1 _54_ (
    .A1(pmpcfg0_value[49]),
    .A2(_04_),
    .B1(_05_),
    .B2(pmpcfg0_value[41]),
    .C1(pmpcfg0_value[33]),
    .C2(_06_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nand2_1 _55_ (
    .A(pmpcfg0_value[57]),
    .B(_13_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a32o_1 _56_ (
    .A1(pmp_mmu_hit2),
    .A2(pmpcfg0_value[17]),
    .A3(_00_),
    .B1(_15_),
    .B2(pmpcfg0_value[25]),
    .X(_21_)
  );
  sky130_fd_sc_hd__a221oi_1 _57_ (
    .A1(pmp_mmu_hit0),
    .A2(pmpcfg0_value[1]),
    .B1(_16_),
    .B2(pmpcfg0_value[9]),
    .C1(_21_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nand4_1 _58_ (
    .A(_12_),
    .B(_19_),
    .C(_20_),
    .D(_22_),
    .Y(pmp_mmu_flg_y[1])
  );
  sky130_fd_sc_hd__nand2_1 _59_ (
    .A(pmpcfg0_value[56]),
    .B(_13_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__a222oi_1 _60_ (
    .A1(pmpcfg0_value[48]),
    .A2(_04_),
    .B1(_05_),
    .B2(pmpcfg0_value[40]),
    .C1(_15_),
    .C2(pmpcfg0_value[24]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a32o_1 _61_ (
    .A1(pmp_mmu_hit4),
    .A2(pmpcfg0_value[32]),
    .A3(_01_),
    .B1(pmpcfg0_value[0]),
    .B2(pmp_mmu_hit0),
    .X(_25_)
  );
  sky130_fd_sc_hd__a32o_1 _62_ (
    .A1(pmp_mmu_hit2),
    .A2(pmpcfg0_value[16]),
    .A3(_00_),
    .B1(_16_),
    .B2(pmpcfg0_value[8]),
    .X(_26_)
  );
  sky130_fd_sc_hd__a211oi_1 _63_ (
    .A1(_10_),
    .A2(_11_),
    .B1(_25_),
    .C1(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nand3_1 _64_ (
    .A(_23_),
    .B(_24_),
    .C(_27_),
    .Y(pmp_mmu_flg_y[0])
  );
  sky130_fd_sc_hd__a22oi_1 _65_ (
    .A1(pmpcfg0_value[55]),
    .A2(_04_),
    .B1(_06_),
    .B2(pmpcfg0_value[39]),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nand3_1 _66_ (
    .A(pmp_mmu_hit2),
    .B(pmpcfg0_value[23]),
    .C(_00_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__nand2_1 _67_ (
    .A(pmp_mmu_hit0),
    .B(pmpcfg0_value[7]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a22oi_1 _68_ (
    .A1(pmpcfg0_value[31]),
    .A2(_15_),
    .B1(_16_),
    .B2(pmpcfg0_value[15]),
    .Y(_31_)
  );
  sky130_fd_sc_hd__and3_1 _69_ (
    .A(_29_),
    .B(_30_),
    .C(_31_),
    .X(_32_)
  );
  sky130_fd_sc_hd__a22oi_1 _70_ (
    .A1(pmpcfg0_value[47]),
    .A2(_05_),
    .B1(_13_),
    .B2(pmpcfg0_value[63]),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nand3_1 _71_ (
    .A(_28_),
    .B(_32_),
    .C(_33_),
    .Y(pmp_mmu_flg_y[3])
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_0 (
    .addr_match_mode_x(pmpcfg0_value[4:3]),
    .mmu_addr_ge_bottom_x(1'h1),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_bottom1),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit0),
    .pmpaddr_x_value(pmpaddr0_value)
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_1 (
    .addr_match_mode_x(pmpcfg0_value[12:11]),
    .mmu_addr_ge_bottom_x(mmu_addr_ge_bottom1),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_bottom2),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit1),
    .pmpaddr_x_value(pmpaddr1_value)
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_2 (
    .addr_match_mode_x(pmpcfg0_value[20:19]),
    .mmu_addr_ge_bottom_x(mmu_addr_ge_bottom2),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_bottom3),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit2),
    .pmpaddr_x_value(pmpaddr2_value)
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_3 (
    .addr_match_mode_x(pmpcfg0_value[28:27]),
    .mmu_addr_ge_bottom_x(mmu_addr_ge_bottom3),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_bottom4),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit3),
    .pmpaddr_x_value(pmpaddr3_value)
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_4 (
    .addr_match_mode_x(pmpcfg0_value[36:35]),
    .mmu_addr_ge_bottom_x(mmu_addr_ge_bottom4),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_bottom5),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit4),
    .pmpaddr_x_value(pmpaddr4_value)
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_5 (
    .addr_match_mode_x(pmpcfg0_value[44:43]),
    .mmu_addr_ge_bottom_x(mmu_addr_ge_bottom5),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_bottom6),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit5),
    .pmpaddr_x_value(pmpaddr5_value)
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_6 (
    .addr_match_mode_x(pmpcfg0_value[52:51]),
    .mmu_addr_ge_bottom_x(mmu_addr_ge_bottom6),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_bottom7),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit6),
    .pmpaddr_x_value(pmpaddr6_value)
  );
  ct_pmp_comp_hit x_ct_pmp_comp_hit_7 (
    .addr_match_mode_x(pmpcfg0_value[60:59]),
    .mmu_addr_ge_bottom_x(mmu_addr_ge_bottom7),
    .mmu_addr_ge_upaddr_x(mmu_addr_ge_upaddr7),
    .mmu_pmp_pa_y(mmu_pmp_pa_y),
    .pmp_mmu_hit_x(pmp_mmu_hit7),
    .pmpaddr_x_value(pmpaddr7_value)
  );
  assign pmp_hit = { pmp_mmu_hit7, pmp_mmu_hit6, pmp_mmu_hit5, pmp_mmu_hit4, pmp_mmu_hit3, pmp_mmu_hit2, pmp_mmu_hit1, pmp_mmu_hit0 };
  assign mmu_addr_ge_upaddr6 = mmu_addr_ge_bottom7;
  assign mmu_addr_ge_upaddr5 = mmu_addr_ge_bottom6;
  assign mmu_addr_ge_upaddr4 = mmu_addr_ge_bottom5;
  assign mmu_addr_ge_upaddr3 = mmu_addr_ge_bottom4;
  assign mmu_addr_ge_upaddr2 = mmu_addr_ge_bottom3;
  assign mmu_addr_ge_upaddr1 = mmu_addr_ge_bottom2;
  assign mmu_addr_ge_upaddr0 = mmu_addr_ge_bottom1;
  assign mmu_addr_ge_bottom0 = 1'h1;
  assign addr_match_mode7 = pmpcfg0_value[60:59];
  assign addr_match_mode6 = pmpcfg0_value[52:51];
  assign addr_match_mode5 = pmpcfg0_value[44:43];
  assign addr_match_mode4 = pmpcfg0_value[36:35];
  assign addr_match_mode3 = pmpcfg0_value[28:27];
  assign addr_match_mode2 = pmpcfg0_value[20:19];
  assign addr_match_mode1 = pmpcfg0_value[12:11];
  assign addr_match_mode0 = pmpcfg0_value[4:3];
endmodule

module ct_pmp_comp_hit(addr_match_mode_x, mmu_addr_ge_bottom_x, mmu_addr_ge_upaddr_x, mmu_pmp_pa_y, pmp_mmu_hit_x, pmpaddr_x_value);
  input [1:0] addr_match_mode_x;
  wire [1:0] addr_match_mode_x;
  input mmu_addr_ge_bottom_x;
  wire mmu_addr_ge_bottom_x;
  output mmu_addr_ge_upaddr_x;
  wire mmu_addr_ge_upaddr_x;
  input [27:0] mmu_pmp_pa_y;
  wire [27:0] mmu_pmp_pa_y;
  output pmp_mmu_hit_x;
  wire pmp_mmu_hit_x;
  input [28:0] pmpaddr_x_value;
  wire [28:0] pmpaddr_x_value;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire mmu_na4_addr_match;
  sky130_fd_sc_hd__clkinv_1 _147_ (
    .A(mmu_pmp_pa_y[27]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__clkinv_1 _148_ (
    .A(mmu_pmp_pa_y[26]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__clkinv_1 _149_ (
    .A(pmpaddr_x_value[26]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__clkinv_1 _150_ (
    .A(pmpaddr_x_value[25]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(mmu_pmp_pa_y[0]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__clkinv_1 _152_ (
    .A(pmpaddr_x_value[6]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__clkinv_1 _153_ (
    .A(pmpaddr_x_value[12]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__clkinv_1 _154_ (
    .A(pmpaddr_x_value[10]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__clkinv_1 _155_ (
    .A(pmpaddr_x_value[9]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__clkinv_1 _156_ (
    .A(pmpaddr_x_value[16]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__clkinv_1 _157_ (
    .A(pmpaddr_x_value[14]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__clkinv_1 _158_ (
    .A(mmu_pmp_pa_y[23]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__clkinv_1 _159_ (
    .A(mmu_pmp_pa_y[22]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__clkinv_1 _160_ (
    .A(pmpaddr_x_value[22]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__clkinv_1 _161_ (
    .A(mmu_pmp_pa_y[19]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__clkinv_1 _162_ (
    .A(pmpaddr_x_value[18]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__xnor2_1 _163_ (
    .A(pmpaddr_x_value[28]),
    .B(mmu_pmp_pa_y[27]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2b_1 _164_ (
    .A_N(pmpaddr_x_value[27]),
    .B(mmu_pmp_pa_y[26]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _165_ (
    .A(_126_),
    .B(_127_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _166_ (
    .A1(_111_),
    .A2(pmpaddr_x_value[27]),
    .B1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o21ai_0 _167_ (
    .A1(_112_),
    .A2(mmu_pmp_pa_y[25]),
    .B1(_129_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _168_ (
    .A(mmu_pmp_pa_y[25]),
    .SLEEP(pmpaddr_x_value[26]),
    .X(_131_)
  );
  sky130_fd_sc_hd__a21oi_1 _169_ (
    .A1(mmu_pmp_pa_y[24]),
    .A2(_113_),
    .B1(_131_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21ai_0 _170_ (
    .A1(mmu_pmp_pa_y[24]),
    .A2(_113_),
    .B1(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _171_ (
    .A(_130_),
    .SLEEP(_133_),
    .X(_134_)
  );
  sky130_fd_sc_hd__xnor2_1 _172_ (
    .A(mmu_pmp_pa_y[17]),
    .B(pmpaddr_x_value[18]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _173_ (
    .A(mmu_pmp_pa_y[16]),
    .SLEEP(pmpaddr_x_value[17]),
    .X(_136_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _174_ (
    .A(pmpaddr_x_value[17]),
    .SLEEP(mmu_pmp_pa_y[16]),
    .X(_137_)
  );
  sky130_fd_sc_hd__nor3b_1 _175_ (
    .A(_136_),
    .B(_137_),
    .C_N(_135_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2b_1 _176_ (
    .A_N(pmpaddr_x_value[2]),
    .B(mmu_pmp_pa_y[1]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _177_ (
    .A(pmpaddr_x_value[3]),
    .SLEEP(mmu_pmp_pa_y[2]),
    .X(_140_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _178_ (
    .A(pmpaddr_x_value[2]),
    .SLEEP(mmu_pmp_pa_y[1]),
    .X(_141_)
  );
  sky130_fd_sc_hd__a311oi_1 _179_ (
    .A1(pmpaddr_x_value[1]),
    .A2(_114_),
    .A3(_139_),
    .B1(_140_),
    .C1(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _180_ (
    .A(mmu_pmp_pa_y[3]),
    .SLEEP(pmpaddr_x_value[4]),
    .X(_143_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _181_ (
    .A(mmu_pmp_pa_y[2]),
    .SLEEP(pmpaddr_x_value[3]),
    .X(_144_)
  );
  sky130_fd_sc_hd__nand2b_1 _182_ (
    .A_N(mmu_pmp_pa_y[4]),
    .B(pmpaddr_x_value[5]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nand2b_1 _183_ (
    .A_N(mmu_pmp_pa_y[3]),
    .B(pmpaddr_x_value[4]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o311ai_0 _184_ (
    .A1(_142_),
    .A2(_143_),
    .A3(_144_),
    .B1(_145_),
    .C1(_146_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2b_1 _185_ (
    .A_N(pmpaddr_x_value[5]),
    .B(mmu_pmp_pa_y[4]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(_115_),
    .B(mmu_pmp_pa_y[5]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2b_1 _187_ (
    .A_N(mmu_pmp_pa_y[6]),
    .B(pmpaddr_x_value[7]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o21ai_0 _188_ (
    .A1(_115_),
    .A2(mmu_pmp_pa_y[5]),
    .B1(_003_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a31oi_1 _189_ (
    .A1(_000_),
    .A2(_001_),
    .A3(_002_),
    .B1(_004_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2b_1 _190_ (
    .A_N(pmpaddr_x_value[8]),
    .B(mmu_pmp_pa_y[7]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2b_1 _191_ (
    .A_N(pmpaddr_x_value[7]),
    .B(mmu_pmp_pa_y[6]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(_006_),
    .B(_007_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2b_1 _193_ (
    .A_N(mmu_pmp_pa_y[7]),
    .B(pmpaddr_x_value[8]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o221ai_1 _194_ (
    .A1(_118_),
    .A2(mmu_pmp_pa_y[8]),
    .B1(_005_),
    .B2(_008_),
    .C1(_009_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a22oi_1 _195_ (
    .A1(mmu_pmp_pa_y[9]),
    .A2(_117_),
    .B1(_118_),
    .B2(mmu_pmp_pa_y[8]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _196_ (
    .A(mmu_pmp_pa_y[10]),
    .SLEEP(pmpaddr_x_value[11]),
    .X(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _197_ (
    .A(mmu_pmp_pa_y[10]),
    .B(pmpaddr_x_value[11]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__xnor2_1 _198_ (
    .A(pmpaddr_x_value[12]),
    .B(mmu_pmp_pa_y[11]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o211ai_1 _199_ (
    .A1(mmu_pmp_pa_y[9]),
    .A2(_117_),
    .B1(_013_),
    .C1(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _200_ (
    .A1(_010_),
    .A2(_011_),
    .B1(_015_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__maj3_1 _201_ (
    .A(_116_),
    .B(mmu_pmp_pa_y[11]),
    .C(_012_),
    .X(_017_)
  );
  sky130_fd_sc_hd__xor2_1 _202_ (
    .A(pmpaddr_x_value[16]),
    .B(mmu_pmp_pa_y[15]),
    .X(_018_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _203_ (
    .A(mmu_pmp_pa_y[14]),
    .SLEEP(pmpaddr_x_value[15]),
    .X(_019_)
  );
  sky130_fd_sc_hd__xor2_1 _204_ (
    .A(mmu_pmp_pa_y[14]),
    .B(pmpaddr_x_value[15]),
    .X(_020_)
  );
  sky130_fd_sc_hd__nor2_1 _205_ (
    .A(_018_),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xnor2_1 _206_ (
    .A(pmpaddr_x_value[14]),
    .B(mmu_pmp_pa_y[13]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _207_ (
    .A(mmu_pmp_pa_y[12]),
    .SLEEP(pmpaddr_x_value[13]),
    .X(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _208_ (
    .A(mmu_pmp_pa_y[12]),
    .B(pmpaddr_x_value[13]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o2111ai_1 _209_ (
    .A1(_016_),
    .A2(_017_),
    .B1(_021_),
    .C1(_022_),
    .D1(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__maj3_1 _210_ (
    .A(_120_),
    .B(mmu_pmp_pa_y[13]),
    .C(_023_),
    .X(_026_)
  );
  sky130_fd_sc_hd__maj3_1 _211_ (
    .A(_119_),
    .B(mmu_pmp_pa_y[15]),
    .C(_019_),
    .X(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _212_ (
    .A1(_021_),
    .A2(_026_),
    .B1(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a21boi_0 _213_ (
    .A1(_025_),
    .A2(_028_),
    .B1_N(_138_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__maj3_1 _214_ (
    .A(mmu_pmp_pa_y[17]),
    .B(_125_),
    .C(_136_),
    .X(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _215_ (
    .A(mmu_pmp_pa_y[23]),
    .B(pmpaddr_x_value[24]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2b_1 _216_ (
    .A_N(pmpaddr_x_value[23]),
    .B(mmu_pmp_pa_y[22]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _218_ (
    .A1(pmpaddr_x_value[23]),
    .A2(_122_),
    .B1(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _219_ (
    .A(mmu_pmp_pa_y[20]),
    .SLEEP(pmpaddr_x_value[21]),
    .X(_035_)
  );
  sky130_fd_sc_hd__xor2_1 _220_ (
    .A(mmu_pmp_pa_y[20]),
    .B(pmpaddr_x_value[21]),
    .X(_036_)
  );
  sky130_fd_sc_hd__xor2_1 _221_ (
    .A(pmpaddr_x_value[22]),
    .B(mmu_pmp_pa_y[21]),
    .X(_037_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(_034_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xor2_1 _224_ (
    .A(pmpaddr_x_value[20]),
    .B(mmu_pmp_pa_y[19]),
    .X(_040_)
  );
  sky130_fd_sc_hd__nand2b_1 _225_ (
    .A_N(pmpaddr_x_value[19]),
    .B(mmu_pmp_pa_y[18]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__xor2_1 _226_ (
    .A(pmpaddr_x_value[19]),
    .B(mmu_pmp_pa_y[18]),
    .X(_042_)
  );
  sky130_fd_sc_hd__nor3_1 _227_ (
    .A(_039_),
    .B(_040_),
    .C(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21ai_0 _228_ (
    .A1(_029_),
    .A2(_030_),
    .B1(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__maj3_1 _229_ (
    .A(pmpaddr_x_value[20]),
    .B(_124_),
    .C(_041_),
    .X(_045_)
  );
  sky130_fd_sc_hd__maj3_1 _230_ (
    .A(_121_),
    .B(pmpaddr_x_value[24]),
    .C(_032_),
    .X(_046_)
  );
  sky130_fd_sc_hd__maj3_1 _231_ (
    .A(_123_),
    .B(mmu_pmp_pa_y[21]),
    .C(_035_),
    .X(_047_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _232_ (
    .A1_N(_039_),
    .A2_N(_045_),
    .B1(_047_),
    .B2(_034_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a31o_1 _233_ (
    .A1(_044_),
    .A2(_046_),
    .A3(_048_),
    .B1(_134_),
    .X(_049_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _234_ (
    .A(_130_),
    .SLEEP(_132_),
    .X(_050_)
  );
  sky130_fd_sc_hd__maj3_1 _235_ (
    .A(pmpaddr_x_value[28]),
    .B(_110_),
    .C(_127_),
    .X(_051_)
  );
  sky130_fd_sc_hd__nand3_1 _236_ (
    .A(_049_),
    .B(_050_),
    .C(_051_),
    .Y(mmu_addr_ge_upaddr_x)
  );
  sky130_fd_sc_hd__and3b_1 _237_ (
    .A_N(addr_match_mode_x[1]),
    .B(addr_match_mode_x[0]),
    .C(mmu_addr_ge_bottom_x),
    .X(_052_)
  );
  sky130_fd_sc_hd__nand4_1 _238_ (
    .A(_049_),
    .B(_050_),
    .C(_051_),
    .D(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(pmpaddr_x_value[21]),
    .B(pmpaddr_x_value[20]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__and2_0 _240_ (
    .A(pmpaddr_x_value[18]),
    .B(pmpaddr_x_value[17]),
    .X(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(pmpaddr_x_value[1]),
    .B(pmpaddr_x_value[0]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand3_1 _242_ (
    .A(pmpaddr_x_value[2]),
    .B(pmpaddr_x_value[1]),
    .C(pmpaddr_x_value[0]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__and4_1 _243_ (
    .A(pmpaddr_x_value[2]),
    .B(pmpaddr_x_value[1]),
    .C(pmpaddr_x_value[3]),
    .D(pmpaddr_x_value[0]),
    .X(_058_)
  );
  sky130_fd_sc_hd__and4_1 _244_ (
    .A(pmpaddr_x_value[5]),
    .B(pmpaddr_x_value[4]),
    .C(pmpaddr_x_value[6]),
    .D(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__and3_1 _245_ (
    .A(pmpaddr_x_value[7]),
    .B(pmpaddr_x_value[8]),
    .C(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(pmpaddr_x_value[9]),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand4_1 _247_ (
    .A(pmpaddr_x_value[5]),
    .B(pmpaddr_x_value[4]),
    .C(pmpaddr_x_value[6]),
    .D(_058_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _248_ (
    .A(pmpaddr_x_value[7]),
    .SLEEP(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and4_1 _249_ (
    .A(pmpaddr_x_value[8]),
    .B(pmpaddr_x_value[10]),
    .C(pmpaddr_x_value[9]),
    .D(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__and4_1 _250_ (
    .A(pmpaddr_x_value[12]),
    .B(pmpaddr_x_value[11]),
    .C(pmpaddr_x_value[13]),
    .D(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(pmpaddr_x_value[14]),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand3_1 _252_ (
    .A(pmpaddr_x_value[15]),
    .B(pmpaddr_x_value[14]),
    .C(_065_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__and4_1 _253_ (
    .A(pmpaddr_x_value[16]),
    .B(pmpaddr_x_value[15]),
    .C(pmpaddr_x_value[14]),
    .D(_065_),
    .X(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_055_),
    .B(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand3_1 _255_ (
    .A(pmpaddr_x_value[19]),
    .B(_055_),
    .C(_068_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(_054_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand4_1 _257_ (
    .A(pmpaddr_x_value[19]),
    .B(pmpaddr_x_value[20]),
    .C(_055_),
    .D(_068_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a21oi_1 _258_ (
    .A1(pmpaddr_x_value[22]),
    .A2(_071_),
    .B1(_034_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(_134_),
    .B(_073_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand3_1 _260_ (
    .A(pmpaddr_x_value[24]),
    .B(pmpaddr_x_value[23]),
    .C(pmpaddr_x_value[22]),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a41oi_1 _261_ (
    .A1(pmpaddr_x_value[24]),
    .A2(pmpaddr_x_value[23]),
    .A3(pmpaddr_x_value[22]),
    .A4(_071_),
    .B1(_074_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _262_ (
    .A(_018_),
    .B(_067_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _263_ (
    .A(_022_),
    .B(_065_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a22oi_1 _264_ (
    .A1(_014_),
    .A2(_024_),
    .B1(_064_),
    .B2(pmpaddr_x_value[11]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _265_ (
    .A(_013_),
    .B(_064_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _266_ (
    .A(pmpaddr_x_value[9]),
    .B(mmu_pmp_pa_y[8]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__xnor2_1 _267_ (
    .A(mmu_pmp_pa_y[9]),
    .B(pmpaddr_x_value[10]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__o21ai_0 _268_ (
    .A1(_060_),
    .A2(_081_),
    .B1(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__xnor2_1 _269_ (
    .A(pmpaddr_x_value[6]),
    .B(mmu_pmp_pa_y[5]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a32oi_1 _270_ (
    .A1(_145_),
    .A2(_001_),
    .A3(_084_),
    .B1(_058_),
    .B2(pmpaddr_x_value[4]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(_003_),
    .B(_007_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__o21ai_0 _272_ (
    .A1(_085_),
    .A2(_086_),
    .B1(_062_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a31oi_1 _273_ (
    .A1(_006_),
    .A2(_009_),
    .A3(_087_),
    .B1(_063_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _274_ (
    .A(_130_),
    .B(_131_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2b_1 _275_ (
    .A(_143_),
    .B_N(_146_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xnor2_1 _276_ (
    .A(pmpaddr_x_value[1]),
    .B(mmu_pmp_pa_y[0]),
    .Y(_091_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _277_ (
    .A(_139_),
    .SLEEP(_141_),
    .X(_092_)
  );
  sky130_fd_sc_hd__o21ai_0 _278_ (
    .A1(pmpaddr_x_value[0]),
    .A2(_091_),
    .B1(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ai_0 _279_ (
    .A1(_140_),
    .A2(_144_),
    .B1(_057_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__o22a_1 _280_ (
    .A1(pmpaddr_x_value[27]),
    .A2(_126_),
    .B1(_129_),
    .B2(pmpaddr_x_value[26]),
    .X(_095_)
  );
  sky130_fd_sc_hd__nor4_1 _281_ (
    .A(_113_),
    .B(_054_),
    .C(_075_),
    .D(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _282_ (
    .A(_037_),
    .SLEEP(_071_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2i_1 _283_ (
    .A0(_096_),
    .A1(_040_),
    .S(_070_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a22oi_1 _284_ (
    .A1(_036_),
    .A2(_072_),
    .B1(_083_),
    .B2(_061_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand3_1 _285_ (
    .A(addr_match_mode_x[1]),
    .B(addr_match_mode_x[0]),
    .C(_094_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o22ai_1 _286_ (
    .A1(pmpaddr_x_value[17]),
    .A2(_135_),
    .B1(_058_),
    .B2(_090_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o22ai_1 _287_ (
    .A1(pmpaddr_x_value[12]),
    .A2(_024_),
    .B1(_084_),
    .B2(pmpaddr_x_value[5]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__a21oi_1 _288_ (
    .A1(_056_),
    .A2(_093_),
    .B1(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__o21ai_0 _289_ (
    .A1(pmpaddr_x_value[25]),
    .A2(_089_),
    .B1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__or4_1 _290_ (
    .A(_080_),
    .B(_100_),
    .C(_101_),
    .D(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd__a2111oi_0 _291_ (
    .A1(_020_),
    .A2(_066_),
    .B1(_078_),
    .C1(_079_),
    .D1(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__o211ai_1 _292_ (
    .A1(_138_),
    .A2(_068_),
    .B1(_077_),
    .C1(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a2111oi_0 _293_ (
    .A1(_042_),
    .A2(_069_),
    .B1(_088_),
    .C1(_097_),
    .D1(_107_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o2111ai_1 _294_ (
    .A1(pmpaddr_x_value[23]),
    .A2(_031_),
    .B1(_098_),
    .C1(_099_),
    .D1(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__o21ai_0 _295_ (
    .A1(_076_),
    .A2(_109_),
    .B1(_053_),
    .Y(pmp_mmu_hit_x)
  );
  assign mmu_na4_addr_match = 1'h0;
endmodule
