module contract_top(output bad);
  (* anyconst *) reg [6:0] iu_idu_ex1_pipe0_fwd_preg;
  (* anyconst *) reg [63:0] iu_idu_ex1_pipe0_fwd_preg_data;
  (* anyconst *) reg iu_idu_ex1_pipe0_fwd_preg_vld;
  (* anyconst *) reg [6:0] iu_idu_ex1_pipe1_fwd_preg;
  (* anyconst *) reg [63:0] iu_idu_ex1_pipe1_fwd_preg_data;
  (* anyconst *) reg iu_idu_ex1_pipe1_fwd_preg_vld;
  (* anyconst *) reg [6:0] iu_idu_ex2_pipe0_wb_preg;
  (* anyconst *) reg [63:0] iu_idu_ex2_pipe0_wb_preg_data;
  (* anyconst *) reg iu_idu_ex2_pipe0_wb_preg_vld;
  (* anyconst *) reg [6:0] iu_idu_ex2_pipe1_wb_preg;
  (* anyconst *) reg [63:0] iu_idu_ex2_pipe1_wb_preg_data;
  (* anyconst *) reg iu_idu_ex2_pipe1_wb_preg_vld;
  (* anyconst *) reg [6:0] lsu_idu_da_pipe3_fwd_preg;
  (* anyconst *) reg [63:0] lsu_idu_da_pipe3_fwd_preg_data;
  (* anyconst *) reg lsu_idu_da_pipe3_fwd_preg_vld;
  (* anyconst *) reg [6:0] lsu_idu_wb_pipe3_wb_preg;
  (* anyconst *) reg [63:0] lsu_idu_wb_pipe3_wb_preg_data;
  (* anyconst *) reg lsu_idu_wb_pipe3_wb_preg_vld;
  (* anyconst *) reg [6:0] x_src_reg;
  wire [63:0] gold_x_src_data;
  wire gold_x_src_no_fwd;
  wire [63:0] gate_x_src_data;
  wire gate_x_src_no_fwd;
  gold gold_i (.iu_idu_ex1_pipe0_fwd_preg(iu_idu_ex1_pipe0_fwd_preg), .iu_idu_ex1_pipe0_fwd_preg_data(iu_idu_ex1_pipe0_fwd_preg_data), .iu_idu_ex1_pipe0_fwd_preg_vld(iu_idu_ex1_pipe0_fwd_preg_vld), .iu_idu_ex1_pipe1_fwd_preg(iu_idu_ex1_pipe1_fwd_preg), .iu_idu_ex1_pipe1_fwd_preg_data(iu_idu_ex1_pipe1_fwd_preg_data), .iu_idu_ex1_pipe1_fwd_preg_vld(iu_idu_ex1_pipe1_fwd_preg_vld), .iu_idu_ex2_pipe0_wb_preg(iu_idu_ex2_pipe0_wb_preg), .iu_idu_ex2_pipe0_wb_preg_data(iu_idu_ex2_pipe0_wb_preg_data), .iu_idu_ex2_pipe0_wb_preg_vld(iu_idu_ex2_pipe0_wb_preg_vld), .iu_idu_ex2_pipe1_wb_preg(iu_idu_ex2_pipe1_wb_preg), .iu_idu_ex2_pipe1_wb_preg_data(iu_idu_ex2_pipe1_wb_preg_data), .iu_idu_ex2_pipe1_wb_preg_vld(iu_idu_ex2_pipe1_wb_preg_vld), .lsu_idu_da_pipe3_fwd_preg(lsu_idu_da_pipe3_fwd_preg), .lsu_idu_da_pipe3_fwd_preg_data(lsu_idu_da_pipe3_fwd_preg_data), .lsu_idu_da_pipe3_fwd_preg_vld(lsu_idu_da_pipe3_fwd_preg_vld), .lsu_idu_wb_pipe3_wb_preg(lsu_idu_wb_pipe3_wb_preg), .lsu_idu_wb_pipe3_wb_preg_data(lsu_idu_wb_pipe3_wb_preg_data), .lsu_idu_wb_pipe3_wb_preg_vld(lsu_idu_wb_pipe3_wb_preg_vld), .x_src_data(gold_x_src_data), .x_src_no_fwd(gold_x_src_no_fwd), .x_src_reg(x_src_reg));
  gate gate_i (.iu_idu_ex1_pipe0_fwd_preg(iu_idu_ex1_pipe0_fwd_preg), .iu_idu_ex1_pipe0_fwd_preg_data(iu_idu_ex1_pipe0_fwd_preg_data), .iu_idu_ex1_pipe0_fwd_preg_vld(iu_idu_ex1_pipe0_fwd_preg_vld), .iu_idu_ex1_pipe1_fwd_preg(iu_idu_ex1_pipe1_fwd_preg), .iu_idu_ex1_pipe1_fwd_preg_data(iu_idu_ex1_pipe1_fwd_preg_data), .iu_idu_ex1_pipe1_fwd_preg_vld(iu_idu_ex1_pipe1_fwd_preg_vld), .iu_idu_ex2_pipe0_wb_preg(iu_idu_ex2_pipe0_wb_preg), .iu_idu_ex2_pipe0_wb_preg_data(iu_idu_ex2_pipe0_wb_preg_data), .iu_idu_ex2_pipe0_wb_preg_vld(iu_idu_ex2_pipe0_wb_preg_vld), .iu_idu_ex2_pipe1_wb_preg(iu_idu_ex2_pipe1_wb_preg), .iu_idu_ex2_pipe1_wb_preg_data(iu_idu_ex2_pipe1_wb_preg_data), .iu_idu_ex2_pipe1_wb_preg_vld(iu_idu_ex2_pipe1_wb_preg_vld), .lsu_idu_da_pipe3_fwd_preg(lsu_idu_da_pipe3_fwd_preg), .lsu_idu_da_pipe3_fwd_preg_data(lsu_idu_da_pipe3_fwd_preg_data), .lsu_idu_da_pipe3_fwd_preg_vld(lsu_idu_da_pipe3_fwd_preg_vld), .lsu_idu_wb_pipe3_wb_preg(lsu_idu_wb_pipe3_wb_preg), .lsu_idu_wb_pipe3_wb_preg_data(lsu_idu_wb_pipe3_wb_preg_data), .lsu_idu_wb_pipe3_wb_preg_vld(lsu_idu_wb_pipe3_wb_preg_vld), .x_src_data(gate_x_src_data), .x_src_no_fwd(gate_x_src_no_fwd), .x_src_reg(x_src_reg));
  wire [5:0] contract_sel = {(lsu_idu_wb_pipe3_wb_preg_vld && (x_src_reg[6:0] == lsu_idu_wb_pipe3_wb_preg[6:0])), (lsu_idu_da_pipe3_fwd_preg_vld && (x_src_reg[6:0] == lsu_idu_da_pipe3_fwd_preg[6:0])), (iu_idu_ex2_pipe1_wb_preg_vld && (x_src_reg[6:0] == iu_idu_ex2_pipe1_wb_preg[6:0])), (iu_idu_ex1_pipe1_fwd_preg_vld && (x_src_reg[6:0] == iu_idu_ex1_pipe1_fwd_preg[6:0])), (iu_idu_ex2_pipe0_wb_preg_vld && (x_src_reg[6:0] == iu_idu_ex2_pipe0_wb_preg[6:0])), (iu_idu_ex1_pipe0_fwd_preg_vld && (x_src_reg[6:0] == iu_idu_ex1_pipe0_fwd_preg[6:0]))};
  wire contract_onehot = (contract_sel != 0) && ((contract_sel & (contract_sel - 1'b1)) == 0);
  wire no_fwd_bad = gold_x_src_no_fwd != gate_x_src_no_fwd;
  wire data_bad = contract_onehot && (gold_x_src_data != gate_x_src_data);
  assign bad = no_fwd_bad || data_bad;
endmodule
